### PR TITLE
Remove Generator multitarget special-cases

### PR DESCRIPTION
**Pull request by steven-johnson**
The code path for Generators formerly went thru compile_multitarget()
only for cases where there were multitargets; this meant that the
contents of static libraries (and the patterns of filename
substitution) could be subtly different for single- vs multi-target,
making some bugs hard to track down (since some Generator tests use
single and some use multi). Now, the code uniformly goes thru the
multitarget case; this means that a ‘wrapper’ function is now generated
for the single-target case where none was before, but in terms of code
size and speed, it’s essentially a wash (the wrapper is just the an
unconditional branch to the underlying function). This will make
subsequent changes to this code much easier to verify across all usages.

### CODE REVIEW

**Comment by abadams** [comment]
I'd rather avoid the wrapper, even it's just an unconditional branch. I'm starting to worry about the number of wrappers that exist around our generated code, and having slightly more code complexity in the compiler to avoid one layer seems like a good trade-off to me.

**Comment by steven-johnson** [comment]
Good point; reworked to avoid the wrapper entirely for this case (but still going thru compile_multitarget).

**Comment by steven-johnson** [comment]
(IMHO this PR is still desirable, as it does reduce the surface area of testing for Generators, but it should probably be retitled something like "Change the multitarget special cases to all-new all-different special cases")

**Comment by steven-johnson** [comment]
Finally green. PTAL.

**Comment by abadams** [comment]
This may have broken the tutorials: https://buildbot.halide-lang.org/master/builders/linux-64-gcc49-381/builds/287/steps/make%20test_tutorials/logs/stdio

**Comment by steven-johnson** [comment]
Output file name for .stmt is different now. There are more worms in this can than I anticipated. Might just roll it back and rethink.

**Pull request merged**
