### PR TITLE
Remove scoped truths that might introduce new side effects

### PR DESCRIPTION
**Pull request by abadams**
These mutations could cause out-of-bounds reads and divide-by-zeros on the mutated side. An example of an error:

```
(x < 0) || (f(max(x, 0) == 3)
```
assume LHS is false on RHS ->
```
(x < 0) || f(x) == 3
```

Now vectorize x (so no short-circuiting) and evaluate it at a negative x.

The equivalent mutations were removed from the select operator before the new simplifier was merged, but I didn't catch these ones.

### CODE REVIEW

**Comment by steven-johnson** [comment]
What's the status on this PR?

**Comment by abadams** [comment]
The buildbots seem to be ignoring it :(

**Comment by abadams** [comment]
I'll try pushing a merge with master

**Comment by abadams** [comment]
Only failures are unrelated due to mac bot flux. PTAL.

**Pull request merged**
