### PR TITLE
only report failures in test_correctness

### PR DESCRIPTION
**Pull request by abadams**
Make test_correctness output only a . character for successful tests. Makes it easier to find failures when running at -j:

```

$ make test_correctness -j
...........................................................................................................................................................................................................................................................
FAILED TEST: chunk
Defining function...
Realizing function...
Success!
Makefile:1502: recipe for target 'quiet_correctness_chunk' failed
make: *** [quiet_correctness_chunk] Error 1
make: *** Waiting for unfinished jobs....
...............
```

I've found myself running a -j4 on an 80-thread machine just so I can find failures more easily, which is ridiculous.

### CODE REVIEW

**Comment by dsharletg** [comment]
This passes travis and the build bots won't test this anyways (doesn't affect CMake build).

**Comment by abadams** [comment]
The buildbots do use the makefile, which is why I was delaying. E.g. see the much-improved error on the mingw builder.

**Comment by zvookin** [comment]
It is crazy that this isn't built into make, or some other tool, at this point.

**Comment by abadams** [comment]
Failure is unrelated.

**Pull request merged**
