### PR TITLE
Expand LLVM_CONFIG and CLANG for test_apps

### PR DESCRIPTION
**Pull request by steven-johnson**
The test_apps target recursively calls sub-makefiles (which can change the WD), but the buildbots define LLVM_CONFIG and CLANG as relative paths, so these can become invalid when building apps. (Why this hasn't caused more failures in the past is a bit of a mystery.) Use $(realpath) to explicitly expand these vars for the sub-makefile calls to address this.

### CODE REVIEW

**Comment by abadams** [comment]
I think the apps really shouldn't be using the LLVM_CONFIG and CLANG variables - those are strictly for compiling libHalide. Is there a case where they are?

**Comment by steven-johnson** [comment]
Makefile.inc uses `$(LLVM_CONFIG)` in a few places to get libs for linking (e.g. `$(LLVM_CONFIG) --libs`), so, yes, lots

**Comment by abadams** [comment]
Oh yeah, I remember seeing that and frowning. That's not great - the idea is that libHalide.so is supposed to encapsulate and hide any dependency on llvm. I'll see what actually breaks if I remove that. I suspect it's just for things like libz

**Comment by shoaibkamil** [comment]
Yes, I believe it's for libz/libcurses and the rest.  If we had a way of making those not required, it would be really great-- it's annoying having to figure out e.g. which curses replacement to use on different platforms in order to link against libHalide.so.

**Comment by steven-johnson** [comment]
Yeah, the main issue is system libs. 

We actually *almost* have a clean solution already, but only for CMake and Bazel: when building a distrib folder, we emit stubs (halide_config.bzl and halide_config.cmake) that indicate the system libs that are expected by libHalide. If we added a similar stub for Make, *and* modified the apps/ folder to always depend on on `distrib`, this wouldn't be necessary.

(IMHO having apps/ depend only on `distrib` would be good hygiene anyway; the python_bindings/ were built with that constraint in mind and it's worked well there. It would require someone to go thru and revise all the app buildfiles, though.)

**Comment by abadams** [comment]
I just deleted everything llvm-related from Makefile.inc. The only thing that was missing was -ltinfo. With that added, make test_apps passed. I'll open and PR and we can see which bots it fails on.

**Comment by steven-johnson** [comment]
> The only thing that was missing was -ltinfo

I will bet you a dollar that we'll find configurations that are broken in other ways. (I don't remember the details, but this stuff all got added to fix breakages in the past. Could look it up via blame.)

**Comment by abadams** [comment]
Yeah I'm not expected all the buildbots to pass. #3311

**Comment by steven-johnson** [comment]
See https://github.com/halide/Halide/pull/3312 -- this part 1 of a change that will enable us to cleanly remove the LLVM_CONFIG nonsense here.

**Comment by abadams** [comment]
Can this be closed now? Looks like the problem is fixed by your other merged PRs.

**Comment by steven-johnson** [comment]
obsolete

**Pull request closed without merging**
