### PR TITLE
[Vulkan] Region allocator fixes for memory requirements and allocations

### PR DESCRIPTION
**Pull request by derek-gerstmann**
As reported by https://github.com/halide/Halide/issues/8079

+ Add region allocator tests that check alignment, nearest_multiple and collect routines
+ Fix can_split() routine to use conformed sizes so that split allocation matches
+ Fix region size accounting so that coalesce never has zero size regions to merge
+ Fix aligned_offset() routine to check for zero alignment (which means no constraint)
+ Use Vulkan memory_requirements to determine nearest_multiple during initialization
+ Query Vulkan memory_requirements for each region, and reallocate if driver requires additional device memory

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]
LGTM. 

As a nit, there were a lot of superficial changes in debug output that made it harder to parse out the functional changes for review.

**Comment by derek-gerstmann** [comment]
> LGTM.
> 
> As a nit, there were a lot of superficial changes in debug output that made it harder to parse out the functional changes for review.

Yes, sorry. I tried to isolate the debug formatting stuff to separate commits.

**Comment by steven-johnson** [comment]
Ready to land?

**Comment by derek-gerstmann** [comment]
Yes, this one is done. There will be more fixes soon.

**Pull request merged**
