### PR TITLE
Conditionally run associativity prover in .reorder.

### PR DESCRIPTION
**Pull request by jingpu**
Only run the associativity prover when a user tries to reorder RVars. It is a performance optimization as the prover is not cheap to run. It is also to prevent the regression in compiling some existing Halide pipelines which the prover is not robust enough to handle. @dsharletg @zvookin

### CODE REVIEW

**Comment by zvookin** [comment]
Looks like we wrote effectively the same PR at the same time.

**Comment by abadams** [comment]
I don't understand the second part: regression in compiling some existing Halide pipelines.

Previously reordering rvars was straight-up illegal. The change to use the prover made some new cases legal, but it shouldn't have made anything that used to work stop working...

**Comment by steven-johnson** [comment]
Yeah, this and https://github.com/halide/Halide/pull/3248 look damn near the same. Either one is fine with me. I happened to review (and approve) the other one first but whichever is ready to land first is fine with me.

**Comment by zvookin** [comment]
@abadams Regression in that the compiler goes into an infinite loop trying to prove something that is not needed. At least that is what was happening on the async PR.

**Comment by jingpu** [comment]
@abadams , the regression refers to that the prover can crash in some existing pipelines that don't reorder two RVars (of course, none of existing pipelines does this).

@zvookin I will close mine.

**Comment by steven-johnson** [comment]
@jingpu how hard would it be to extract one of the failing google pipelines into a form we could post here? might be interesting to have more folks see the failure mode.

**Comment by dsharletg** [comment]
It sounds like @zvookin already has some open source examples in the async branch

**Comment by jingpu** [comment]
Re @steven-johnson, @psuriana is looking at a case we found internally at Google.

**Comment by psuriana** [comment]
@jingpu @steven-johnson Found the cause of the internal failure at Google, it was a really stupid bug. See #3251

**Pull request closed without merging**
