### PR TITLE
Upgrade pybind11 to 2.6.x

### PR DESCRIPTION
**Pull request by alexreinking**
Users who have 2.6.0 installed system-wide run into an issue with a hack with a workaround etc. etc. in pybind11 that ultimately means it chokes on the `SYSTEM` argument to `pybind11_add_module` on v2.6 but not on v2.5.

Since we're already diverged from Ubuntu, we might as well upgrade to pybind11 2.6, which also happens to fix a bug that lets us remove one of our own awkward workarounds.

### CODE REVIEW

**Comment by steven-johnson** [comment]
LGTM but will wait to see how the buildbots like it :-)

**Comment by steven-johnson** [comment]
Producing lots of warnings on (at least) the Mac build (https://buildbot.halide-lang.org/master/#/builders/49/builds/123/steps/12/logs/stdio) -- would be good to clean these up.

**Comment by alexreinking** [comment]
> 
> 
> Producing lots of warnings on (at least) the Mac build (https://buildbot.halide-lang.org/master/#/builders/49/builds/123/steps/12/logs/stdio) -- would be good to clean these up.

That's a make-builder. No idea how this change could affect it.

**Comment by steven-johnson** [comment]
(1) there are warnings in the Linux build too (at least on my system)
(2) ack, how to Makefile builds use PyBind11 then? Is it just expected to be present on the system? If so, do we need to manually upgrade the installs on the buildbots?

**Comment by alexreinking** [comment]
> (1) there are warnings in the Linux build too (at least on my system)

The only [warnings I see on `x86-64-linux-testbranch-12-cmake` ](https://buildbot.halide-lang.org/master/#/builders/30/builds/161/steps/7/logs/stdio) are the following:

```
[1874/3367] Building CXX object python_bindings/CMakeFiles/Halide_PyStubs.dir/stub/PyStubImpl.cpp.o
/home/halidenightly/build_bot/worker/x86-64-linux-testbranch-12-cmake/halide-source/python_bindings/stub/PyStubImpl.cpp: In function ‘PyObject* _halide_pystub_impl(const char*, FactoryFunc)’:
/home/halidenightly/build_bot/worker/x86-64-linux-testbranch-12-cmake/halide-source/python_bindings/stub/PyStubImpl.cpp:200:42: warning: ‘pybind11::module_::module_(const char*, const char*)’ is deprecated: Use PYBIND11_MODULE or module_::create_extension_module instead [-Wdeprecated-declarations]
     auto m = pybind11::module(module_name);
                                          ^
In file included from /home/halidenightly/build_bot/worker/x86-64-linux-testbranch-12-cmake/halide-source/python_bindings/stub/PyStubImpl.cpp:6:0:
_deps/pybind11-src/include/pybind11/pybind11.h:897:14: note: declared here
     explicit module_(const char *name, const char *doc = nullptr) {
              ^~~~~~~
```

which, yeah, I should fix.

> (2) ack, how to Makefile builds use PyBind11 then? Is it just expected to be present on the system? If so, do we need to manually upgrade the installs on the buildbots?

Yes. I think they look for a system-wide installation. Ideally, we'd put this in the requirements.txt (also TODO, I guess) and have the buildbot create fresh virtualenvs as needed.

**Comment by steven-johnson** [comment]
Suggestion: add something like `static_assert(PYBIND11_VERSION == 2.6);` somewhere in our PyBind code, so that we can double-verify that we are always building with the version we expect

**Comment by steven-johnson** [comment]
Also need to update requirements.txt:

`pybind11==2.5.0`

**Comment by steven-johnson** [comment]
(nm, I'll push the requirements and version-check myself)

**Comment by alexreinking** [comment]
Can we do `>=` for the minor version?

**Comment by steven-johnson** [comment]
> Can we do `>=` for the minor version?

We *could*, but I'd rather not be surprised by a newer version breaking us somehow. How about we change it if/when it becomes a problem?

**Comment by steven-johnson** [comment]
I updated the buildbots (manually) via `pip3 install pybind11==2.6.0`

**Comment by alexreinking** [comment]
Hrm, I'm generally against inserting hard blocks against newer versions. We're certainly not going to upgrade the buildbots unexpectedly. And now if someone wants to compile Halide against a newer version, they'll have to modify our sources. That's not so nice. Having a min-version check makes sense since it won't compile anyway, but at least this improves the error message.

**Comment by steven-johnson** [comment]
Looks like the extra warnings on OSX+Make are because that defaults to `-Wrange-loop-analysis` enabled and PyBind11 itself is triggering it. I'll disable the warning.

**Comment by steven-johnson** [comment]
> Hrm, I'm generally against inserting hard blocks against newer versions. We're certainly not going to upgrade the buildbots unexpectedly. And now if someone wants to compile Halide against a newer version, they'll have to modify our sources. That's not so nice. Having a min-version check makes sense since it won't compile anyway, but at least this improves the error message.

meh, ok

**Comment by steven-johnson** [comment]
Looking at the PyBind11 repo, it looks like 2.6.1 is the latest. Any reason we shouldn't upgrade to that?

**Comment by alexreinking** [comment]
> 
> 
> Looking at the PyBind11 repo, it looks like 2.6.1 is the latest. Any reason we shouldn't upgrade to that?

No reason I know of

**Comment by alexreinking** [comment]
`correctness_mul_div_mod` failure is unrelated.

**Review by steven-johnson — APPROVED** [review]

**Pull request merged**
