### PR TITLE
It's generally a bad idea for simplifier rules to multiply constants

### LINKED ISSUE #8227: Signed integer overflow occurred during constant-folding. Signed integer overflow for int32 and int64 is undefined behavior in Halide.
repro.py:
```py
import halide as hl
import sys
import tempfile

N = 5794


@hl.generator(name="kernel")
class Kernel:
    in_ptr0 = hl.InputBuffer(hl.Float(32), 1)
    out_ptr0 = hl.OutputBuffer(hl.Float(32), 1)

    def generate(g):
        in_ptr0 = g.in_ptr0
        out_ptr0 = g.out_ptr0
        xindex = hl.Var("xindex")
        yindex = hl.Var("yindex")
        tmp0 = hl.Func()
        tmp0[yindex, xindex] = in_ptr0[yindex + (64 * xindex)]
        out_ptr0_index = hl.Var("out_ptr0_index")
        out_ptr0[out_ptr0_index] = tmp0[
            out_ptr0_index // N, out_ptr0_index % N
        ]

        # same issue with autoscheduler enabled
        # in_ptr0.set_estimates([hl.Range(0, 1914624)])
        # out_ptr0.set_estimates([hl.Range(0, 1914624)])


with tempfile.TemporaryDirectory() as outdir:
    sys.argv = [
        "repro.py",
        "-g", "kernel",
        "-o", outdir,
        "-f", "halide_kernel",
        "-e", "static_library,h,schedule",
        "target=host-large_buffers-debug",
    ]
    hl.main()
```

Throws the following error when run:
```
Unhandled exception: Error: Signed integer overflow occurred during constant-folding. Signed integer overflow for int32 and int64 is undefined behavior in Halide.

Traceback (most recent call last):
  File "/home/jansel/pytorch/repro.py", line 39, in <module>
    hl.main()
RuntimeError: Generator failed: -1
```

However, this passes if I reduce `N` by 1:
```py
N = 5793
```

In my original program `N` was larger, but I reduced it to find the error threshold.  I observed this error in a much larger program generated by `torch.compile`, but minified it to find the smallest reproducer for the error.

I am a bit surprised by this, because `5794*64` is nowhere close to INT32_MAX, and I am only dealing with buffers of a few MB.

### PR DESCRIPTION
**Pull request by abadams**
Fixes #8227 but may break other things. Needs thorough testing.

Also, there are more rules like this lurking.

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]

**Comment by steven-johnson** [comment]
Ready to land?

**Comment by abadams** [comment]
I think this one probably needs testing inside Google. We may need more simplifier rules to patch up the holes left by the deleted ones.

**Comment by steven-johnson** [comment]
> I think this one probably needs testing inside Google. We may need more simplifier rules to patch up the holes left by the deleted ones.

ok, I'll run a full test

**Comment by steven-johnson** [comment]
Looks clean inside Google.

**Pull request merged**
