### PR TITLE
Make CodeGen_C aware of count_leading_zeros

### PR DESCRIPTION
**Pull request by matthiaskramm**

### CODE REVIEW

**Comment by zvookin** [comment]
Will try to review shortly, but I think we're likely going to need to make the code conditional on that builtin being available and back it up with generic code for other compilers. There's also the issue that the C backend us used for GPU languages as well and we'll need to make sure this intrinsic is handled in each of them as well. (It may already be so handled.)

**Comment by matthiaskramm** [comment]
Would it be easier to just use generic code all the time? It's not a very common intrinsic.

**Comment by steven-johnson** [comment]
LGTM -- please sync to master and I'll clone for buildbots

**Comment by matthiaskramm** [comment]
Rebased on top of master.

**Comment by matthiaskramm** [comment]
Spurious segfaults in unrelated tests. Rebased on newest master.

**Comment by steven-johnson** [comment]
Buildbots finally back up. Please sync this to master, then I'll clone and test.

**Comment by matthiaskramm** [comment]
Rebased on top of master.

**Comment by steven-johnson** [comment]
Could you (again) sync this to master for testing purposes?

**Comment by matthiaskramm** [comment]
Rebased on top of master.

**Comment by steven-johnson** [comment]
Failures are unrelated. Thanks for your patience!

**Pull request merged**
