### PR TITLE
Make LLVM_DIR take precedence when searching for Clang.

### PR DESCRIPTION
**Pull request by alexreinking**
@abadams reported a find_package issue with Clang locally. This patch works for me and for him. Let's see if the buildbots like it.

### CODE REVIEW

**Comment by alexreinking** [comment]
@steven-johnson is there some way we can stop the non-cmake bots from running on PRs that change only files named "CMakeLists.txt" or "*.cmake"?

**Comment by steven-johnson** [comment]
Possible? Certainly. I'd have to go dive in to figure out how, though.

**Comment by alexreinking** [comment]
I think doing so will save us some real time in the short-medium term as people open issues against the CMake build.

**Comment by steven-johnson** [comment]
I'm upgrading the buildbot setup to use the latest versions first.

**Comment by alexreinking** [comment]
Superceded by #4980

**Pull request closed without merging**
