### PR TITLE
Rework Generator make rules to avoid race conditions

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by kgnk** [comment]
Technically, the correct way to do this is with an intermediate phony target.
```
.INTERMEDIATE: generator-target-x86-64-osx
generator-target-x86-64-osx: $(GENERATOR_EXECUTABLE)
    $(GENERATOR_EXECUTABLE) x86-64-osx

$(GENERATED_X86_64_OSX_HEADERS) $(GENERATED_X86_64_OSX_OBJECTS) : generator-target-x86-64-osx
```

**Comment by steven-johnson** [comment]
Thanks for the tip, I didn't know about that. I'll push an updated fix.

**Comment by steven-johnson** [comment]
Actually, looking at this further, I don't think it addresses the issue. The problem here was that we had a rule like:

    foo.a foo.h: foo.generator
       foo.generator /*args to output foo.a and foo.h*/

where the rule produced both the .a and .h in the same call. As it turns out, this is decomposed by Make into (effectively) 

    foo.a: foo.generator
       foo.generator /*args to output foo.a and foo.h*/

    foo.a: foo.generator
       foo.generator /*args to output foo.a and foo.h*/

When running with multiple jobs, you can end up with both rules trying to create/update the .a file at the same time, producing invalid output; that's what this patch addresses.

IIUC, the .INTERMEDIATE target can produce more efficient builds by eliding the build of the generator if the final .a/.h files are up to date, but that's not the issue we were trying to fix.

**Comment by kgnk** [comment]
The problem I saw was calling the generator once for each output file. The generator in this case generates a dozen files. By using .INTERMEDIATE, the generator is only called once if any of the dozen files is missing or older than the generator. 

I did leave one line out of my example:
```
all: $(GENERATED_X86_64_OSX_HEADERS) $(GENERATED_X86_64_OSX_OBJECTS)
```

**Pull request merged**
