### PR TITLE
Enable warnings-as-errors by default on Windows builds

### PR DESCRIPTION
**Pull request by steven-johnson**
As of right now, the tree builds cleanly on Windows this way (pending buildbot verification): let's flip this switch to keep it that way.

### CODE REVIEW

**Comment by steven-johnson** [comment]
All clean. PTAL.

**Comment by dsharletg** [comment]
The warnings in HalideBuffer.h look legit/should maybe be fixed? https://buildbot.halide-lang.org/master/#/builders/26/builds/440

**Comment by steven-johnson** [comment]
Those all seem to be instances of this line:
        assert(sizes.size() <= std::numeric_limits<int>::max());
that pattern repeats many times in HalideBuffer.h, but only warns on Win32 builds.

**Comment by dsharletg** [comment]
Should we fix them though? It seems easy to fix these warnings, and the warning looks correct. I'm not sure why they *aren't* warnings on other platforms. It seems like maybe win32 is the only one that is catching these right now?

Basically, it would seem preferable to fix the warnings rather than disable the warning.

**Comment by steven-johnson** [comment]
> Basically, it would seem preferable to fix the warnings rather than disable the warning

I'm hesitant mainly because these are all basically comparing-int-to-size-t warnings, and there are hundreds (thousands?) of such comparisons in our code -- why we aren't getting even more warnings is a bit of a puzzle. But let me take a look.

**Comment by steven-johnson** [comment]
(And the equivalent gcc/clang warning --Wconversion is not enabled in any of our builds and is not part of -Wall, etc)

**Comment by steven-johnson** [comment]
Thinking more about it:
-- Disabling this warning on Win32 seems to get the MSVC warning situation closer to the gcc/clang situation (ie: conversion warnings not-enabled anywhere).
-- Resolving all of these conversions to allow enabling these warnings is (IMHO) a good long-term idea but one that is a nontrivial task in its own right.
-- That said, I'm puzzled as to why we aren't getting lots more of the int-vs-size_t warnings than we already are, so that probably needs to be figured out before making a decision.

**Comment by dsharletg** [comment]
If we're already disabling this warning on other platforms then it makes sense to just merge this for now and we can revisit this issue later (since it probably is a huge job to fix it).

**Pull request merged**
