### PR TITLE
Apply split should respect the order of substitutions/predicate/lets

### PR DESCRIPTION
**Pull request by psuriana**
Bug fixes for ApplySplit. It should respect the order of substitutions/predicates/lets since it is possible to have substitution-predicate-substitution in the case of split with GuardWithIf tail strategy.

### CODE REVIEW

**Comment by dsharletg** [comment]
Does this make #1619 obsolete?

**Comment by psuriana** [comment]
Yes, this is a fix for the out-of-bounds access errors described in #1619

**Comment by steven-johnson** [comment]
We should really add a test for this fix.

**Comment by steven-johnson** [comment]
I'd like to see a test added, but are we confident enough to go and land this as is?

**Comment by steven-johnson** [comment]
LGTM

**Pull request merged**
