### PR TITLE
Add a seed to correctness_async_copy

### PR DESCRIPTION
**Pull request by steven-johnson**
We are seeing a flaky failure on some systems; allowing reproducibility of the PRNG sequence may help track down the cause.

### CODE REVIEW

**Comment by abadams** [comment]
This actually makes it less deterministic, for the reasons we discussed offline. So I could see that this increases coverage, but it's not going to reduce flakiness.

**Comment by steven-johnson** [comment]
I don't expect it to reduce flakiness -- I just want to make it easier to repro a failure. (Unless you are saying that currently the random_int() sequence defaults to returning an identical sequence every time, in which case... nevermind I guess?)

**Comment by abadams** [comment]
It does, it returns the same sequence every time by default. It's a pure function of which number call to random_*() it was in the process and the pure vars of the Func that uses it.

Oblig: https://xkcd.com/221/

**Comment by steven-johnson** [comment]
Meh, ok then, withdrawing.

**Pull request closed without merging**
