### PR TITLE
Update CodeGen_PTX_Dev to use new PassManager

### PR DESCRIPTION
**Pull request by steven-johnson**
This was still using the LegacyPassManager for optimization, which will be going away at some point. (Code changes by @alinas; I'm just opening this PR on her behalf)

Fixes #[6710](https://github.com/halide/Halide/issues/6710)

### CODE REVIEW

**Comment by steven-johnson** [comment]
attn @[MaskRay](https://github.com/MaskRay)

**Review by abadams — APPROVED** [review]

**Comment by abadams** [comment]
@steven-johnson @alinas Do you recall the reason behind the change to CodeGen_LLVM in this PR? It doesn't seem related to PTX and it seems likely that it's the cause of the large performance regression mentioned in the issue.

**Comment by steven-johnson** [comment]
I will ping @alinas directly.

**Comment by LebedevRI** [comment]
I highly suspect that is depended on the LLVM version, it's not needed for fresh LLVM (14+ i would say),
but *is* needed for earlier ones: https://reviews.llvm.org/D113210

**Comment by alinas** [comment]
IIUC correctly, the regression is for this PR which is including both commits: switch to new pass manager and cleaning up adding the default AA pipeline. Assuming removing the default AA pipeline is the issue, Roman's change will fix this.
If it doesn't, we'll need a reproducer to understand why the switch to the new pass manager caused the regression.

**Pull request merged**
