### PR TITLE
Reduce JIT memory pressure in correctness_vector_math

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by zvookin** [comment]
Why isn't the solution here just to put scopes around each separate part of the test?

**Comment by steven-johnson** [comment]
> Why isn't the solution here just to put scopes around each separate part of the test?

I thought this was cleaner.

**Comment by zvookin** [comment]
Gotta disagree. Generally scoping things to their use is a standard way to control lifetimes in C++. I also think it should be the standard pattern for writing many separate tests in a single C++ function. Not just for resources, but to make sure one doesn't inadvertently reuse things from one test to another. Intentional reuse can be had by declaring common stuff at top-level scope at the start of the function.

(More structured test infrastructure would have each test in its own function with special support for setup and teardown, etc... That requires ... more stuff ... and maybe more lines per test. The braces are simple and a good compromise.)

**Comment by zvookin** [comment]
Oh and while I'm at it, a comment above each open brace saying what the test tests would be really nice too.

**Comment by steven-johnson** [comment]
I disagree substantially -- this PR fixes the issue with minimum of confusion and code delta -- but it's not a point worth arguing. I'll offer something else.

**Pull request closed without merging**
