### PR TITLE
Fix cxx_mangling_aottest for WITH_PTX case

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by abadams** [comment]
I thought the test flag was WITH_CUDA

**Comment by steven-johnson** [comment]
I don't see any instances of WITH_CUDA in the code, anywhere.

**Comment by abadams** [comment]
Ah, I was thinking TEST_CUDA.

TEST_CUDA is defined for the tests whenever Halide and llvm were both
compiled with cuda support (which is governed by WITH_PTX). I don't thing
WITH_PTX is necessarily defined for the tests.

**Comment by steven-johnson** [comment]
Yeah, WITH_PTX must be (incorrectly) defined for tests in the Bazel branch (where I saw it). If the code inside WITH_PTX is defunct we should just remove it rather than fix it.

**Comment by steven-johnson** [comment]
Yeah, looks like WITH_PTX is defined here in Bazel builds only because of a dumb hiccup in the BUILD file; we should probably just remove this clause since it shouldn't ever compile elsewhere.

**Comment by steven-johnson** [comment]
It's a dangling wart from https://github.com/halide/Halide/pull/1670 followed by a "fix" in 6605c1276cd3a7e3697318077904490304a5a3a8 -- sigh

**Pull request merged**
