### PR TITLE
Simpler simplified stmt

### PR DESCRIPTION
**Pull request by abadams**
This removes compile_to_simplified_lowered_stmt, and adds a much simpler Func::print_loop_nest, which dumps out pseudocode for the loop nest. E.g. here's bilateral grid:
```
compute blurz:
  parallel y:
    compute histogram:
      for c:
        for z:
          for y:
            for x:
              histogram(...) = ...
      for y:
        for x:
          for r.y:
            for r.x:
              unrolled c:
                histogram(...) = ...
    for x.x:
      vectorized x.v4 in [0, 3]:
        for z:
          unrolled c:
            blurz(...) = ...
compute blurx:
  parallel z:
    for y:
      for x.x:
        vectorized x.v5 in [0, 3]:
          unrolled c:
            blurx(...) = ...
compute blury:
  parallel z:
    for y:
      for x.x:
        vectorized x.v6 in [0, 3]:
          unrolled c:
            blury(...) = ...
compute bilateral_grid:
  parallel y:
    for x.x:
      vectorized x.v7 in [0, 3]:
        bilateral_grid(...) = ...
```

The purpose is to help people understand the loop nest that their schedule specifies. The scheduling tutorials have therefore been updated to use this feature.

### CODE REVIEW

**Comment by abadams** [comment]
@jrk: Does this look like the right thing?

**Comment by gchauras** [comment]
If bounds can be simplified to human readable constants, it will be useful to have them here. It is useful to see them to figure out if you bound computation is exploding because of your tiling, or if you are getting bound expansion in places. I agree that symbolic bounds like f.s0.extent are useless.

**Comment by gchauras** [comment]
Also from my experience in Fredo's class: 
People declare Var's global outside the scope of any Func definitions and reuse the same Var for each Func definition.

They have to eventually understand that Vars are owned by Func. People found that really confusing. Saying "func_name.s0.x" was not the best way of explaining this but omitting Func name completely might be more confusing. Printing 
```
compute A:
  loop x:
```
is ok, but it is easy to lose track if x.x in the above example belongs to histogram or blurz
```
  for x.x:
      vectorized x.v4 in [0, 3]:
        for z:
          unrolled c:
            blurz(...) = ...
```

**Comment by abadams** [comment]
I actually think that for non-trivial piplines symbolic bounds are somewhat useful, and magic constants are useless. "the width of the output + 5" is useful. "514" is not useful. That's why I always used compile_to_lowered_stmt instead of compile_to_simplified_lowered_stmt. I found that simplified_lowered_stmt actually obfuscated things for me. If I want to know what bounds inference is doing, I can turn on HL_TRACE=1.

But that argument is beside the point. In this PR I wanted to keep things strictly to the same information as specified in the schedule. People get so confused by scheduling at first that I wanted a simplification that explains that alone, and doesn't include bounds information at all.

**Comment by abadams** [comment]
I went back and forth on including the func and stage in the var name. Any other opinions?

**Pull request merged**
