### PR TITLE
Set estimates for training in Generator

### PR DESCRIPTION
**Pull request by steven-johnson**
Not sure if this is what you had in mind or not, but demonstrates putting all the values into estimates rather than command line. Includes fixes from https://github.com/halide/Halide/pull/3460 as well.

### CODE REVIEW

**Comment by abadams** [comment]
Change to script looks reasonable, but all those inputs and outputs  already have .bound directives. I just started trying to autotune that pipeline locally, and to get estimates I just made Dimension::set_bounds also call Dimension::set_bounds_estimates. It seems to me that if you have a concrete bound on something, that should act as an estimate too.

**Comment by steven-johnson** [comment]
> I just made Dimension::set_bounds also call Dimension::set_bounds_estimates

SGTM, and should arguably land in main as-is. 

But maybe a potential issue with order-of-call for existing code? (Though.... I guess if there are concrete bounds, those should always take precedence over estimates. Maybe issue a warning if both are specified and they don't match?)

**Comment by steven-johnson** [comment]
See: https://github.com/halide/Halide/pull/3462

**Comment by steven-johnson** [comment]
That's not what I found when I tried, but maybe I need to re-sync to the tip of this branch?

**Comment by abadams** [comment]
Possibly. There's an existing block of estimates set already in the if (auto_schedule) section of the schedule. The inputs should certainly not need estimates - bounds inference should work for those.

**Comment by steven-johnson** [comment]
Maybe, but I did this by dumb trial and error: I removed everything and re-added them until RunGen no longer complained about missing estimates.

**Comment by steven-johnson** [comment]
> I think the required estimates are already in the file now - I've been successfully using rungen on it.

If you're still using the bench_cost_model.sh that is checked in to this branch, ~all of the estimates are provided on the command line there.

**Comment by steven-johnson** [comment]
(Note that this includes fixes from https://github.com/halide/Halide/pull/3465)

**Pull request merged**
