### PR TITLE
Remove NaCl support

### PR DESCRIPTION
**Pull request by steven-johnson**
Remove all support for (P)NaCl code generation in Halide.

(Note that this also removes support for LLVM 3.6 and earlier; we
technically no longer supported these versions at all, but maintained
some build-and-test infrastructure to improve coverage for NaCl, since
the versions were similar in API.)

### CODE REVIEW

**Comment by dsharletg** [comment]
Do we still need the LLVM 3.2 bitcode writer at all after this?

**Comment by abadams** [comment]
Renderscript uses it

**Comment by dsharletg** [comment]
Also, LGTM

**Comment by abadams** [comment]
lgtm to me too. Will break all the pnacl buildbots of course. I'll delete them once this lands.

**Pull request merged**
