### PR TITLE
Add `halide_debug_assert()` macro (#6384)

### PR DESCRIPTION
**Pull request by steven-johnson**
Also convert usage of `halide_assert()`/`HALIDE_CHECK()` in hashmap.h and gpu_context_common.h to `halide_debug_assert()`, as all the usages looked to be appropriate for debug-mode only.

### CODE REVIEW

**Comment by zvookin** [comment]
Do we really need to litter the code long all caps names? We should use lots of asserts and checks and this approach is just horrible from a readability point of view. It draws massive attention to the *name* of the macro, which is just not at all interesting. It's like if every if statement was written "HEY_IM_AN_IF_STATEMENT_PAY_ATTENTION_TO_ME".

**Review by abadams — APPROVED** [review]

**Comment by steven-johnson** [comment]
> Do we really need to litter the code long all caps names? 

For HALIDE_CHECK I think that SCREAMING_SNAKE_CASE is appropriate because it really should jump out at you. For debug-assert, though, probably not. would `halide_debug_assert()` be a better choice?

**Comment by steven-johnson** [comment]
(This needs https://github.com/halide/Halide/pull/6382 to land first)

**Comment by steven-johnson** [comment]
Closing in favor of identical-but-rebased https://github.com/halide/Halide/pull/6390

**Pull request closed without merging**
