### PR TITLE
expr_match for Shuffles

### PR DESCRIPTION
**Pull request by vksnk**
This PR extends expr_match to also support Shuffle nodes.

### CODE REVIEW

**Comment by abadams** [comment]
No objection, but I would actually like to deprecate expr_match. It's mostly just the same as the IRMatcher patterns, but much much slower.

**Comment by vksnk** [comment]
That's good to know, I am using it similar to how it's used in HexagonOptimize.cpp, i.e. match some pattern to expression and if it matches, then replace it with the call which arguments are some subexpressions (with some optional preprocessing, for example, trying to narrow the arguments) of the original expression. I can't seem to find a direct replacement of the expr_match, which would let me to get matched subexpressions. Is there anything similar?

**Comment by abadams** [comment]
There's a minor extension I could make that would make it a direct replacement. I'll see if I can do it this afternoon.

**Comment by vksnk** [comment]
That's great, thank you!

**Comment by steven-johnson** [comment]
Is this PR defunct?

**Comment by vksnk** [comment]
I only need it in my local branch for some other work, so can keep it there for now. I'll close it.

**Pull request closed without merging**
