### PR TITLE
Clone of Generate Python extension modules #2975

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by matthiaskramm** [comment]
Looks like all the checks pass now?

**Comment by steven-johnson** [comment]
for Travis, yes, but for some reason the full buildbot suite hasn't run. Investigating...

**Comment by steven-johnson** [comment]
added missing return to PythonExtensionGen.cpp

**Comment by steven-johnson** [comment]
This is weird; the C++ generated on the arm32 bot is scrambled in a weird way that doesn't seem like it should be possible (nor obviously related to this change). Investigating.

**Pull request closed without merging**
