### PR TITLE
Convert autoscheduler weights to a single file

### PR DESCRIPTION
**Pull request by steven-johnson**
The main gist of this change is to put all of the weights used by the autoscheduler into a single file (instead of a directory of multiple files); the goal is to make saving 'overnight' tuned weights for a pipeline simpler, via having only a single `.weights` file rather than a directory of things.

There are various drive-by fixes, of course:
- The 'Weights' struct moved into its own file, and now manages its own loading/saving, in both the classic dir-of-files format, and new, single-file format. (The single-file format is very simpleminded but likely more than adequate; it has a trivial signature at the front so some smart upgrading over time should be easy to do.)
- DefaultCostModel.cpp got its own .h file, instead of being incestuously connected to the ABC it implements
- existing `weights` folder was deleted; the equivalent data is now in `baseline.weights`
- added the `weightsdir_to_weightsfile` utility for any downstream consumers that have custom weights in the 'old' format that they need to update to the 'new' format.
- Removed some unused code here and there.

Note that HL_WIEGHTS_DIR (and HL_WEIGHTS_OUT_DIR) are still used, but are 'smart' for now; if you pass a pathname that ends in `.weights` it loads as a single file, otherwise it assumes an old-style directory. (I didn't try to smarten the env var names because we really need to eradicate the use of env vars for this purpose anyway. but that's a job for another day.)

### CODE REVIEW

**Comment by steven-johnson** [comment]
(Issue #4121)

**Comment by steven-johnson** [comment]
(If there is a better -- existing -- format for combining the weights into one file, I'm all ears. Only one that springs to mind that supports multiple float32 images is MultiTIFF, which seems vastly too heavyweight for our needs here.)

**Comment by abadams** [comment]
Would be good to also include PipelineFeatures::version and ScheduleFeatures::version, and to warn on mismatch. If either the pipeline or schedule features get a version bump, the weights are invalid, but are probably still a good starting point for retraining in the number of features hasn't changed (hence warning but not error).

**Comment by steven-johnson** [comment]
> include PipelineFeatures::version and ScheduleFeatures::version

Done. Also reworked code to be more resilient to failures when reading weight files, and improved some deps in the makefile. PTAL.

**Comment by abadams** [comment]
Regarding nomenclature: compiled-in weights are reasonable to call baseline, because they can't be modified, but as a weights these are the trained x86 weights. Should we be calling them that? Or maybe baseline_x86?

**Comment by steven-johnson** [comment]
> baseline_x86

More likely `x86-64-avx2`, since I suspect that was used (it's the default in autotune_loop.sh)... which (btw) now that I look at it might be suboptimal, since I don't think that including the AVX2 feature also includes AVX and SSE41 implicitly...

**Comment by steven-johnson** [comment]
> compiled-in weights are reasonable to call baseline, because they can't be modified

FYI, the 'compiled-in-weights' were just an in-code copy of the old `weights` folder, which is now called `baseline.weights`, or possibly `baseline_x86-64-avx2.weights`, so....?

**Pull request merged**
