### PR TITLE
Matrix class

### PR DESCRIPTION
**Pull request by kree-colemcalughlin**
This pull request introduces a front end extension to halide for performing matrix and vector computations. The Matrix class wraps a halide function and views it as a matrix. For small dimensions (currently <= 4x4) the class uses a halide tuple instead and explicitly computes additional operations on the matrix, such as determinant, inverse, cofactor, etc... The Matrix class has its own scheduling operations that are different from Func. The basic idea of scheduling matrix computation is to specify the partitioning scheme on the matrix. The operators on matrices have fast schedules predifined so that you can mostly use matrices without having to worry about the scheduling.

NOTE: This is a work in progress, and there are known problems. I also do not guarantee that the Matrix API will not change in future versions.

This PR also introduces a standard place for defining extensions to halide. The Matrix class is compiled into its own header and lib files, and has its own testing suite. Comments are welcomed on how the extensions folder and build mechanism have been structured.

### CODE REVIEW

**Comment by kree-colemcalughlin** [comment]
Just added a fix to this PR. Previously writing expressions like this:
```
Matrix A, B, u, v;
Matrix C = 2 * A * u + B * v / 3;
```
was not possible with the class. Committed a change that fixed this, complex expression trees should be okay now.

**Comment by kree-colemcalughlin** [comment]
Gentle nudge on this PR. Any comments on the proposed build system for front-end extensions?

**Comment by abadams** [comment]
Sorry, I've been delaying looking at this closely because I'm worried I made a mistake with the extension folder proposal. Here's my concern:

On one hand, this is a lot of code, and some of it reaches into Halide and wraps built-in things like scheduling. Without a specific use of it I worry it'll rot pretty quickly. This is likely to be true of other extensions also. I don't want an extensions folder that becomes a graveyard for unsupported things that no longer compile.

On the other hand, having a repository of examples of neat things you can do to extend Halide could be a real resource for people.

Thoughts, @zvookin, @steven-johnson, @dsharletg?

**Comment by kree-colemcalughlin** [comment]
That is a fair point, and it is worth discussing what is the correct solution. There are a couple issues that I feel like the extensions folder is addressing, which I think are important.

First of all it provides a first step towards modularity. Breaking things down into chunks, which could potentially be in different states of completeness, could actually help with code maintenance. In this case I am proposing a front-end extension, but we have also been discussing standard library like components, and I could forsee a future where we want to modularize the codegen backends. Whether or not the proposed extensions folder is the correct way to do this is totally worth discussing.

One of the big advantages this gives us is the ability to make clear the state of each module. With the matrix_class branch, I'd say the extension is in an alpha, or experimental, state, but it is hard to push the development forward without feedback on the api design, bug reports, etc... So being able to commit different parts of Halide in different states of development and allow people to start tinkering with them is useful.

To address the concerns about code rot, I think this comes down to a code maintenance issue. If we just start throwing everything in extensions willy-nillly, this could certainly be a problem. If we maintain a decent code review process and only commit extensions that will be actively developed and we believe to be useful, then this may be less of a problem.

In our previous discussions on this we compared the extensions folder to Eigen's unsupported folder, but maybe that is not the best comparison. Maybe rather than thinking of it as a dumping ground for unsupported code, we should think of it as the first step to modularizing the Halide codebase.

**Comment by dsharletg** [comment]
Sorry for dragging my feet in replying, I'm struggling to form an opinion on this, I'm probably letting perfect be the enemy of good and end up not completing any of my thoughts. This is also the reason I'm dragging my feet on updating the FuncT/typed funcs PR: I'm not sure what to do.

My current thinking is that this (and FuncT/typed funcs, and other similar features) is that they should exist as part of an example in apps, but no more than that. I think the expectation for code at that level is that its something you might copy/paste out of the example into your own app and use it/modify it at will, but I think part of that expectation is that only the functionality exercised in the example would work, and using it in any other way or modifying it makes it "your (the user's) code".

Maybe this is a trivial difference, but the reason I like this is that I feel like the level of support expected by users is different for this vs. an 'extensions' folder. As a user, if I come across something like FuncT or this matrix class in an example, my only expectation is that the code that uses it in the example will work. I would expect anything else to either not exist or might be broken (but it's probably better for it to be non-existent than broken). This is especially important for FuncT, because there are some corner cases of operator overload resolution that are difficult with it.

I also like this because we *do* test the apps, and if we keep the scope of this "extension" code to examples, then it shouldn't be too hard to maintain it as it breaks as Halide evolves.

Sorry to push for yet another code reorg (if others agree with this) :)

**Comment by dsharletg** [comment]
This is really old, going to close it, reopen if we want to reconsider.

**Pull request closed without merging**
