### PR TITLE
Testing issue #2371

### PR DESCRIPTION
**Pull request by SanderVocke**
This PR is only to see if the issue I encountered in #2371 can be reproduced on Halide's buildbots.

### CODE REVIEW

**Comment by SanderVocke** [comment]
Looks like this was a silly idea, as there is no llvm 5.0 build bot.

**Comment by abadams** [comment]
There is, but the buildbots by default only test PRs originating from inside the repo. I'm going to reopen this and use it for testing mechanisms for us to trigger buildbot runs on external PRs.

**Comment by abadams** [comment]
I have assigned halidebuildbots as a reviewer. I'll try to configure the buildbots to notice this and do a full run.

**Comment by SanderVocke** [comment]
Thanks Adam. Would the build results also show up here, or only be reported to you internally?

**Comment by abadams** [comment]
They would show up here if I could get the damn thing working.

**Comment by steven-johnson** [comment]
Is this still an issue, or can it be closed?

**Comment by abadams** [comment]
I failed to get it working, and no longer have time to try. I guess I'll close it.

**Pull request closed without merging**
