### PR TITLE
Fix android samples for nexus 5x

### PR DESCRIPTION
**Pull request by abadams**
It has a rotated image sensor

### CODE REVIEW

**Comment by jiawen** [comment]
Looks sane.

YuvBufferT::rotate180: instead of rotating in place, how about returning a new YuvBufferT?

Nits:

Android sensor orientations are exactly 0, 90, 180, or 270. Since you're only handling the rotated 180 degrees case, change ">= 180" to "== 180".

Also rename the functions:

rotate_buffer_t --> rotate_buffer_t_180
rotateNativeYuvBufferT --> rotateNativeYuvBufferT180

**Comment by abadams** [comment]
I was getting a value for 270 for the rotation. Go figure. I figured I'd just map 0 and 90 to not rotated, and 180 and 270 to rotated.

I'll rename those functions. I think I'll leave the rotate operation as in-place, because if it returned a new buffer it'd be an alias for the same memory as the original buffer, which might be confusing and/or introduce lifetime issues.

**Comment by jiawen** [comment]
Yeesh, orientation is complicated: http://developer.android.com/guide/topics/manifest/activity-element.html#screen

We set the app to "landscape", which usually means orientation = 90. I think we can avoid the rotate_180 on the Nexus 5X by forcing the activity to have "reverseLandscape" orientation.

**Comment by steven-johnson** [comment]
More info here:

https://code.google.com/p/android/issues/detail?id=191210

“Because of manufacturing reasons, we needed to mount the Nexus 5X main sensor in the less-common (reverse landscape) orientation – the wires from the sensor chip wouldn’t have fit otherwise. Unfortunately, our old camera API (which is deprecated, but most apps still use it) isn’t terribly user-friendly, and requires application developers to explicitly set the preview rotation. On most devices, though, it turns out the default rotation is correct for a forced-landscape app, so many apps never call the display orientation method.”

Sounds like we should be able to fix this just by tweaking the Android Java code and skip the explicit rotation stuff.

**Comment by abadams** [comment]
I tried a few java api calls to no effect other than slowing down the viewfinder. I'll check with etalvala to see what I'm supposed to do.

**Comment by abadams** [comment]
Turns out jiawen already checked with the Android folks and there's no good answer right now for this particular data flow. I'll merge this as-is.

**Pull request merged**
