### PR TITLE
Don't create unnecessary lets in Inlining

### PR DESCRIPTION
**Pull request by abadams**
Possible alternative to #3635

### CODE REVIEW

**Comment by abadams** [comment]
@steven-johnson try patching this in and running one of the failing pipelines. For most inlining cases, I believe this is all CSE was doing.

**Comment by steven-johnson** [comment]
Nope: patching this in (and leaving the inliner at >1 instead of the earlier >0) is still timing out.

**Comment by steven-johnson** [comment]
Is this still necessary/desirable?

**Comment by abadams** [comment]
It's still a good change

**Comment by steven-johnson** [comment]
Synced to master to tickle buildbots

**Pull request merged**
