### PR TITLE
Two (possibly related) autoscheduler bugs.

### PR DESCRIPTION
**Pull request by SanderVocke**
Code to reproduce bugs for issue #2431.

Found 2 bugs in the autoscheduler. I think I have a rough idea of the root cause, but don't know how to approach it to get to a solution.

**Note that the Travis CI builds will not fail, because it does not trigger the autoscheduler tests.**

This PR just exposes the bug(s) in test cases for the autoscheduler:

1. In test/auto_schedule/unbounded_nonpure.cpp, made a test that lets a sum (non-pure reduction) be consumed by a non-extern Func. The consumption is written such that the autoscheduler cannot determine the sum's bounds. The following internal error results:

> Internal error at /home/sander/dev/Halide/Halide/src/RegionCosts.cpp:416 triggered by user code at /home/sander/dev/Halide/Halide/test/auto_schedule/unbounded_nonpure.cpp:36:
Condition failed: get_element(env, f.first).is_pure()

My analysis of this: 
It seems from the autoscheduler implementation that "any unbounded function will be inlined". This usually makes sense. However, in this case, the unbounded function has update steps, so it is not inlineable. 
Indeed, I confirmed that the sum function is added to the "inlining list" by the autoscheduler. The assertion that fails happens just before the actual inlining is about to happen; there there is a check that the function should be pure.
So it seems there should be some special behavior added for this situation: what if we have an unbounded function, but we cannot inline it? Maybe it could be set to compute_at() at the innermost level of each possible consumer (if necessary using wrappers) or something - that's the closest to inlining we can get.

2.  In test/auto_schedule/extern.cpp, added a test case where a sum function (reduction domain, non-pure) is consumed by an extern function. This is a very similar situation as the 1st bug: a non-pure function is consumed by an extern func, therefore it's unbounded at compile-time. I would expect the exact same failure, but apparently this is a bit different, as the autoscheduler fails trying to find a tile size for it.

> Internal error at /home/sander/dev/Halide/Halide/src/AutoSchedule.cpp:1773 triggered by user code at /home/sander/dev/Halide/Halide/test/auto_schedule/extern.cpp:138:
Condition failed: extent.defined()

I have a feeling that a single solution for scheduling unbounded, non-pure functions should be able to fix both of these bugs. But I don't think I am in the best position to suggest a fix.

### CODE REVIEW

**Comment by SanderVocke** [comment]
An alternative solution would be to make it possible to inline non-pure functions. That would require a mechanism to construct a single expression which combines all update steps of a particular function for any coordinate set.

**Comment by steven-johnson** [comment]
What the status on this PR?

**Comment by psuriana** [comment]
I am working on it

**Comment by psuriana** [comment]
Fixed in #2679

**Pull request closed without merging**
