### PR TITLE
Backport #6375

### PR DESCRIPTION
**Pull request by abadams**

### CODE REVIEW

**Comment by steven-johnson** [comment]
(waiting for merge conflicts to be resolved before reviewing)

**Comment by alexreinking** [comment]
Looks like you need to rebase backports onto release?

**Comment by abadams** [comment]
I'm not sure I did this correctly, because I also see all the commits from the previous point release (which is also what's causing the conflict). I'll wait to hear from Alex.

**Comment by steven-johnson** [comment]
LGTM pending green

**Review by alexreinking — APPROVED** [review]

**Pull request merged**
