### PR TITLE
Work around LLVM breakage

### PR DESCRIPTION
**Pull request by steven-johnson**
Report: "LLVM removed some intrinsics in order for them to be lowered to LLVM IR instead (which seems to natively support it now)"

### CODE REVIEW

**Comment by abadams** [comment]
I'm not particularly confident that they'll catch averaging in all the same cases that we do. I guess we'll see what simd_op_check says. If our pattern turns out to be more general, we may need to have it map to something in runtime/x86.ll that implements the intrinsic using precisely the pattern that LLVM expects for it.

**Comment by steven-johnson** [comment]
At the moment, simd_op_check passes. But yeah, this may need more attention. This is mostly a band-aid to unbreak us with trunk.

**Comment by steven-johnson** [comment]
Update: simd_op_check passed on OSX but is failing on Linux buildbot. Investigating.

**Comment by steven-johnson** [comment]
I can't get the simd_op_check to fail on my local Linux box. Restarted the buildbot to see if it's intermittent.

**Comment by abadams** [comment]
That test should not be flaky. You may need to try different combinations of target (x86-64, x86-64-sse41, x86-64-avx, etc)

**Comment by steven-johnson** [comment]
Ah, yep, that's it: HL_TARGET=x86-64-linux (disabling AVX, etc) repeats it.

Might be worth (temporarily) disabling the pavgX test targets for LLVM >= 60 to get the buildbots unstuck.

**Comment by steven-johnson** [comment]
Actual fix (rather than band-aid) pushed.

**Comment by abadams** [comment]
lgtm

**Comment by abadams** [comment]
This has passed the relevant tests on the trunk builder, so I'm going to merge it to try to unbreak the build for other PRs

**Pull request merged**
