### PR TITLE
Demo of a desktop app using OpenGL with AOT filter compilation

### PR DESCRIPTION
**Pull request by ronen**
Demo of a desktop app using OpenGL with AOT filter compilation, showing a few use cases side-by-side:

* Sample filter AOT compiled to opengl target, run with data being sent to & from the host.

* Same filter, run with data already in GPU textures.

* Same filter, compiled to run entirely on the host.

Built and tested on OS X.

Shout out to @shoaibkamil who collaborated on this

### CODE REVIEW

**Comment by shoaibkamil** [comment]
PTAL.  This probably needs some changes to Makefiles etc, so please let us know what we should change.  The app does require `glfw3` and `libpng` (along with OpenGL, of course).

**Comment by abadams** [comment]
This is great, thanks. Here's what I had to do to the Makefile to get it to work on OS X:
https://gist.github.com/abadams/80e1bc7922f1c6ee7b92143c7a683904

Ignore the /opt/local/include bit, that was me messing about with macports.

If it's inside the Halide repo, paths should just be relative to the Halide repo rather than an installation. The other apps use apps/support/Makefile.inc, which might simplify things. Haven't tested on linux yet.

**Comment by ronen** [comment]
> If it's inside the Halide repo, paths should just be relative to the Halide repo rather than an installation.

Makes sense.  I'll update the Makefile and push it into the PR.  Do you want me to collapse the commits?

**Comment by abadams** [comment]
No, it's not necessary to collapse the commits.

**Comment by abadams** [comment]
This really really doesn't want to work on linux. I was hoping it would be a simple change. Oh well. Maybe change the readme to explicitly say it's an OS X app?

**Comment by shoaibkamil** [comment]
[Here's a patch](https://gist.github.com/anonymous/ead7f1ac306f720d8abe8cb06334fb28) to get this to work on Ubuntu 16.04; I did have to manually install libdrawtext.

**Comment by ronen** [comment]
I've applied @shoaibkamil's patch.

**Comment by abadams** [comment]
Still didn't work for me on something like Ubuntu 14.04, but much closer. Here's a patch that got it working completely for me: 

https://gist.github.com/abadams/7f0a2c0bc4811a9ca3191e42057a6a02

Perhaps it still works for Shaoib?

**Comment by shoaibkamil** [comment]
I can confirm @abadams's patch continues to work on my Ubuntu 16.04 machine.

**Comment by ronen** [comment]
I've applied @abadams's patch.  And confirmed that it still works on OS X

**Pull request merged**
