### PR TITLE
Make type_info not depend on addresses of template instantiations

### PR DESCRIPTION
**Pull request by abadams**
trunk clang was refusing to compile libHalide with the current setup.
This PR makes the implementation much dumber, and hence more resilient
to template weirdness. Compile times seem unaffected. It's an indirect
call through the vtable either way to get the type info.

### CODE REVIEW

**Comment by steven-johnson** [comment]
+1 to using this approach rather than requiring RTTI.

I have one concern: this is fragile if the code gets reformatted.

A more robust approach might be to something like

    template<> uintptr_t ExprNode<Mod>::static_type_info() { static const uint8_t t = 0; return (uintptr_t)&t;}

**Comment by abadams** [comment]
Fragile? How so?

The type ids in the PR change if that source file is modified and then
recompiled. Using the address of a static also changes if Halide is
modified and recompiled, and may also change every run.

Two type ids could be the same if someone puts them on the same line, but
that reformatting seems extremely unlikely.

I was tempted to just have them return 0, return 1, return 2. But that
makes it a pain to add new IR nodes in the middle.

**Comment by steven-johnson** [comment]
> Two type ids could be the same if someone puts them on the same line

That's precisely what I was concerned about. It's unlikely but possible, whereas the address-based approach isn't. Correctness that depends on code formatting makes me nervous.

(Both approaches can vary between different compiles, of course, which is fine for our purposes.)

**Comment by abadams** [comment]
I appreciate your aversion to macros, but I don't think anyone would be
that silly.

The address-based approach is roughly equivalent to the old design - return
the address of a static object associated with the template instantiation.
It seems bulletproof, but so did the old design. It makes me think hard
about the uniqueness of a static method of a template instantiation, and
needing readers to think that hard seems unnecessary in this case.

**Comment by abadams** [comment]
Caused large compile time regressions :( 

Will find a better fix.

**Pull request merged**
