### PR TITLE
Tweak schedule for camera_pipe, ~4% improvement in hexagon cycles

### PR DESCRIPTION
**Pull request by ronlieb**
Small improvement in camera_pipe performance.
should the  strip_size only be set for the hexagon_target?

### CODE REVIEW

**Comment by dsharletg** [comment]
The tradeoff is that the larger strip_size is, there is less redundant compute, but also less parallelism. For Hexagon, that's fine, it only needs 2 or 4 tasks of equal size. However, on other devices, like a 4+4 big/little CPU, more parallelism helps. 128 is less than 2 tasks per core on an 8 thread machine, so it's probably too big.

Another option for Hexagon is to do this:

    Expr strip_size = output_buffer.dim(1).extent() / 4;

If the output height is divisible by 4, then this will use exactly 4 tasks of the same size. If you only care about HVX 128, you could divide by 2 also. How about this:

    Expr strip_size;
    if (get_target.has_feature(Target::HVX_128)) {
        strip_size = output_buffer.dim(1).extent() / 2;
    } else if (get_target.has_feature(Target::HVX_64)) {
        strip_size = output_buffer.dim(1).extent() / 4;
    } else {
        strip_size = 32;
    }

**Comment by ronlieb** [comment]
I tried the suggested approach of output_buffer ... but it actually degrades performance for both 64b, and 128b modes.

I tweaked the original patch to use 64 and 128 respectively for 64B and 128B modes.

**Comment by dsharletg** [comment]
I looked at it the generated code. The problem is that Halide doesn't know that strip_size is even, so it causes some simplifications to stop working. The fix to tell Halide that the strip_size is even:

    Expr strip_size;
    if (get_target.has_feature(Target::HVX_128)) {
        strip_size = output_buffer.dim(1).extent() / 2;
    } else if (get_target.has_feature(Target::HVX_64)) {
        strip_size = output_buffer.dim(1).extent() / 4;
    } else {
        strip_size = 32;
    }
    strip_size = (strip_size / 2) * 2;

And then make sure that the strip split is using TailStrategy::RoundUp

I see these performance numbers:

master: 10.23e6
strip size 128:  9.9e6
strip size height / 4: 9.58e6

**Comment by ronlieb** [comment]
LGTY?

**Comment by dsharletg** [comment]
I think we should add a comment prior to the if explaining why the strip size is what it is: with HVX 128, we need 2 threads to saturate HVX with work, HVX 64 we need 4 threads, and on other devices, we might need many threads.

**Comment by ronlieb** [comment]
shamelessly stolen comments.

**Pull request merged**
