### PR TITLE
Add Generator-based version of Wavelet app

### PR DESCRIPTION
**Pull request by steven-johnson**
wavelet_gen is a simple port of apps/wavelet, but with all Halide code
in Generator form; it exists to show a simple example of using AOT
Generators with an app (and in particular, how Make and CMake files can
be constructed).

### CODE REVIEW

**Comment by steven-johnson** [comment]
(I intend to use this as a place to experiment with some alternate build systems; e.g., Bazel.)

**Comment by abadams** [comment]
How about just replacing the existing wavelet app with this?

The other thing the existing app does though is demonstrate noruntime. Is
that a bad idea for your use-cases?

**Comment by steven-johnson** [comment]
Re: replacing wavelet app, happy to do so; I left it in place as a way to have a reference for doing stuff both ways. Happy to just replace it if you'd prefer.

Re: no-runtime, I overlooked that. Will fix.

**Comment by steven-johnson** [comment]
Re: the no-runtime flag... one concern I have is that I thought it would be good to keep this example as simple as possible (ie, what's the simplest Generator-AOT usage for each build system); adding the no-runtime flag adds an unrelated wrinkle. I can still add it if you think this is the right place for it, but I'm concerned that might mean future cargo-culting of the example resulting in the assumption you need to use the no-runtime flag everywhere...

**Comment by steven-johnson** [comment]
Edit: we actually also test the no-runtime flag in the main Makefile, for test/generator/nested_externs_*

**Comment by abadams** [comment]
I thought it was nice to have a minimal app example of it, because the
details of how nested externs builds is buried in the top-level makefile.

It may be good practice to use noruntime when building an app that uses
many aot Halide filters, in which case cargo-culting this app would be a
good thing. On windows weak linkage doesn't exist, afaik, and our current
solution is to tell the linker to ignore duplicate symbol errors. noruntime
is probably better.

On the other hand, it is marginally less simple than including the runtime
in each object file for this trivial app. Maybe we should use
apps/linear_algebra for the noruntime example - it uses very many
generators, and noruntime might actually speed up compilation.

Which do think is better?

**Comment by steven-johnson** [comment]
I vote for retrofitting linear_algebra for that; that keeps the simple example simple, and allows us to demonstrate the noruntime use in a situation where it's genuinely useful.

**Comment by steven-johnson** [comment]
linear_algebra retrofitted in PR#867; I'll update this PR to simply replace wavelet entirely.

**Comment by steven-johnson** [comment]
Updated to replace existing wavelet app; added a bit more explanation in the CMake file. PTAL

**Comment by abadams** [comment]
My only comment is the the readme is a little vague. Does "direct compilation steps" mean an int main() with explicit calls to compile_to_file like in the local laplacian app?

**Comment by steven-johnson** [comment]
Clarified.

**Comment by abadams** [comment]
Bah, sorry, clicked merge before your comment appeared. Feel free to fix it in master.

**Comment by steven-johnson** [comment]
Looks like it made it in!

**Comment by delcypher** [comment]
@steven-johnson Sorry there was a typo in my previous comment, fixed now.

**Pull request merged**
