### PR TITLE
Fix a missing case in clamp_unsafe_accesses

### PR DESCRIPTION
**Pull request by abadams**

### CODE REVIEW

**Review by alexreinking — APPROVED** [review]
Thanks for the fix!

**Comment by alexreinking** [comment]
Looks like the crash must be happening here:

``` 
 ​            ​auto​ bounds = func_bounds.​at​({call->​name​, call->​value_index​});
```

Is there some reason an input image would not be included in the FuncValueBounds results?

**Comment by abadams** [comment]
Yeah, we don't know the value bounds of input images. I pushed something that better reflects what I was trying to do.

**Comment by alexreinking** [comment]
Great, yeah, that looks better

**Pull request merged**
