### PR TITLE
delete rewrite rule that is incorrect under new div by zero definition

### PR DESCRIPTION
**Pull request by jn80842**
After the change to the semantics of division, this rewrite rule is incorrect when y = 0. Deleting this rule should fix issue #4638.

### CODE REVIEW

**Comment by dsharletg** [comment]
It looks like the failures in the travis check are real simplification failures:

Input: (-1/((x*2) + 1))
Output: (-1/((x*2) + 1))
Expected output: select((x < 0), 1, -1)

**Comment by abadams** [comment]
The travis check hints at a precondition that could save this rule: If ExprInfo struct tells us y could not possibly be zero, the rule is fine. This is already captured in the bool "denominator_non_zero", we can probably just add that to the precondition.

**Comment by steven-johnson** [comment]
We should add the breakage from #4638 to a test somewhere, to ensure it stays fxed.

**Comment by steven-johnson** [comment]
Clone is clean except for the known arm32 failures. LGTM.

**Pull request merged**
