### PR TITLE
Insert apparently-missing `break;` in IREquality.cpp

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by steven-johnson** [comment]
Maybe time to enable `-Wimplicit-fallthrough`

**Review by abadams — APPROVED** [review]
yikes

**Comment by steven-johnson** [comment]
> Funnily enough, this could not have caused a problem other than making a redundant check, which is why no tests failed, but that's only because GE has the same layout as GT.
> 
> Looks like there's another problem in runtime/webgpu.cpp

I did a clean CMake build and didn't get any warning there. Or did you find this by inspection?

**Comment by steven-johnson** [comment]
> I added the flag to the makefile build. Did adding the flag to cmake also cover the runtime?

Nope, fixing now

**Comment by steven-johnson** [comment]
Please push your makefile fixes to this branch too

**Pull request merged**
