### PR TITLE
cuda matrix multiply fixes

### PR DESCRIPTION
**Pull request by abadams**
Matrix multiply in cuda was nearly *two orders of magnitude* slower than it should be.

There were two problems:

- llvm stopped promoting small arrays to registers in the ptx backend. The ptx was full of pointless stores to local memory. Added a pass to do this promotion manually by sharding into scalar alloca nodes. This gave a 5x perf boost.

- The nvidia driver needs some magic variables tuned to set register counts. There's no one perfect value for every kernel. For mat_mul, it needs to be much larger than the default. This gave a 10x perf boost. This parameter should be in the schedule, but it's a per-module setting, so we'd have to refactor how we pass ptx kernels to the driver. For now this PR hacks it in as an environment var to enable further testing.

With these changes, mat mul is back to with 2x of cublas. Added an app that does this benchmark to track progress.

### CODE REVIEW

**Comment by zvookin** [comment]
I filed an LLVM bug requesting control of .maxnregs on a per entry basis:
    https://llvm.org/bugs/show_bug.cgi?id=31321
and an issue to track adding some sort of ptx_tune scheduling directive:
    https://github.com/halide/Halide/issues/1671

**Comment by jlebar** [comment]
Hi, llvm cuda/ptx developer here.

> llvm stopped promoting small arrays to registers in the ptx backend.

This sounds like a serious regression in SROA and/or the ptx backend that would be worthwhile to understand better and/or fix in llvm itself.  Can you file a bug on this?

> I filed an LLVM bug requesting control of .maxnregs on a per entry basis:

Thanks for that bug; I agree we should let you specify this from llvm.  It seems it should be pretty straightforward.  I will see if I can spin a patch in the next few days.

**Comment by abadams** [comment]
Will do. I saw that the LLVM codegen tests for this only check scalar
allocas, so I figured this wasn't explicitly supported behavior. Perhaps
there's something non-trivial about our allocas that's breaking things.

**Comment by abadams** [comment]
https://llvm.org/bugs/show_bug.cgi?id=31333

**Comment by abadams** [comment]
I think our PTX pass setup was totally wrong. See #1675

**Comment by jlebar** [comment]
.maxnreg support landed in LLVM r289729.

**Comment by abadams** [comment]
Awesome, thanks. We think we've figured out how to expose this in the
schedule:

func.cuda_tune(some_enum, some_value);

**Pull request merged**
