### PR TITLE
include HalideGenerator.cmake needed by various apps

### PR DESCRIPTION
**Pull request by ibtaylor**
I had to add this in order to get apps to build.

I can see this possibly being included by each individual app instead. Thoughts?

### CODE REVIEW

**Comment by zvookin** [comment]
LGTM.

**Comment by steven-johnson** [comment]
No objection, but I'm puzzled as to why this is needed for your build -- our buildbots have been succeeding at this for a while without it. What target(s) are you building?

**Comment by ibtaylor** [comment]
Maybe the build bots aren't compiling with `WITH_APPS=ON`?

**Comment by ibtaylor** [comment]
Hah, actually it seems like it is fine when building `WITH_TESTS=ON` which seems accidental.
https://github.com/halide/Halide/search?utf8=%E2%9C%93&q=HalideGenerator&type=

**Comment by steven-johnson** [comment]
OK, just waiting for the buildbots to be clean

**Comment by ibtaylor** [comment]
Unsure if the includes can be scoped so this sort of thing is less likely to occur in the future.

**Pull request merged**
