### PR TITLE
Splitting RVars and update definitions by non-factors using predication

### PR DESCRIPTION
**Pull request by abadams**
Splitting a pure Var in an update definition no longer rounds up the extent (this is a change to existing behavior), and you can now split RVars by factors which do not divide the extent (this was previously an error). 

This branch injects an if statement in the loop to guard against going beyond the end, and then uses "likely" to make is so that if statement only appears in an epilogue case. So splitting an RVar by a factor of 8 gives you code something like this:

    for outer from 0 to (extent+7)/8*8: // rounds up
      for inner from 0 to 8:
        if likely(outer*8 + inner < extent):
          do stuff

After loop partitioning, this turns into:

    for outer from 0 to extent/8: // rounds down
      for inner from 0 to 8:
        do stuff
    if extent % 8 > 0: // epilogue for loop over outer. It has at most one iteration, so it has become an if
      for inner from 0 to 8:
        if inner < extent % 8: // predication still exists in epilogue case. Condition has been simplified.
          do stuff

That final for loop for inner should really just have its extent truncated to extent % 8 if it hasn't been vectorized, or otherwise messed with, but I'll leave that until I get back to the trim_no_ops branch, which would handle this case nicely. Note that if there are other reasons for an epilogue (like a boundary condition), then because this uses "likely" it shares the same epilogue. It doesn't make yet another one.

Unrolling an RVar by a factor of 8 gives you code like this (after some simplifications):

    for outer from 0 to extent/8: // rounds down
      do stuff for inner = 0
      do stuff for inner = 1
      ...
    if extent % 8 > 0:
      do stuff for inner = 0
      if extent % 8 > 1:
        do stuff for inner = 1
        if extent % 8 > 2:
          do stuff for inner = 2
          if extent % 8 > 3:
            ...

The PR includes a bunch of new simplifier rules that improve the sorts of patterns that appear in the generated code, but these are not necessary for the logic to work.

The PR also includes code that helps bounds inference understand that the if statement bounds the range of the variable in question for the purposes of the body of the if statement. This doesn't affect computation bounds inference, which works using the original Func definition. It exists so that the memory-access bounds checks at the top of the pipeline understand that the predicated loop body doesn't read out to the to the rounded-up extent.

### CODE REVIEW

**Comment by abadams** [comment]
btw, it's easy to back the change off to only addressing the case that was previously an error, in which case the impact on existing code should be zero. This seemed better than rounding up though for update definitions.

**Comment by abadams** [comment]
fyi, this branch is currently failing some gpu tests locally, so do not merge yet

**Comment by abadams** [comment]
Fixed.

**Comment by abadams** [comment]
Looking at that if statement with @zvookin, we're inclined to make the strategy for dealing with the tail (round up, round up and predicate, shift inwards, or maybe assert that it's already a multiple) an optional final argument to split. The default case would be the same as the current behavior. @jrk @dsharletg @steven-johnson  thoughts?

**Comment by steven-johnson** [comment]
I don't understand why the optional variation is necessary. What is the use case for them?

**Comment by abadams** [comment]
There are a few places where we could expose meaningful options.

For pure vars in pure stages you can shift the last split inwards (our current behavior), which avoids reading out of bounds on inputs or writing out of bounds on outputs, but you actually get shorter and maybe faster code if you just round up, and that's often fine to do.

For splitting pure vars in update stages it's not correct to recompute, so you have the choice of rounding up (master), which might read out of bounds, or throwing an if statement in that last split (this branch), which is more complex code, but doesn't expand any bounds.

For splitting RVars in update stages you can either try to prove that the factor divides the extent (master), or you can just throw an if statement in there (this branch), or you could inject a runtime assertion that the factor divides the extent.

Using heuristics to make these choices seems against the spirit of Halide, with its explicit control over scheduling.

**Comment by dsharletg** [comment]
I think it's a good idea. I have wanted to just pad an internal realization so it executes full vectors worth in the past. I assume that's what the 'round up' option would do. To clarify, downstream bounds inference would still use the un-padded dimensions, or no? I assume the bounds of producers that the reduction consumes would be padded out though. Or will we just read out of bounds (maybe not a problem)?

**Comment by steven-johnson** [comment]
OK, makes sense, and agreed that explicit is better than heuristics. That said, this was non-obvious to me; adding some explicit examples to the docs for when each behavior is useful would probably be a really good idea.

**Comment by abadams** [comment]
If you round up, downstream computation bounds inference shouldn't be affected - that's based on what values are actually needed by the rest of the algorithm, not what values are going to be computed (*). Allocation bounds inference might need to increase some buffer sizes to handle the new loads.

(*) Unless the earlier Func is compute_at somewhere inside the consumer's loop nest. In that case it's very hard to figure out what values the consumer is responsible for computing correctly in this particular loop iteration, and instead we just assume all of the values that the consumer computes need to be correct.

**Comment by abadams** [comment]
Made it an option on split and similar scheduling calls. PTAL

**Comment by abadams** [comment]
@dsharletg @zvookin bump. Now it's an explicit option.

**Comment by dsharletg** [comment]
This looks good to me. We should note somewhere in the next release that we've removed the cuda* scheduling variants in favor of the gpu* equivalents.

**Pull request merged**
