### PR TITLE
Add types to left-shift and right-shift assertions

### PR DESCRIPTION
**Pull request by steven-johnson**
This makes debugging violations a bit easier.

### CODE REVIEW

**Comment by zvookin** [comment]
Please do not mix the types with the expression print in a way that looks like the types might have come from the expression itself. (Long discussion, but this PR exists because Expr printing is somewhat ambiguous to read. If you wanted to make it unambiguous, the way would be to wrap the Expr in a cast before printing, but then that is confusing because it looks like the cast was part of the IR originally, not inserted by the error message.) I'd suggest putting the type info on another line or using English text like "... where the arguments have type <x type> and <y type>".

**Comment by steven-johnson** [comment]
Moved the types to a separate line per your request.

Also fixed a mistake in operator>>, which should have passed the unsigned RHS rather than the original RHS. (operator<< was already correct.) This is arguably a separate issue worthy of its own PR, but in the interest of expedience, including it here.

**Comment by steven-johnson** [comment]
Looks like this is inducing OpenCL failures, e.g.

CUSTOMBUILD : error : CL: clBuildProgram failed: CL_BUILD_PROGRAM_FAILURE [C:\build_bot\worker\win-64-testbranch-800\halide-build-Release\test\run_correctness_boundary_conditions.vcxproj]
  Build Log:
<kernel>(100,24): error GF2BD9111: can't convert between vector values of different size ('int16' and 'uint16') [C:\build_bot\worker\win-64-testbranch-800\halide-build-Release\test\run_correctness_boundary_conditions.vcxproj]
     int16 _6824 = _6821 >> _6823;
                   ~~~~~ ^  ~~~~~
<kernel>(161,23): error GF2BD9111: can't convert between vector values of different size ('int16' and 'uint16') [C:\build_bot\worker\win-64-testbranch-800\halide-build-Release\test\run_correctness_boundary_conditions.vcxproj]
    int16 _6887 = _6884 >> _6886;
                  ~~~~~ ^  ~~~~~

**Comment by dsharletg** [comment]
The OpenCL backend probably needs to cast RHS of shifts to the type of the LHS.

**Pull request merged**
