### PR TITLE
Mark host_dirty() and device_dirty() with no_discard.

### PR DESCRIPTION
**Pull request by mcourteaux**
Lost quite some time, because I needed `set_host_dirty()` instead of `host_dirty()`.

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]
I wish this was the default in C++ :-/

**Comment by mcourteaux** [comment]
Heh, it's not working... It says "attribute ignored". Why is this? Is the macro not properly defined to check compiler support? Or am I misunderstanding the compiler output?

**Comment by steven-johnson** [comment]
> Heh, it's not working... It says "attribute ignored". Why is this? Is the macro not properly defined to check compiler support? Or am I misunderstanding the compiler output?

Dunno, but for a lark, try putting it before HALIDE_ALWAYS_INLINE?

**Comment by mcourteaux** [comment]
Ah, it's because you apparently need to put all the attributes in a single `[[...]]` list... Meh... Let's think...

**Comment by steven-johnson** [comment]
> Ah, it's because you apparently need to put all the attributes in a single [[...]] list... Meh... Let's think...

We require C++17 at this point, we can just write it out explicitly without a macro

**Comment by mcourteaux** [comment]
Nevermind, you were right the order of the attributes mattered, as we mix `__attribute__()` with `[[...]]`. There is no `always_inline` attribute in for `[[ ]]` AFAICT, so this will be it for now.

**Pull request merged**
