### PR TITLE
Unify compile_to_xxx(), part 1

### PR DESCRIPTION
**Pull request by steven-johnson**
(Issue #1200)

— Add options to the Outputs struct to allow for all interesting output
options, and update compile_module_to_outputs accordingly
— Update Pipeline.cpp and Generator.cpp to use
compile_module_to_outputs() in all cases
— Remove the now-unused shim wrappers around
compile_module_to_outputs() from Output.h/.cpp

### CODE REVIEW

**Comment by abadams** [comment]
compile_module_to_outputs looks like it should be a member on Module at this point (now that Module is a full class instead of a struct). Perhaps just "Module::compile(Outputs)"

**Comment by steven-johnson** [comment]
> member on Module at this point

I like it. Will fix.

**Comment by steven-johnson** [comment]
PTAL

**Comment by abadams** [comment]
LGTM

Always happy to see lines deleted > lines added

**Pull request merged**
