### PR TITLE
Fix offload mode autoscheduler results.

### PR DESCRIPTION
**Pull request by shubhamp-ca**
Currently, when autoscheduler is invoked in offload mode, the
the emit options {featurization and schedule} are not working
as expected and bailing out due to auto_scheduler_results not
present in the lowered module, resulting in empty feature and
schedule files produced. This happens because, when offloaded
submodules are recursively resolved, the autoscheduler results
are not copied back into the lowered module. This change fixes
this issue by setting back the auto_scheduler_results in the
ModuleContents of the module that is lowered after resolving
submodules.

### CODE REVIEW

**Comment by steven-johnson** [comment]
Thanks for the fix! Would it be possible to add a test that would catch this (since clearly we don't have one now)?

**Comment by shubhamp-ca** [comment]
> Thanks for the fix! Would it be possible to add a test that would catch this (since clearly we don't have one now)?

I considered adding a test with the change, but I am not sure if either the default autoscheduler or the Adams2019 are currently capable of emitting schedules which lead to creation of submodules within the module which is evaluated. This bug was only hit when the apps/autoscheduler was forced to emit ".hexagon()" calls at the root stage. Any ideas on how this could be tested are welcome.

Though, this bug probably doesn't affect anything currently, it seemed like an "okay" fix for whenever autoschedulers are able to autonomously emit offload calls.

**Comment by shubhamp-ca** [comment]
Also, not really sure what is causing the buildbot failure here. The error is -- 

`CodeGen_LLVM.cpp:993:66: error: ‘void llvm::GlobalObject::setAlignment(unsigned int)’ is deprecated [-Werror=deprecated-declarations]
storage->setAlignment((unsigned)sizeof(halide_scalar_value_t));`

**Comment by steven-johnson** [comment]
re: buildbot failure, that looks like an ongoing LLVM change we're aware of; we can ignore it here.

**Comment by steven-johnson** [comment]
Thanks for the fix!

**Pull request merged**
