### PR TITLE
Need to use --wrap option on libc symbols in skel

### PR DESCRIPTION
**Pull request by ronlieb**
adding back --wrap argument to Makefile target libhalide_hexagon_remote_skel.so for symbols
  malloc, calloc, free, realloc, memalign and stack_chk_fail.

getting an error like this on some of our MTP's.

adsprpc : vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:728:adsp dlopen error: halide_hexagon_remote undefined PLT symbol memalign (72) libhalide_hexagon_remote_skel.so

### CODE REVIEW

**Comment by ronlieb** [comment]
I see the above error on about 40% of our MTP devices, some behave correctly and others fail. I noticed this when i went back to my supply of MTP;s to validate them prior to adding to my test system.

It seems like the libhalide_hexagon_remote_skel.o file would *always* have the symbol present. 
A bit mysterious.

i tried restricting this fix to memalign only, to verify if it was the only symbol, nope, problem then moved to free, so i think all of the symbols need to be wrap'ed.

**Comment by dsharletg** [comment]
I've off-and-on seen the same problem with qurt_mutex_lock (I think that was it...) but I didn't know how to fix it. Do you think those functions need this too?

**Comment by ronlieb** [comment]
Is the occasional failure with qurt_mutex_lock an unresolved PLT symbol? or some other signature?

**Comment by dsharletg** [comment]
I can't remember. It was definitely some kind of linker-ish error from dlopen, but I can't remember if it was precisely the same error or not.

**Comment by ronlieb** [comment]
i am checking with Jack May on the qurt_mutex_lock symbol question.

**Comment by ronlieb** [comment]
Jack says the qurt_mutex_*s symbols are all visible in the DSP image, and do not need the --wrap approach.

**Comment by dsharletg** [comment]
Cool, thanks for checking. It must have been something else.

**Pull request merged**
