### PR TITLE
Refactor runtime

### PR DESCRIPTION
**Pull request by dsharletg**
This PR does some refactoring of the runtime:

- Use typedefs for function pointers.
- Rename a few halide_ things that are already inside the Halide::Runtime::Internal namespace.

### CODE REVIEW

**Comment by dsharletg** [comment]
I've tested this on linux, I'm about to test it on OSX.

**Comment by steven-johnson** [comment]
LGTM

**Comment by dsharletg** [comment]
Thanks for the quick review!

It's passing on OSX.

**Comment by dsharletg** [comment]
Actually I just spotted a few wrong handlers, fixed them.

**Pull request merged**
