### PR TITLE
Clone of https://github.com/halide/Halide/pull/5588 for testing

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by xndcn** [comment]
Append a commit #b63ad8d to disable this checking in linux so that linux-make build test can pass. Please help me cherry-pick the commit and trigger the buildbot again, thanks.

**Comment by steven-johnson** [comment]
> Append a commit #b63ad8d to disable this checking in linux so that linux-make build test can pass. Please help me cherry-pick the commit and trigger the buildbot again, thanks.

Done

**Comment by xndcn** [comment]
Seems something wrong in buildbot
```
'sm_80' is not a recognized processor for this target (ignoring processor)
'+ptx70' is not a recognized feature for this target (ignoring feature)
'sm_80' is not a recognized processor for this target (ignoring processor)
'sm_80' is not a recognized processor for this target (ignoring processor)
'+ptx70' is not a recognized feature for this target (ignoring feature)
'sm_80' is not a recognized processor for this target (ignoring processor)
'sm_80' is not a recognized processor for this target (ignoring processor)
'+ptx70' is not a recognized feature for this target (ignoring feature)
'sm_80' is not a recognized processor for this target (ignoring processor)
terminate called after throwing an instance of 'Halide::RuntimeError'
  what():  Error: CUDA: cuModuleLoadData failed: CUDA_ERROR_INVALID_PTX
```

**Comment by steven-johnson** [comment]
Fixed by https://github.com/halide/Halide/pull/5617

**Pull request closed without merging**
