### PR TITLE
Expand the x86 SIMD variants tested in correctness_vector_reductions

### PR DESCRIPTION
**Pull request by steven-johnson**
A recent bug in LLVM codegen was missed because it only affected x86 architectures with earlier-than-AVX2 SIMD enabled; it didn't show up for AVX2 or later. This revamps correctness_vector_reductions to re-run multiple times when multiple SIMD architectures are available on x86 systems.

(correctness_vector_reductions was chosen here because it reliably demonstrated the specific failures in this case.)

### CODE REVIEW

**Comment by abadams** [comment]
We used to run the full correctness tests with HL_JIT_TARGET=x86-64-linux-sse41 or whatever in addition to the host target. I guess we stopped doing that? Should we revive it?

**Comment by steven-johnson** [comment]
> We used to run the full correctness tests with HL_JIT_TARGET=x86-64-linux-sse41 or whatever in addition to the host target.

No, we are still doing that -- in this particular case, we didn't catch the error because our nightly LLVM builds on the x86 machines were made just prior to the commit that injected the erroneous behavior (and so this change actually wouldn't have caught it in our tests).

That said, this change still has value: partly because it adds more robustness to this test, but (mostly) because I want this behavior when running this test inside Google: the tests are run on a heterogenous set of machines (mostly AVX2-class, some less, some more), and LLVM changes are pulled in on a hard-to-predict schedule; if this version of this test had landed inside Google it would have caught this failure much earlier.

(Yes, I thought about making a specific-to-Google version of this test, but then I decided that the changes were modest and strictly a win everywhere.)

**Comment by steven-johnson** [comment]
Gentle review ping

**Review by alinas — APPROVED** [review]
LGTM.

**Comment by abadams** [comment]
I'm still a bit confused about this - does it actually add any test coverage to our CI, or is this redundant with running the test under multiple values of HL_JIT_TARGET?

**Comment by steven-johnson** [comment]
It adds coverage in a way that doesn't require customizing multiple different test scripts.

**Pull request merged**
