### PR TITLE
Clone #3225 for the build bots

### PR DESCRIPTION
**Pull request by dsharletg**
Testing

### CODE REVIEW

**Comment by dsharletg** [comment]
I manually started a build that is hopefully running on this branch: https://buildbot.halide-lang.org/master/#/builders/26/builds/5

**Comment by pranavb-ca** [comment]
buildbot/linux-64-gcc53-testbranch-500 and buildbot/linux-64-gcc53-testbranch-600 are failing in make test_bazel and the problem relates to a ccache issue.

The buildbot running HVX seems to have stalled at a particular step; it hasn't progressed since the last time i saw it about 30 mins back - https://buildbot.halide-lang.org/master/#/builders/26/builds/19

My concern is a segfault in "fft" run in buildbot/mac-64-testbranch-500. @aankit-ca, @dsharletg - do you think it is related to gather? or your guess is as good as mine?

**Comment by dsharletg** [comment]
The failures look unrelated. The Hexagon tests passed. However, it's worth noting that with https://github.com/halide/Halide/pull/3294/commits/7c8355c9ccbdbac30089bf9110922762d8120a9a#diff-2b98879ac6c5c51b7c360b11c440b254, vgather isn't actually being tested on the build bots, it's just testing that the PR didn't break anything else. We would need to configure the build bots to test v65 for them to test it itself.

I should have mentioned this earlier, I had thought of it and I thought it was OK just temporarily as presumably you guys are testing the actual vgather functionality as part of getting this PR in working order? I don't want to introduce a variable into the buildbot work going on right now...

**Comment by aankit-ca** [comment]
Unless it's building for hvx with >=v65 it should not affect FFT.

**Pull request closed without merging**
