### PR TITLE
IRMutator->IRMutator2, Part 11 [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by abadams** [comment]
It might be wise to hold off on this one until async is merged up with master. There's currently a nasty merge to do inside storagefolding, and this will make it harder.

**Comment by steven-johnson** [comment]
Okee dokee. Is there any timetable/plan for that merge?

**Comment by steven-johnson** [comment]
(Renamed to be sure no one merges inadvertently)

**Comment by steven-johnson** [comment]
Closing because incredibly stale. Will revisit after async branch lands.

**Pull request closed without merging**
