### PR TITLE
JITGeneratorContext -> GeneratorTarget

### PR DESCRIPTION
**Pull request by steven-johnson**
"JITGeneratorContext" was a misleading name since it isn't used only for JIT. Renamed to "GeneratorTarget" since it's really used to specify a Target to a Generator.

Also: driveby optimization to move externs_map and value_tracker out of GeneratorBase and completely into GeneratorContext, since the redundant implementations were, well, redundant.

### CODE REVIEW

**Comment by steven-johnson** [comment]
Clean, PTAL

**Comment by steven-johnson** [comment]
Monday morning review ping

**Comment by steven-johnson** [comment]
Don't merge yet: there is one post-approval possible improvement I want to explore.

**Comment by steven-johnson** [comment]
Reworked now that https://github.com/halide/Halide/pull/2412 has landed: GeneratorContext is now a concrete class that is a base class of Generator, which simplifies usage a great deal. PTAL.

**Comment by abadams** [comment]
Agree that that's an improvement. lgtm.

**Pull request merged**
