### PR TITLE
remove use of new/delete and use malloc/free for hexagon_host.cpp - w…

### PR DESCRIPTION
**Pull request by ronlieb**
…windows build issue 
unresolved new and delete when using VS to build Halide and building helloHexagon

built runtime with 8.0.05 as well.

### CODE REVIEW

**Comment by dsharletg** [comment]
These probably should actually be calls to halide_malloc and halide_free.

**Comment by dsharletg** [comment]
Also - why rebuild the runtime? This change doesn't affect the runtime?

**Comment by ronlieb** [comment]
ok, cleaned it up a bit

**Comment by dsharletg** [comment]
Looks like they are running now. Maybe the hiccup was related to https://twitter.com/awscloud/status/836656554212372480 ?

**Comment by ronlieb** [comment]
ok to merge?

**Pull request merged**
