### PR TITLE
Set CMAKE_CROSSCOMPILING_EMULATOR in toolchain.linux-arm32.cmake

### PR DESCRIPTION
**Pull request by steven-johnson**
Also add comments.

(Trying this as an alternative to https://github.com/halide/Halide/pull/5805)

### CODE REVIEW

**Review by alexreinking — APPROVED** [review]

**Comment by alexreinking** [comment]
Approved, assuming it works.

**Comment by steven-johnson** [comment]
Testing now, and looks promising, but there is a minor fly in the ointment: we are going to need this toolchain for LLVM builds too, but those can't easily rely on a toolchain file in the Halide repo. (Currently this is working because I made a local copy of the toolchain on the armbots for experimentation.) 

AFAIK, LLVM doesn't provide toolchain files (just instructions on configuring stuff manually). 

Options:
- Use toolchain file for Halide itself; for LLVM, just replicate the necessary CMake stuff directly into buildbot script.
- Add a toolchain file to the buildbot repo and have the workers use that one for LLVM + Halide. (Then we have to keep then in sync, of course.)
- Add a toolchain file locally on the arm32 bots and point to it. Maintain manually. Yuck.
- Don't use the toolchain file at all; instead, put the relevant CMake mojo into the buildbot script. Yuck.
- Something else.

**Comment by steven-johnson** [comment]
Oh, also: do we need to do

    SET(CMAKE_FIND_ROOT_PATH /usr/arm-linux-gnueabihf)

or something similar as well?

**Comment by alexreinking** [comment]
>     * Add a toolchain file to the buildbot repo and have the workers use that one for LLVM + Halide. (Then we have to keep then in sync, of course.)

This is a good idea. I think there's a "push file to worker" step that we could use to keep the workers in sync with the master.

**Comment by alexreinking** [comment]
> Oh, also: do we need to do
> 
> ```
> SET(CMAKE_FIND_ROOT_PATH /usr/arm-linux-gnueabihf)
> ```
> 
> or something similar as well?

I think one typically sets `CMAKE_SYSROOT`. See if things work without setting any of these variables and then try that one first.

**Comment by steven-johnson** [comment]
> This is a good idea. I think there's a "push file to worker" step that we could use to keep the workers in sync with the master.

Yeah, we would still have the potential issue of keeping the toolchain files in sync between the Halide repo and build_bot repo, but that's ok

**Comment by steven-johnson** [comment]
The test above are misleading since some buildbot changes have to land too, but from offline testing, I'm confident enough that it works to land it.

**Pull request merged**
