### PR TITLE
Add HALIDE_FALLTHROUGH_INTENDED macro

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by zvookin** [comment]
I'd prefer to just eliminate the use of fall through.

**Comment by zvookin** [comment]
That assumes we can turn on the warnings in our builds so none creep in.

**Comment by steven-johnson** [comment]
> That assumes we can turn on the warnings in our builds so none creep in.

We could add `-Wimplicit-fallthrough` but we'd need to sniff for the proper version of Clang/GCC -- IIRC it was only added to GCC in v7 so we'd definitely have to have some checking.

**Comment by steven-johnson** [comment]
Offline discussion suggests we should just forbid using implicit fallthrough in Halide code, period; I'm inclined to agree, unless we somehow find an incredibly compelling instance otherwise, which we won't. So I'm closing this.

**Pull request closed without merging**
