### PR TITLE
Use LLVM instead of hexagon-clang to compile Hexagon code

### PR DESCRIPTION
**Pull request by dsharletg**
This PR removes the hack of using hexagon-clang to compile Halide code from LLVM IR to Hexagon assembly, and instead uses the same LLVM toolchain path as the other LLVM based backends.

This PR also dumps out the Hexagon assembly when HL_DEBUG_CODEGEN >= 2.

### CODE REVIEW

**Comment by dsharletg** [comment]
This PR slows down Hexagon code by 1-5% in my measurements. I think the difference is mostly due to different tuning for unrolling thresholds and things like that. I've also noticed code that gets faster than with hexagon-clang, and some compile times are dramatically better with LLVM (presumably because of less aggressive unrolling).

**Comment by ronlieb** [comment]
which codes are runnable by us (not propietary) where we could reproduce the difference?
for example, what numbers do  you see for camera_pipe, HelloHexagon  (before and after).

**Comment by steven-johnson** [comment]
LGTM

**Comment by dsharletg** [comment]
I see a ~5-10% regression in the simulated cycle count for the camera pipe (depending on whether lazy_slice_vectors is merged or not). HelloHexagon is too small of a benchmark to see a difference in when measuring performance on device.

**Pull request merged**
