### PR TITLE
Make the IntrusivePtr interface more similar to std::shared_ptr

### PR DESCRIPTION
**Pull request by abadams**
The main effect is to replace contents.ptr-> with contents-> in lots of places.

Opinions?

### CODE REVIEW

**Comment by steven-johnson** [comment]
Obvious question: should we consider nuking IntrusivePtr entirely and using shared_ptr directly?

**Comment by abadams** [comment]
I thought about it, but the semantics are different for intrusive pointers.
If you unwrap an IntrusivePtr (e.g. expr.as<Add>()) and then wrap it back
up (passing a const Add * to something expecting an Expr), you preserve the
reference count. If you do that with a shared_ptr you're going to have a
bad time. Switching to shared_ptr (and make_shared) would involve
rethinking a lot of code in visitors.

**Comment by steven-johnson** [comment]
LGTM

**Comment by zvookin** [comment]
std::shared_ptr requires an extra memory allocation as it cannot rely on memory being allocated inside the pointed to object. Since Halide refcounts Expr, I expect adding an extra memory allocation per ref counted object would be notable overhead.

**Comment by abadams** [comment]
I think we'd avoid that pitfall by using make_shared<Foo>(args) instead of
std::shared_ptr<Foo>(new Foo);

The problem is that we have this idiom where downcasting an Expr (Expr::as)
takes a shared_ptr and returns a const raw pointer to a specific subclass.
I don't think we can make that idiom safe with shared_ptr, so it would
require rewriting lots of code to handle shared_ptrs to the subclasses
instead, which would indeed be a lot of overhead.

**Pull request merged**
