### PR TITLE
Split Generator builds into libs

### PR DESCRIPTION
**Pull request by steven-johnson**
This reworks the Generator build rules so that instead of building a
binary directly from source, we create intermediate libraries that are
then linked into binaries.

As-is, this change is a no-op, but paves the way for some other
upcoming changes (which invole combining multiple precompiled
Generators into a single binary, then accessing them via the
GeneratorRegistry); doing this as a separate PR should make for a much
cleaner review.

(Note that we use shared libraries rather than static libraries, mainly
because static libraries will get dead-stripped away due to the way
Generators are registered, and there doesn’t seem to be a good,
portable “alwayslink” option across all systems.)

### CODE REVIEW

**Comment by steven-johnson** [comment]
(kicked off windows builds too)

**Comment by abadams** [comment]
LGTM, but what's the motivation here? Linking multiple generators into a single binary?

**Comment by abadams** [comment]
Oh, nvm, I didn't read the description.

**Comment by steven-johnson** [comment]
This works properly on my local Linux box but fails on Travis, with "unable to find libHalide.so" -- so far I've been unable to figure out what's different on the Travis setup.

**Comment by kgnk** [comment]
You need the [/INCLUDE](https://msdn.microsoft.com/en-us/library/2s3hwbhs.aspx) command line switch. It takes a mangled name.

**Comment by steven-johnson** [comment]
Leaving this open for now, but probably going to abandon this -- I'm going to investigate other ways to solve the downstream problem I was hoping to address this way.

**Pull request closed without merging**
