### PR TITLE
Add a bottleneck for loading libhalide_hexagon_host.so

### PR DESCRIPTION
**Pull request by steven-johnson**
We can override this at present by using (e.g.) LD_LIBRARY_PATHS, in
some cases anyway, but having a weak runtime method to override makes
some use cases much simpler and safer.

### CODE REVIEW

**Comment by steven-johnson** [comment]
Edit: I guess I could accomplish the same thing by overriding halide_load_library() and special-casing for "libhalide_hexagon_host.so", but that feels more fragile than necessary.

**Comment by dsharletg** [comment]
Most of our other similar code uses an environment variable to solve this problem, e.g. you would set HL_HEXAGON_HOST_LIB=blah. I'm not opposed to this design, I just want to make sure you considered this design, at least for consistency with other stuff (though most of it is probably Hexagon to begin with...).

**Comment by steven-johnson** [comment]
> Most of our other similar code uses an environment variable to solve this problem

This is true, but I think that pretty much all of those are compile-time problems, not runtime. At compile-time it's pretty reasonable for us to believe that we can control the env vars; at runtime, I'm less confident (i.e., EvilApp manages to hijack the env vars to point to libevil.so instead of libhalide_hexagon_host.so).

**Comment by steven-johnson** [comment]
Actually, please don't land this yet; I think a different solution will be better-suited to my needs. (Leaving it open for now just in case.)

**Pull request closed without merging**
