### PR TITLE
Add static-dimension annotations to Buffer usage in python_bindings and tutorials

### PR DESCRIPTION
**Pull request by steven-johnson**
Plus more fixes to corner cases in src/ and halide_image_io that I missed earlier

### CODE REVIEW

**Comment by abadams** [comment]
I'm not convinced about the changes to the tutorials. Adding an explicit dimensionality on the left hand side of a realize call is redundant with the number of arguments passed on the right hand side. I don't think it adds any clarity.

**Comment by steven-johnson** [comment]
> I'm not convinced about the changes to the tutorials. Adding an explicit dimensionality on the left hand side of a realize call is redundant with the number of arguments passed on the right hand side. I don't think it adds any clarity.

If we want to avoid redundancy there, we could just use `auto`...

Not gonna spend time arguing this, but IMHO putting thus into the tutorials is one of the most important things to do; the idioms we show new users there is what they will use as they write new code. If we want them to use static dimensions when appropriate (and I do want them to), we should show them how to do so here.

**Comment by abadams** [comment]
auto doesn't quite work because you need a cast to an explicit type of Buffer for operator() to work on the resulting object. I'm not convinced it's appropriate to use explicit static dimensionality in a casual JIT context in which so much other stuff is implicit or automatic.

**Comment by steven-johnson** [comment]
(going to land this in pieces instead)

**Pull request closed without merging**
