### PR TITLE
Allow Output<Buffer<>> = Func

### PR DESCRIPTION
**Pull request by steven-johnson**
This eases converting Generators that used helper functions to produce Funcs that are returned from build().

Note the caveat about names: I chose to issue a warning rather than make this an error. not sure if this is the right decision.

(I also briefly thought about modifying Func::in() to allow making a global-wrapper with an arbitrary name, but that seems like a bad idea...)

### CODE REVIEW

**Comment by steven-johnson** [comment]
Clean-ish, PTAL

**Comment by steven-johnson** [comment]
Monday Review Ping

**Comment by abadams** [comment]
The naming issue is vexing. I've been trying to think of a fix without much success.

**Comment by steven-johnson** [comment]
Likewise, I don't know how to solve the naming issue. It would be nice if we could just rename Funcs but that is a pretty deeply ingrained thing at this point.

**Comment by abadams** [comment]
Without a reasonable solution, I think we should just continue to disallow this.

**Comment by steven-johnson** [comment]
How bad is just having the wrong name in this case? The downside is basically:

-- metadata is wrong, so tools like RunGen don't work as user expects
-- .stmt files have "wrong" names, so debugging code is confusing

But AFAICT there is no possibility of wrongness in terms of output.

**Comment by steven-johnson** [comment]
We're not really happy with any of the options right now. I'm going to leave this PR open for a while until I get evidence as to whether this is essential rather than convenient-in-some-cases.

**Comment by steven-johnson** [comment]
Revamped: add code to remap metadata names. This is some ugly plumbing but does solve the problem.

**Comment by steven-johnson** [comment]
Travis failures are unrelated timeouts; PTAL to see if you like the metadata-munging approach.

**Comment by abadams** [comment]
It aint pretty, but it gets the job done.

**Pull request merged**
