### PR TITLE
compile_multitarget() needs love to handle External_Code blocks properly

### PR DESCRIPTION
**Pull request by steven-johnson**
Previously, we’d output them multiple times, causing duplicate-symbol
errors at link time.

### CODE REVIEW

**Comment by steven-johnson** [comment]
ping?

**Comment by abadams** [comment]
Probably @zvookin should look at this one. Buildbots are all happy.

**Comment by steven-johnson** [comment]
zalman@ and I discussed this offline; he wants to do some additional testing before landing this, so don't merge yet.

**Comment by steven-johnson** [comment]
Ping to zalman@

**Comment by steven-johnson** [comment]
Synced to master, PTAL ping

**Comment by zvookin** [comment]
I don't really like this happening without some sort of control. It assumes all the things with the same name are identical, which is a common use case, but it may hide errors as well. I'd envisioned this as having the user of the feature ensure the names are unique or that only one copy of a multiply used name gets inserted.

One way to go is to change the test to make sure the names used are unique for different compilation targets or to make sure only one of them inserts the extra code. Another way to go is to add a flag to the ExternalCode block that allows the merging explicitly. A third approach is to compare the contents of the code blocks and to signal an error if they have the same name and the contents are not byte identical.

At some level I'm tempted to just let it go, but intuition is nagging me that it will actually cause a bug somewhere. E.g. a place where some appended runtime needs different versions for different levels of a single processor architecture.

**Pull request closed without merging**
