### PR TITLE
[release/16.x] Changes to trigger another build for release.

### PR DESCRIPTION
**Pull request by derek-gerstmann**

### CODE REVIEW

**Comment by steven-johnson** [comment]
(FYI: you can also use `git commit --allow-empty -am "trigger buildbots" && git push` for this)

**Comment by derek-gerstmann** [comment]
> (FYI: you can also use `git commit --allow-empty -am "trigger buildbots" && git push` for this)

Ahhh ... thanks!! I'll do this from now on !

**Comment by derek-gerstmann** [comment]
Ready to merge (to sync the release/16.x branch to this changeset to match the build)

**Comment by derek-gerstmann** [comment]
@steven-johnson Hmmm ... where do I find the binary packages for this build?  They aren't listed on https://buildbot.halide-lang.org/

**Comment by steven-johnson** [comment]
> @steven-johnson Hmmm ... where do I find the binary packages for this build? The change sets don't match for the v16.x tarballs listed on https://buildbot.halide-lang.org/

The binaries there are triggered by the `nightly` builds, but several over the past few days seems to have gotten broken due to the LLVM churn in the LLD apis. Let me check this morning to see if those are finally stable.

**Comment by derek-gerstmann** [comment]
> > @steven-johnson Hmmm ... where do I find the binary packages for this build? The change sets don't match for the v16.x tarballs listed on https://buildbot.halide-lang.org/
> 
> The binaries there are triggered by the `nightly` builds, but several over the past few days seems to have gotten broken due to the LLVM churn in the LLD apis. Let me check this morning to see if those are finally stable.

Ah, okay ... that explains things!  Okay, thank you!

**Comment by derek-gerstmann** [comment]
@steven-johnson Hmmm ... the nightly packages for 16.0.0 still don't seem to have the same checksums.  Can I force a nightly build for release/16.x?

**Comment by steven-johnson** [comment]
> @steven-johnson Hmmm ... the nightly packages for 16.0.0 still don't seem to have the same checksums. Can I force a nightly build for release/16.x?

Do you mean they are built from different commits? Pretty sure none of them should have matching checksums...

**Comment by derek-gerstmann** [comment]
> > @steven-johnson Hmmm ... the nightly packages for 16.0.0 still don't seem to have the same checksums. Can I force a nightly build for release/16.x?
> 
> Do you mean they are built from different commits? Pretty sure none of them should have matching checksums...

Yes.  The "Cutting a Release" docs mention that they should all match, and to download these for the release binaries:
https://github.com/halide/Halide/wiki/Cutting-a-release#step-5-get-the-binaries-from-the-buildbots

**Comment by steven-johnson** [comment]
Got it. I can manually trigger the nightlies now if you like.

**Comment by derek-gerstmann** [comment]
> Got it. I can manually trigger the nightlies now if you like.
> 
> EDIT: I just did. Check back in a few hours :-)

Perfect, thank you!

**Comment by derek-gerstmann** [comment]
@steven-johnson It looks like the nightly binary packages from the past few builds still don't match across all platforms for Halide-${PLATFORM}-16.0.0.  Does this PR need to get merged in order for this to work?

**Comment by steven-johnson** [comment]
> @steven-johnson It looks like the nightly binary packages from the past few builds still don't match across all platforms for Halide-${PLATFORM}-16.0.0. 

> Does this PR need to get merged in order for this to work?

No, this PR probably just makes things worse. What we need to do is leave the release/16.x branch unchanged for a day so that the nightlies have a stable target. I recommend just closing this PR, and let's discuss the issue further via email or similar.

**Comment by derek-gerstmann** [comment]
Okay, sounds good.  I'll close this PR and follow up.

**Pull request closed without merging**
