### PR TITLE
Let the user pass the Func to use to the reduction helpers

### PR DESCRIPTION
**Pull request by abadams**
This makes them schedulable if necessary without having to rewrite parts of someone's pipeline.

### CODE REVIEW

**Comment by dsharletg** [comment]
Aren't the reduction helpers equivalent to:

```
Func reduction;
reduction(x) += ...;

reduction.in();
```

If we're going to be encouraging/making a breaking change that requires access to the inner reduction, maybe we should be encouraging migrating to this instead?

**Comment by abadams** [comment]
I think that pattern is cleaner to write, but the breaking change in question - turning off llvm loop optimizations - may require retrofitting old code, which might be difficult to rewrite in that way. Adding a last arg to the inline reduction helpers makes for an easier patch.

**Comment by steven-johnson** [comment]
> Adding a last arg to the inline reduction helpers makes for an easier patch.

True, but it also makes for a weird (IMHO) syntactical wart that we will be stuck with for a long time (maybe forever). Is retrofitting code to the "proper" style really likely to be that tricky?

**Comment by abadams** [comment]
There are also things like argmax, which aren't so easy to write out manually as a summation

**Comment by abadams** [comment]
Also, this isn't really adding a new last arg. Currently they take a string as the last arg, which is the name of the anonymous Func. This upgrades that interface to accept a Func too. That was the rationale behind this design when we discussed it in the dev meeting.

**Review by steven-johnson — COMMENTED** [review]
Meh, ok

**Review by steven-johnson — APPROVED** [review]

**Pull request merged**
