### PR TITLE
Remove the use of qurt_hvx_get_mode

### PR DESCRIPTION
**Pull request by pranavb-ca**
On newer Snapdragon targets, the way for a thread to get
HVX 64B or 128B mode has changed. This means that we can
no longer use qurt_hvx_get_mode() inside qurt_thread_pool to
know in what mode the threads in the thread pool should lock
HVX. This patch adds a new function set_par_hvx_mode that
bakes in a call into every pipelines that uses HVX and parallel
that tells the runtime what mode the master thread is going
to be using. The paralle runtime "remembers" this and uses
this mode for the worker threads in the thread pool.

@dsharletg : PTAL

### CODE REVIEW

**Comment by dsharletg** [comment]
This seems dangerous (not thread safe)...

**Comment by pranavb-ca** [comment]
Yes, I wanted to guard this with a mutex so that only one thread accesses it at one time, but I didn't do that because the way it is designed I think the master will always set master_thread_mode before any other thread tries to access it.

**Comment by dsharletg** [comment]
The problem is multiple threads sharing the same global state. A mutex can't fix that unless we get really messy. The ways I can see to fix this are:

- Add a parameter to halide_do_par_for somehow, and set the value of this parameter in codegen. I can't think of a clean way to do this.
- Thread local storage. With thread local storage, we could basically simply reimplement qurt_hvx_get_mode (qurt_hvx_lock sets the thread local value, halide_qurt_hvx_get_mode just returns it).
- Is there no replacement for qurt_hvx_get_mode? Is maybe the problem just that we need to version this code, or is it really disappearing completely?

**Comment by pranavb-ca** [comment]
For the way we want to use qurt_hvx_get_mode, it is dead. Without going into too many details, this is primarily because of what Qurt HVX mode means now. There is no real replacement for qurt_hvx_get_mode at this time. The only other alternative is to work on a TLS based solution that I'll work on next week as I am out thu and fri this week.

Although, one point i wanted to mention was that, yes, each thread shares the common global state, but that state is written and read by the same thread and that thread only.

**Comment by dsharletg** [comment]
OK, I think this is what we should do: remove all qurt_hvx_lock logic from the thread pool itself, and then CodeGen_Hexagon needs to rewrite the qurt_hvx_lock calls more substantially. Prior to parallel for loops, it should unlock HVX if it was locked, and inside parallel the body of for loops, it should re-lock it.

**Comment by pranavb-ca** [comment]
Ok I'll work on that.

**Pull request closed without merging**
