### PR TITLE
[x86 & wasm] Split up double saturating-narrows from i32

### LINKED ISSUE #7069: [x86] Codegen should split up double saturating-narrows
CodeGen_ARM already does this (see [here](https://github.com/halide/Halide/blob/16243da75944ce9ea8d4e8eb90d6f104f06284ec/src/CodeGen_ARM.cpp#L1186-#L1216)).

x86's options are far more limited (only `i32 -> u8` and `i32 -> i8` are possible), but a pair of saturating narrow instructions will be better than what we currently generate. Other backends might also benefit from this, but I haven't looked into it.

### PR DESCRIPTION
**Pull request by rootjalex**
We can get much better codegen for double saturating narrows from i32 on x86 and wasm. HVX and ARM backends both already do this. Also added tests to simd_op_check

Fixes #7069 

Here's an example from x86 (wasm is similar):
```
Var x("x");
ImageParam in(Int(32), 1);
Func f("f");

f(x) = u8_sat(in(x));
f.vectorize(x, 32);

Target x86("x86-64-linux-avx-avx2-fma-sse41");
f.compile_to_assembly("vpack.asm", f.infer_arguments(), x86);
```
Previously:
```
	vpminsd	-96(%rax,%rcx,4), %ymm0, %ymm2
	vpminsd	-64(%rax,%rcx,4), %ymm0, %ymm3
	vpminsd	-32(%rax,%rcx,4), %ymm0, %ymm4
	vpminsd	(%rax,%rcx,4), %ymm0, %ymm5
	vpmaxsd	%ymm1, %ymm2, %ymm2
	vpmaxsd	%ymm1, %ymm3, %ymm3
	vpackusdw	%ymm3, %ymm2, %ymm2
	vpmaxsd	%ymm1, %ymm4, %ymm3
	vpmaxsd	%ymm1, %ymm5, %ymm4
	vpackusdw	%ymm4, %ymm3, %ymm3
	vpermq	$216, %ymm3, %ymm3              # ymm3 = ymm3[0,2,1,3]
	vpermq	$216, %ymm2, %ymm2              # ymm2 = ymm2[0,2,1,3]
	vpackuswb	%ymm3, %ymm2, %ymm2
	vpermq	$216, %ymm2, %ymm2              # ymm2 = ymm2[0,2,1,3]
	vmovdqu	%ymm2, (%r8,%rcx)
```
Now:
```
	vmovdqu	-96(%rax,%rcx,4), %ymm0
	vmovdqu	-32(%rax,%rcx,4), %ymm1
	vpackssdw	-64(%rax,%rcx,4), %ymm0, %ymm0
	vpackssdw	(%rax,%rcx,4), %ymm1, %ymm1
	vpermq	$216, %ymm0, %ymm0              # ymm0 = ymm0[0,2,1,3]
	vpermq	$216, %ymm1, %ymm1              # ymm1 = ymm1[0,2,1,3]
	vpackuswb	%ymm1, %ymm0, %ymm0
	vpermq	$216, %ymm0, %ymm0              # ymm0 = ymm0[0,2,1,3]
	vmovdqu	%ymm0, (%r8,%rcx)
```

### CODE REVIEW

**Review by abadams — APPROVED** [review]

**Comment by steven-johnson** [comment]
https://buildbot.halide-lang.org/master/#/builders/42/builds/693 looks like perhaps a real failure

**Review by steven-johnson — CHANGES_REQUESTED** [review]
https://buildbot.halide-lang.org/master/#/builders/42/builds/693 looks like a problem

**Comment by rootjalex** [comment]
@steven-johnson I see the same failure on #7279 , so I don't think either PR is responsible for the failure
https://buildbot.halide-lang.org/master/#/builders/42/builds/692

**Comment by steven-johnson** [comment]
> @steven-johnson I see the same failure on #7279 , so I don't think either PR is responsible for the failure https://buildbot.halide-lang.org/master/#/builders/42/builds/692

great, it's probably another LLVM injection :-/

**Comment by steven-johnson** [comment]
The predicated-load failure isn't happening for me locally with top-of-tree LLVM, so maybe it's a temporary flake; I'm forcing rebuilds on the x64 bots to see if it recurs

**Comment by rootjalex** [comment]
Only failing test appears unrelated. @steven-johnson think it’s good to go?

**Comment by steven-johnson** [comment]
Failure is vectorized_gpu_allocation, which I've *never* seen before as a flake or even an ordinary failure, so let me retry it just a bit first.

**Comment by steven-johnson** [comment]
The failure is now in our old friend, correctness_atomics, aka "Mr. Flaky", so I think we're good to go

**Review by steven-johnson — APPROVED** [review]

**Pull request merged**
