### PR TITLE
Create vagrant & VirtualBox setup to run OpenGL tests headlessly.

### PR DESCRIPTION
**Pull request by ronen**
This makes it easy for OS X developers who are working on OpenGL to build Halide and `test_opengl` on Ubuntu 14.04 and/or Ubuntu 16.04, by doing:

```
$ cd Halide/test/opengl/vagrant
$ vagrant up [u14|u16]
[...]
$ vagrant ssh [u14|u16] -c "sh /vagrant/build_tests.sh"
[...]
```

...With the intent of course to avoid future time wasters in which PRs that work on OS X break things on Linux (such as #1381 reverted by #1467).

This PR just adds the subdirectory `test/opengl/vagrant` with the necessary files to create and provision the virtual machines, along with the build script.  More details in `test/opengl/vagrant/README.md`

Let me know if you don't think both 14.04 and 16.04 aren't needed, and I'd be happy to drop one of them.  And of course open to any other suggestions/improvements.

cc @shoaibkamil

### CODE REVIEW

**Comment by dsharletg** [comment]
This seems cool and useful. I'm trying to test it, I see this:

    There are errors in the configuration of this machine. Please fix
    the following errors and try again:

    vm:
    * The box 'bento/ubuntu-14.04' could not be found.

I see that that string is part of your config files, but I'm not sure how to change it (or if I should).

**Comment by ronen** [comment]
@dsharletg Hmm, you shouldn't have to change anything.  Vagrant normally automatically downloads the box if you don't have it locally.  I have no idea why it failed... I'm not a super Vagrant expert, it generally works for me.

Maybe try first explicitly adding the box, and see whether Vagrant gives you any more detailed error message?  

```
 $ vagrant box add --provider virtualbox bento/ubuntu-14.04
```
To make sure something hasn't changed in Vagrant's box repository, I just cleaned out my boxes (`vagrant box remove bento/ubuntu-14.04`) and tried the above and it worked fine.  Here's what it looks like  for me:

```
$ vagrant box add --provider virtualbox bento/ubuntu-14.04
==> box: Loading metadata for box 'bento/ubuntu-14.04'
    box: URL: https://atlas.hashicorp.com/bento/ubuntu-14.04
==> box: Adding box 'bento/ubuntu-14.04' (v2.2.9) for provider: virtualbox
    box: Downloading: https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04/versions/2.2.9/providers/virtualbox.box

    [...watch download progress indicator for a few minutes...]

==> box: Successfully added box 'bento/ubuntu-14.04' (v2.2.9) for 'virtual box'!
$
```

If that works for you, then `vagrant up` should work afterwards.   If not, maybe this'll at least give some hints.

FWIW my environment is:

````
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34
$ vagrant --version
Vagrant 1.8.5
$ grep BundleVersion /Applications/VirtualBox.app/Contents/Info.plist
    <key>CFBundleVersion</key>                  <string>5.0.26</string>
$
```

**Comment by dsharletg** [comment]
Hmm, it looks like Google IT is giving me an older version of vagrant... or something weird is going on (my install of vagrant says that command isn't valid/not invoked properly). Either way, this seems like it is useful to at least you and I don't see any issues with it, I'll go ahead and merge it.

**Comment by dsharletg** [comment]
(BTW, great documentation!)

**Comment by ronen** [comment]
bummer vagarant's not working for you, but thanks for the merge!

**Pull request merged**
