### PR TITLE
Added target flags for OpenCL embedded profile

### PR DESCRIPTION
**Pull request by dsharletg**
This CL adds/changes a few target flags:

- CLEmbedded: generate code compatible with the OpenCL embedded profile
- CLint64: When generating embedded profile compatible code, enable the cles_khr_int64 extension
- CLDoubles is deprecated, CLfp64 is the new name (for consistency with CLint64). It still has the same functionality as before.

### CODE REVIEW

**Comment by abadams** [comment]
I think float64 would be more inline with the rest of our type naming than fp64

**Comment by dsharletg** [comment]
I named it fp64 so that our feature flags map onto OpenCL's extension names, but the motivation for that is weak. I could go either way on it.

**Comment by abadams** [comment]
fp64 sounds fine then

**Comment by jrprice** [comment]
Presumably this means that we would need to know ahead of time whether or not we are targeting embedded profile. Is this really necessary?

There is an `__EMBEDDED_PROFILE__` macro which the OpenCL compiler will define to `1` if the device only supports embedded profile - couldn't we wrap the problematic code with some `#if` statements to handle this automatically?

I'm just a little concerned that an Android application (for example) may well need to run on both embedded and full profile devices, and this would mean that the developer would need to manually generate Halide programs for both cases.

**Comment by dsharletg** [comment]
I think the embedded profile is a subset of the full profile, so enabling cl_embedded shouldn't preclude the code from running on full profile devices. It *definitely* does not do so currently, where we don't really use cl_embedded for much yet. 

You're correct that we could just wrap the problematic pre-amble code in an #if block. In fact, when I first started fixing this, I did something very similar (though I didn't know of the __EMBEDDED_PROFILE__ flag, I just did -D of my own flag in the clBuildProgram call). However, doing this, we still need a target flag for enabling cles_khr_int64 (if we want to support that feature).

The main reason I went with the target flag approach is I think if we fully robust-ified everything in the Halide OpenCL backend, it should be such that if you successfully build the Halide program, OpenCL runtime compiler errors would not occur. This requires knowing we're targeting embedded at Halide compile time, in order to catch things like uses of int64 when it isn't available. This isn't actually implemented now, but the target flag approach at least enables this in the future.

Also, I just generally want to try to avoid relying on the fact that we are actually JITing OpenCL kernels at runtime. Admittedly, we are already doing this (e.g. for deciding to use __constant memory based on how much constant memory is available), but I consider that a hack that we probably won't be able to use long term. Note that there is currently a disparity between OpenCL and CUDA related to this right now, because without the ability to determine how much constant memory there is at compile time, we can't generate code that uses it, and LLVM/PTX doesn't have a preprocessor that we can use to deal with this at run time.

**Comment by jrprice** [comment]
> I think the embedded profile is a subset of the full profile, so enabling cl_embedded shouldn't preclude the code from running on full profile devices.

Well, if I ask for `opencl-cl_embedded-cl_int64`, this will try to enable the `cles_khr_int64` extension, which doesn't exist on the full profile platforms and will therefore fail to compile (some platforms ignore the invalid extension, but others do produce build errors).

I see your point about not relying on JIT compilation in general though. Could we perhaps just guard the inclusion of the `cles_khr_int64` extension with an `#if __EMBEDDED_PROFILE__` then, to ensure that using the `cl_embedded` target *won't* break things for full-profile devices?

> This requires knowing we're targeting embedded at Halide compile time, in order to catch things like uses of int64 when it isn't available.

Is this actually possible? At Halide (AOT) compile time, you can't possibly know whether the device(s) you're targeting will support int64 if the user has asked for embedded profile, since the extension is optional.

**Comment by dsharletg** [comment]
> I see your point about not relying on JIT compilation in general though. Could we perhaps just guard the inclusion of the cles_khr_int64 extension with an #if __EMBEDDED_PROFILE__ then, to ensure that using the cl_embedded target won't break things for full-profile devices?

Good catch, I'll do that.

> Is this actually possible? At Halide (AOT) compile time, you can't possibly know whether the device(s) you're targeting will support int64 if the user has asked for embedded profile, since the extension is optional.

If the target has `cl_embedded` but not `cl_int64`, then ideally, Halide would emit an error if the code attempts to use int64 in an OpenCL kernel. 

The idea is that if the user wants to use int64, with `cl_embedded`, then the user would need to use cl_int64, which would turn on the extension. This would enable Halide to allow int64 to be used in the generated OpenCL code. At runtime, if the device is embedded, and does not support `cles_khr_int64`, the error would *hopefully* be that the extension was requested and not found (instead of a bunch of compiler errors about int64 not being a type, and the cascade of errors that follows).

**Comment by zvookin** [comment]
I already flag 64-but isn't use in JavaScript and Metal, neither of which
have that support. There is a call in Target.h to determine whether a
target support a specific Type and the tests use this for int64_t/uint64_t.
64-bit float would be another candidate for optional support...

-Z-

**Comment by zvookin** [comment]
Can you update the usage message around line 178 of Target.cpp? I don't see this in the diff.

**Comment by zvookin** [comment]
Actually looks like the usage message is stale in other ways and we really ought to move to generating the message automatically from the list...

**Comment by zvookin** [comment]
(Gonna fix the target mapping logic now because I just have to.)

**Comment by dsharletg** [comment]
Pretty much by coincidence, #948 eliminates the need for these target flags, at least for now. I'm going to close this PR but I'll keep it around for when we want to handle the embedded target properly.

**Pull request closed without merging**
