### PR TITLE
Fix hvx lock/unlock semantics for PR #6457

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Review by dsharletg — APPROVED** [review]

**Comment by steven-johnson** [comment]
(I see you already approved the draft, but I just did some cleanup and commenting; PTAL)

**Comment by steven-johnson** [comment]
Everything appears to pass for me locally, merging

**Comment by dsharletg** [comment]
Yes, it still looks good. This is a much nicer smaller change.

**Comment by pranavb-ca** [comment]
I checked and I think we can remove the use of qurt_hvx_lock. I'll open a PR for this once i am back in the office

**Pull request merged**
