### PR TITLE
Require C++11 and LLVM3.5+ (Issue #741)

### PR DESCRIPTION
**Pull request by steven-johnson**
Remove all ifdef’s that conditionalize C++11 usage; remove all makefile
directives that conditionalize C++11 features. Remove makfile code for
supporting LLVM prior to 3.5.

### CODE REVIEW

**Comment by abadams** [comment]
Probably want to also change the very old version-testing code that determines CLANG_OK and LLVM_OK near the end of the makefile.

**Comment by steven-johnson** [comment]
What's our minimum Clang now?

**Comment by abadams** [comment]
It's just for compiling the runtime, so <3.5 *might* work, but best to peg
it to the minimum llvm version.

**Comment by steven-johnson** [comment]
Should we land this?

**Pull request merged**
