### PR TITLE
Unify common cast helper functions

### PR DESCRIPTION
**Pull request by abadams**
People seem to like to write helpers to do casts more concisely. E.g. cast(UInt(8), foo) -> u8(foo). This is especially convenient for codegen patterns, which use lots of casts inline, and for saturating casts, which are otherwise very verbose (and tricky to get right). 

The precise nesting and sequencing of the casts and the other basic numeric operations (+, *, min, etc) are also important to express tersely when you're writing fixed-point code. It's often only clear that code doesn't overflow yet still generates good machine code if the cast is right there in the middle of the expression. Otherwise you have to think about bounds of things across multiple lines of code.

Unfortunately, these helpers get re-declared with slightly different names all over the place. Nobody wants to put them in the global namespace, because they're too short. This PR dumps them in a namespace ConciseCasts, which you can import via "using namespace ConciseCasts"

I just went with the most common choice I saw for naming: u8(foo) and u8c(foo) for the clamping/saturating variant. Other opinions on naming welcome. Keep in mind though that if it isn't significantly shorter than cast<uint8_t>(foo) then people may just continue writing their own helpers.

### CODE REVIEW

**Comment by abadams** [comment]
Updated for hexagon. PTAL.

**Comment by abadams** [comment]
TODO: using "sat" instead of "c" as a suffix is much clearer.

**Comment by dsharletg** [comment]
Looks good to me, I like this. I've wanted this for a while, I've written this same functions many times. +1 to sat instead of c.

**Comment by zvookin** [comment]
I would like to change e.g. "u8c" to "u8_sat" as I feel the difference between a saturating case and the bit preserving one is very large and one character is too subtle. (Also I think there are a few competing conventions for which character to use -- 'c' 'q' 's'.) Outside of this, I wish there are a more readable solution but having discussed it with Andrew I agree that there isn't a much better answer and that consolidating the syntax in one place is a good idea.

**Comment by dsharletg** [comment]
I'd prefer it without the underscore (i.e. u8sat). Every character really counts in these functions, I have expressions that are *mostly* widening/narrowing casts, more so than even basic arithmetic ops. I was on the fence even about u8c vs. u8sat because of that (though I do think u8sat is better).

**Comment by abadams** [comment]
We inspected some code, and were unable to find more than one *saturating* narrow per line, so _sat was accepted.

**Comment by dsharletg** [comment]
This LGTM, but it needs resolving (probably HexagonOptimize.cpp).

**Pull request merged**
