### PR TITLE
Add a NoRuntime target feature

### PR DESCRIPTION
**Pull request by abadams**
Prevents inclusion of the runtime in AOT-compiled code.

Uses the same split as JIT does, so inlined math stuff is still included
in every module.

Declarations for the runtime API are provided to codegen by including a
runtime module that contains them as extern declarations (using an
attribute((used)) trick). This same runtime module also simplifies the
similar logic for JITting.

Also added a method to just compile a runtime, and a generator command-
line flag that does that (so any Generator can give you a copy of the
runtime for any target).

The specific bug that this fixes is: If you link two modules with different feature flags that affect the runtime (e.g. with and without AVX, so you can switch at runtime depending on the machine), then one arbitrarily wins the linker fight, so you might end up calling AVX runtime functions from the non-AVX filter.

### CODE REVIEW

**Comment by abadams** [comment]
@zvookin I think the new runtime module prevents the need for copying llvm types between modules (and indeed the tests all pass with that code deleted). Does this look like a reasonable solution to you?

**Comment by dsharletg** [comment]
How does one use this feature with generators? Is the intention that all but one of the generators (and all but one of the presumably minimal target flags for that generator) in a program use the NoRuntime flag? Or all generators use NoRuntime on all of their targets except the minimal target for that platform?

I'm not completely sure I like this solution. I still think it might be better if we just used the minimal target features for the shared runtime (so we don't generate e.g. AVX code), so it doesn't matter which copy of the runtime module wins the linker race. (Even if we go this route, it still looks useful to have the runtime_api module/type copying change). Sorry if I'm forgetting why this was a bad idea...

**Comment by abadams** [comment]
That's not how it works. There's a call compile_standalone_runtime. It is
exposed via the Generator CLI. It emits just the runtime for a given target
as an object file. The idea is that you'd do this for the minimum spec you
want to support, and then compile *all* of your generators with
-no_runtime. See apps/wavelet for an example. I expect there'd be a single
build rule to make the runtime, and it would get cached, which would then
save compile time (and avoid this bug) for every future generator
compilation.

Only one mcpu and mattrs can be used per compiled object, so if you're
compiling avx code, it's impossible to get llvm to not use avx in the
runtime. It has to be a separate object.

**Comment by steven-johnson** [comment]
Got it. The internal Google code that handles multiple fallback targets
will need attention if this lands, but it should be simple.

**Comment by dsharletg** [comment]
I see now that generate_filter_main exposes this, and it's the nexted_externs example that demonstrates what I was looking for.

I still think this is maybe a bit duct-tapey, but I can't think of anything better. LGTM.

**Pull request merged**
