### PR TITLE
GPU fixes for python_bindings/apps/bilateral_grid.py

### PR DESCRIPTION
**Pull request by Infinoid**
Issues #4804, #3082.

### CODE REVIEW

**Comment by Infinoid** [comment]
The script has one additional problem, though I don't know whether I caused it or not.  It looks like the pixels are output in the wrong order.

Here is the output when run on a CPU target:
bilateral_grid


Here is the output when run on a GPU target:
bilateral_grid-gpu

**Comment by steven-johnson** [comment]
Interesting -- does the C++ version of apps/bilateral_grid have the same issue for you?

**Comment by Infinoid** [comment]
No.  The C++ bilateral_grid app output is correct for both CPU and GPU builds.

**Comment by steven-johnson** [comment]
I think it's just missing copy_to_host, try adding:

    # do the actual computation
    bilateral_grid.realize(output_image)
    **output_image.copy_to_host()**

**Comment by Infinoid** [comment]
Yep, that worked.  steven-johnson++

**Comment by Infinoid** [comment]
With that, the script works properly for me in both CPU and GPU mode.

It still breaks if you set `generate` to `True`.  But that's a problem for another PR.

**Pull request merged**
