### PR TITLE
HDF5 I/O file support for Halide Buffers

### PR DESCRIPTION
**Pull request by SanderVocke**
Add a small single-header library for I/O to/from HDF5 files, similar to halide_image_io.h.

PNG, JPG and PGM (supported by halide_image_io.h) can only represent a small subset of buffers Halide can represent internally. HDF5 is a nice file format for storing (sets of) multidimensional arrays of data. It is widely supported (for example in Matlab and Octave).

Having support for storing/loading Buffers from HDF5 files helps in debugging by providing a means do dump, analyze and compare buffers of any dimensionality. There is also no confusion about precision and representing of data types, because the file format can deal with the exact data types Halide supports. And a nice bonus is that multiple buffers (of different types) can go in one file.

This is not 100% ready to merge yet, but I am hoping you can provide some feedback (and your opinion on whether this functionality belongs in Halide).

Usage examples:

```
Buffer<uint16_t> buf1 = (...);
Buffer<float> buf2 = (...);

//Storing HDF5 files
save_hdf5( {"buf1_name_in_file"}, "out.h5", buf1 );
save_hdf5( {"buf1_name_in_file", "buf2_name_in_file"}, "out_both.h5", buf1, buf2 );

//Loading a buffer from an HDF5 file
auto buf2_loaded = load_from_hdf5< Buffer<float> >("out_both.h5", "buf2_name_in_file");

//Assuming that buf2 has all mins set to 0, the contents of re-loaded version (buf2_loaded) are equal to buf2
```

Current status:

- Supports any amount of dimensions
- Supports 8-, 16, 32-, 64-bit (unsigned) int, 32-, 64-bit float and bool.
- Keeps all data intact, but discards strides and mins of buffers (which is the best in my opinion: these things could be stored in as proprietary metadata, but other tools like Octave would ignore them anyway)
- A correctness test is included. 

TODO and problems (please let me know if you have suggestions):

- CMake can find libhdf5, but because it is not trivial to find the (correct) library and include locations for libhdf5 and its C++ bindings manually, it is now off by default in the static Makefile. Any suggestions welcome.
- The Travis CI doesn't seem to have an installation of libhdf5-dev. Builds will probably pass, but the feature is not really tested.

### CODE REVIEW

**Comment by steven-johnson** [comment]
Thanks for the PR. I've never used HDF5, so I need to do a little research to figure out where it fits into the scheme of things. (Is libhdf5 well-supported on Windows and other non-Linuxy systems? That's a hard requirement for anything going into Halide.)

(FYI: we're definitely going to be adding TIFF support to halide_image_io.h soon, which will provide floating-point support. IIUC, there are also well-defined conventions for up-to-5D images in TIFF, via repurposing multipage-TIFF support, though I haven't used that personally.)

**Comment by SanderVocke** [comment]
I don't have a long history with HDF5 either, but it seemed to me like a more general-purpose supplement to the currently supported "image-oriented" data types. The dimensionality of buffers goes up to 32, and you can have any amount of differently-typed buffers in the same file. TIFF is also a step in this direction, but I don't think it's quite as versatile. From a quick round of googling I'm not sure if all tools apply/expect such multi-dim data with exactly the same conventions.

It looks like OSX and major Linux distros have libhdf5 in their repositories, and the HDF5 group maintains releases for Windows 7 and Windows 10. Does that cover the non-Linuxy systems Halide is targeting? I have only tested this PR on Ubuntu so far.

**Comment by abadams** [comment]
I'm not crazy about the idea of adding a huge dependency. It looks like
writing and reading a .mat file at level 5 would be fairly straight-forward
and dependency free (
ftp://data.cresis.ku.edu/data/mat_reader/matfile_format.pdf). Would that
solve your problem? I.e. do you just want a format that you can get into
matlab easily, or do you have other hdf5 tools that you're trying to
interop with?

If .mat files really are as simple as they look, and level-5 will continue
to be supported, we could consider just replacing .tmp files with them.

- Andrew

**Comment by SanderVocke** [comment]
The main reason to do this was to have a file type supported that could hold any Halide buffer - something which wasn't there before. The timing turned out funny, because this problem seems to be (partially) addressed now with upcoming ImageStack and TIFF format support.

But I don't know much about using TIFF or .tmp for 5-or-more-dimensional data, and the .tmp format, I am guessing, is currently only used by ImageStack. So it's not really a dependency, but people still need to get that tool in order to do anything with these files outside of Halide. To me it seemed like a nice bonus that the format can be read and written by other widely used tools as well.

Built-in support for .mat would be a nice alternative, which would definitely scratch the same itch!

**Comment by SanderVocke** [comment]
Would you consider adding a built-in implementation of .mat level 5?

**Comment by abadams** [comment]
Yeah, I think .mat level 5 is the right answer. We can replace .tmp files with them.

**Comment by steven-johnson** [comment]
My main concern is mainly that HDF5 appears to have a pretty substantial library requirement, which could complicate Halide's build-and-test systems; at first glance, it looks like .mat-level-5 will satisfy many (most? all?) of the same use cases and seems simple enough for an inline implementation. Simple is good :-)

(To be fair, TIFF support is going to require libtiff for reading -- unless we decided to restrict ourselves to a very limited subset of acceptable TIFF, which seems like a bad idea -- but libtiff a pretty well-known library at this point.)

**Comment by SanderVocke** [comment]
No worries! Looking forward to .mat, and until then I can use this PR on the side.

**Comment by dsharletg** [comment]
We have .mat now as far as I can tell (support exists in write_debug_image.cpp), do we still plan to merge this at some point?

**Comment by dsharletg** [comment]
(we also have it in halide_image_io.h)

**Comment by abadams** [comment]
Yep, .mat landed.

**Pull request closed without merging**
