### PR TITLE
Expose internal symbols

### PR DESCRIPTION
**Pull request by abadams**
Also made it possible to turn on RTTI outside the Makefile.

These changes are intended to make it possible to use pieces of Halide
in external projects without forking the Halide build.

### CODE REVIEW

**Comment by steven-johnson** [comment]
Can we please try to do this for CMake as well? 

In theory, CMake can do this for Windows as well (though I haven't tried it, so who knows):

https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/

**Comment by abadams** [comment]
I attempted to turn it on for windows, and make the EXPORT macro a no-op. Let's see what happens.

If this works and we like it, I'll remove EXPORT from the codebase.

**Comment by abadams** [comment]
Looks like it's still necessary on global variables, of which we have a small number. Trying again.

**Comment by steven-johnson** [comment]
Would it be feasible/practical to expose API for those globals and deprecate the globals themselves?

**Comment by abadams** [comment]
The two classes are the names of intrinsics (e.g. bitwise_xor), and the magic vars _, _0, _1, etc. The intrinsic names could conceivably be functions, but _() is not something I really want to type.

These are value types, so we could do things like make them static in the header, but that doesn't seem any better than leaving an EXPORT tag on them. Either way you have to remember to tag exposed global vars as something.

**Comment by abadams** [comment]
Finally passing

**Comment by steven-johnson** [comment]
LGTM. 

Question: what would it take to make RTTI-enabled the default (rather than RTTI-disabled)? I presume it's mainly "ensure that LLVM is compiled with RTTI on"; for our own builds, that should be easily doable. So perhaps we should move to that model, and recommend that people who need/want to use a no-RTTI LLVM be required to configure WITH_RTTI appropriately?

**Comment by abadams** [comment]
Given that we require the same settings as LLVM, rather than have a WITH_RTTI flag, we should probably just use llvm-config.

I think I'll change WITH_RTTI to default to whether or not LLVM is configured with it.

**Comment by steven-johnson** [comment]
SGTM

**Comment by abadams** [comment]
ok, pushed a change that defaults RTTI to whatever llvm was compiled with, but also allows turning it off in libHalide even if it was on in llvm

**Comment by steven-johnson** [comment]
> allows turning it off in libHalide even if it was on in llvm

...is that likely to work reliably, other than by sheer luck?

(SGTM though; if this lands, I will offer an update to buildbots that ensures LLVM is built with RRTI, so that future distribs offer a default-RTTI-enabled set of libraries.)

**Comment by abadams** [comment]
I believe so. rtti just adds some extra symbols that you can optionally use for dynamic_cast and typeid. It's safe to ignore them. They go before the start of the vtable.

**Pull request merged**
