### PR TITLE
Simplify HalideGenerator.cmake

### PR DESCRIPTION
**Pull request by steven-johnson**
— Windows case shouldn’t be necessary any more since generators output
static libraries which we can handle genetically
— Simplify Xcode special-casing to be more targeted

### CODE REVIEW

**Comment by steven-johnson** [comment]
(just fired off buildbot test, do not land till then)

**Comment by zvookin** [comment]
LGTM.

**Comment by abadams** [comment]
Did this pass the windows builds?

**Comment by steven-johnson** [comment]
It has not passed the Windows tests -- I'm going to finish getting my local Windows machine set up and debug it there.

**Comment by steven-johnson** [comment]
It is passing for me locally now.

**Pull request merged**
