### PR TITLE
Dependency wrangling part 0/N: standard CMake modules

### PR DESCRIPTION
**Pull request by alexreinking**
I'm resuming the work I started in #7300.

Since I've been helping other projects with their CMake builds, and rewriting some others myself, I've come to disagree with the popular approach of using a `dependencies/` folder with `IMPORTED_GLOBAL` targets. I now prefer to structure dependencies such that they _always_ use `find_package` at the narrowest scope possible. This is a prerequisite for decent FetchContent support, which our users request from time to time (e.g. #7611). It also promotes integration with other package management systems, since it's now much easier to hook the `find_package` calls.

I'm breaking this into smaller PRs for ease of review.

---

In this step, I'm moving the `find_package` calls to standard CMake modules to their best locations. This includes Threads, OpenGL, OpenMP, JPEG, and PNG.

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]

**Comment by steven-johnson** [comment]
Looks like legit build failures

**Comment by alexreinking** [comment]
> Looks like legit build failures

They are... debugging...

**Comment by alexreinking** [comment]
Wheeee -- this is because CMake's `$<TARGET_NAME_IF_EXISTS:PNG::PNG>` generator expression is evaluated in the target environment of the _consuming_ target when in `INTERFACE_LINK_LIBRARIES`. Yet using plain `PNG::PNG` will trigger a lookup in the _linkee's_ target environment. Conditional dynamic scoping... yay... 🙃 I'm opening an issue with upstream.

In the meantime, moving the `find_package(PNG)`/`JPEG` up to the top level should work around this.

**Comment by steven-johnson** [comment]
> The Vulkan failures seem spurious.

Yes, there seem to still be intermittent Vulkan errors, tagging @derek-gerstmann to investigate

**Comment by alexreinking** [comment]
I think this is good to merge now?

**Pull request merged**
