### PR TITLE
establish target=host to be the default, and add Makefile define to o…

### PR DESCRIPTION
**Pull request by ronlieb**
…verride.

allows us to say

make bin/out.png target=host-hvx_128

### CODE REVIEW

**Comment by steven-johnson** [comment]
LGTM. Might make sense to move the TARGET ?= into Makefile.inc and propagate this change elsewhere in apps.

**Comment by abadams** [comment]
HL_TARGET would be the best name, to preserve what the behavior was before the generator upgrade.

**Comment by ronlieb** [comment]
i like both suggestions, let me make the change and push it up shortly. next hour or so.

**Comment by ronlieb** [comment]
resubmitting as new branch

**Pull request closed without merging**
