### PR TITLE
Makefile LLVM static library fix

### PR DESCRIPTION
**Pull request by tbennun**
This PR makes obtaining the paths to the .a files more explicit by using the `--libfiles` flag instead of `--libs`. 

Fixes LLVM static libraries ($(LLVM_STATIC_LIBS)) in Makefile  when shared libraries are also present.

### CODE REVIEW

**Comment by steven-johnson** [comment]
What environment are you using? AFAIK most/all core Halide devs build static libs from scratch and haven't experienced this issue.

**Comment by zvookin** [comment]
My here here is that this is going to write absolute paths for all the libraries into the result. (Rather than filenames that are searched for along the library search path.) Both of these will work the same in a lot of circumstances, but I expect they will also differ in other circumstances. Practice on the Mac already effectively requires rewriting paths in shared libraries at install time, etc.

Generally the only way to get this sort of thing to be reliable is to put in tests for the failure a chance is meant to mitigate. We do not have much test coverage for this sort of thing in Halide, but we should probably start adding this. At the very least the PR should contain a complete description of what did not work well before and what works better after.

**Comment by tbennun** [comment]
@steven-johnson I'm compiling the static libraries from scratch, that's not the problem. The problem is that I also compile the shared libraries as well, and this supersedes the static libraries when simply using the `-l` flags. As far as I understand, the `--libs` flag in llvm-config was not meant to point to specific library files, it always produces `-l` results, regardless of whether there are also shared objects or just static libraries.

**Comment by steven-johnson** [comment]
Buildbots are finally back up! Please sync this to head; then I'll clone for full testing.

**Comment by tbennun** [comment]
@steven-johnson Synced with master. Thanks!

**Comment by steven-johnson** [comment]
Could you (again) sync this to master for testing purposes?

**Comment by tbennun** [comment]
@steven-johnson done.

**Comment by steven-johnson** [comment]
Thanks for the fix -- sorry for the delay in landing!

**Comment by tbennun** [comment]
Sure, thanks for merging 👍

**Pull request merged**
