### PR TITLE
Use mutexes instead of spin locks for GPU runtimes

### PR DESCRIPTION
**Pull request by dsharletg**
I'm going through my stale branches and either making PRs or discarding them. This one seems like an improvement.

### CODE REVIEW

**Comment by steven-johnson** [comment]
Out of curiosity: why were this spinlocks in the first place?

**Comment by dsharletg** [comment]
We didn't have the mutex support in the runtime at the time we first added thread safety to the GPU runtimes :)

**Comment by abadams** [comment]
The way in which this might fail is if it's ever used from a static destructor or constructor on Windows (e.g. in a gpu release call). Could that happen?

**Comment by zvookin** [comment]
We need to make a test case for the Window static constructor/destructor issue and do one of the following:
1) Demonstrate that it does not fail.
2) Come up with a mutex that doesn't have the deadlock issue.
3) Conditionalize the mutex use to Windows
4) Document it as a problem and move on.

Alternatively, we can make the call without the test case and:
1) Merge it as is.
2) Conditionalize to not do this on Windows.
3) Abandon the PR.

**Comment by dsharletg** [comment]
I'm going to just abandon this for now.

**Pull request closed without merging**
