### PR TITLE
Add is_nan_f32 for metal

### PR DESCRIPTION
**Pull request by shoaibkamil**
Apparently nobody's ever used is_nan_f32 from a metal pipeline yet.

### CODE REVIEW

**Comment by abadams** [comment]
This normally goes with is_inf and is_finite

**Comment by zvookin** [comment]
Worth adding a test that makes sure these exist? Or maybe file an issue if that adds too much work.

**Comment by shoaibkamil** [comment]
> Worth adding a test that makes sure these exist? Or maybe file an issue if that adds too much work right now.

Good point.  I modified the existing isnan test to also run on GPU.

**Comment by steven-johnson** [comment]
Since buildmaster is still down, IMHO this is OK to land once you have confident Mac builds/tests in place locally.

**Pull request merged**
