### PR TITLE
Add a convenient data type for representing half precision floating point numbers

### PR DESCRIPTION
**Pull request by delcypher**
This probably needs reworking in some areas but @zvookin encouraged me to submit this PR early so I could get feedback.

This type is intended to be one of the foundations for building Half precision support into Halide's expression language.

@abestephensg Please take a look.

### CODE REVIEW

**Comment by abadams** [comment]
Will review when I get back from siggraph, but a related thing I heard today: Apparently the tegra x1 will support fp16 in cuda, so that could be a test platform once dev boards for that are out. It would also be a 64-bit arm test platform, and an arm-cuda test platform, which would all be nice things to have in the testing matrix.

**Comment by abadams** [comment]
Looks generally good. Some comments:

- Relying on llvm in the implementation gives me pause (because I have dreams of decoupling the llvm-using parts of Halide from the front-end), but this is probably OK. The important thing is llvm is not exposed in the interface.

- We use_this_style for method names, members, etc.

- For static methods that make new things, we use make_zero (e.g. make_one in IROperator.h), not getZero (or get_zero).

- I don't think the literal is a good idea. It doesn't save much typing over using a constructor from a float, and is slightly more confusing (and adds build complexity because of the Halide.h thing).

- I think float16_t is a better name than fp16_t, because it mirrors the relationship between the types in stdint.h and the corresponding Halide types, e.g. uint8_t -> UInt(8), so float16_t -> Float(16)

**Comment by delcypher** [comment]
> Relying on llvm in the implementation gives me pause (because I have dreams of decoupling the llvm-using parts of Halide from the front-end), but this is probably OK. The important thing is llvm is not exposed in the interface.

Sure one day it could be replaced with a different implementation if we really feel the need. Doing it this way initially is much faster though as this implementation of IEEE754 has been heavily tested and is likely correct, whereas if I wrote my own implementation I'd likely get it wrong initially.

> We use_this_style for method names, members, etc.
> For static methods that make new things, we use make_zero (e.g. make_one in IROperator.h), not getZero (or get_zero).

Okay, I'll fix this.

> I think float16_t is a better name than fp16_t, because it mirrors the relationship between the types in stdint.h and the corresponding Halide types, e.g. uint8_t -> UInt(8), so float16_t -> Float(16)

Sure. I'll rename the type.

> I don't think the literal is a good idea. It doesn't save much typing over using a constructor from a float, and is slightly more confusing (and adds build complexity because of the Halide.h thing).

I find the user defined literal operator ``_fp16`` quite convenient. It should make writing halide expressions more concise. @zvookin @abestephensg Thoughts?

The build complexity issue with header files ``Halide.h`` is the best I can do right now. Personally I don't like the way Halide is dealing with header files at all right now. I would much rather the tree was organised in the LLVM style and we just generated the ``Halide.h`` file as a convenience header file that does ``#include "Halide/header_name.h``  for all the relevant header files. To be more specific

* Move all header files into ``include/halide/`` and change all ``#include``s in source files to be like ``#include "halide/Expr.h"`` instead of ``#include "Expr.h``. This means that to actually do an install of halide the include directory in Halide's source tree just needs to be copied into ``/usr/include``. This works because ``#include "halide/Expr.h`` will work from the build tree and would also work from an installed version of Halide.

* Generate a ``halide/Halide.h`` header file that just does ``#include "halide/some_header_file.h`` (rather than just concatenating existing header files) for all the header files. This will also work from the build tree and from an installed copy.

With the above change supporting ``HalfFloatLiteral.h`` is trivial because the header file is publicly exposed and someone who wants to use it just does ``#include "halide/HalfFloatLiteral.h``.

**Comment by abadams** [comment]
Agreed on using the llvm implementation for now.

I'm not really opposed to the user-defined literal because of any changes it might require to the way we ship header files - that was just a side comment, and I don't want to get into an argument over the relative merits of shipping a single header vs a whole tree. I mostly think it's unnecessary complexity to provide two very similar ways to do the same thing: float16_t(3) vs 3_fp16.

**Comment by delcypher** [comment]
@abadams 

> float16_t(3) vs 3_fp16

Your comparison isn't quite right. There is no constructor like that. When constructing a ``float16_t`` you **must specify the rounding mode** unless you pass the raw bits. I.e. what you should be comparing is

``float16_t("0.3", float16_t::RoundingMode::TONEAREST_TIESTOEVEN)`` vs ``0.3_fp16``

As you can see the constructor form is incredibly verbose

**Comment by abadams** [comment]
Is it true that a float can represent any float16 accurately? If so, I see no reason not to have a constructor that just takes a float.

**Comment by abadams** [comment]
(and has a defaulted rounding mode param)

**Comment by delcypher** [comment]
> Is it true that a float can represent any float16 accurately?

Yes but ``float`` can represent more values than ``float16_t`` so you need a rounding mode which is why the float and double constructors look like

```
float16_t(float value, RoundingMode roundingMode);
float16_t(double value, RoundingMode roundingMode);
```

I could add variants of the constructors that throw a fatal error if the conversion is inexact but I really prefer the string variant of the constructor because if you use a float/double literal rounding happens **TWICE**! The first time the C++ compiler decides what rouding to do (e.g. ``float x = 0.1f``) and then the second time ``float16_t`` does rounding. This is why the ``_fp16`` user defined literal operator calls the string constructor for ``float16_t``.

**Comment by delcypher** [comment]
@abadams Okay. I've redone the commits to fix most the issues you mentioned. I've left the ``_fp16`` user defined literal operator in because we haven't resolved this issue yet.

**Comment by abadams** [comment]
Hrm, I see. I think the case in which the double-rounding makes a
difference is if the user specifies something that isn't an exact float,
where the closest exact float is halfway in between two float16 values.
Half the time it goes the wrong way, depending on rounding modes. The
simplest case I can find of it doing the wrong thing is the literal
"1025.49995". Rounding to a float you get 1025.5, then rounding to a
float16 with round-to-even you get 1026, instead of 1025.

Do we care about such cases? That's a pretty adversarial user to write such
a literal in their source code and then complain about the last bit of
their mantissa. Perhaps there are simpler cases I'm not seeing where going
via a float does the wrong thing. Programmatic cases where you print and
parse float16s will go via the string constructor, so we're really just
talking about things that humans type directly into source code. If there
are simpler cases, I'm happy to figure out how to include the literal in
Halide.h, otherwise I don't think it's worth it, and I don't think it's
worth shipping an extra file.

**Comment by delcypher** [comment]
> Do we care about such cases?

I'm not sure if there are enough of them to worry about.

I tried looking for a case that requires less digits after the decimal point. "65455.999" is an example where the same issue occurs (very close to middle of 65440 and 65472). If the literal is written as a double rather than a float then the given example doesn't cause a problem ("65455.999999999999" does). 

There are other things that need looking at that depend on this PR and I don't want this feature to be blocked any longer so for now I'll remove the user defined literal and add constructors that use a default rounding mode.

**Comment by delcypher** [comment]
Okay tests pass. Could you take another look?

**Comment by abadams** [comment]
Looks good except for that one remaining capitalization issue. Nice tests.

**Comment by delcypher** [comment]
> This should be in the style TowardZero (see other enums in the code)

I picked those names originally because I was [trying to mimic the names used in the standard C library](http://www.gnu.org/software/libc/manual/html_mono/libc.html#Rounding) and the numbering too. Given that I'm not really matching the C library anymore changing the names should be fine. I'll do this when I'm at my proper machine.

**Comment by delcypher** [comment]
Okay I've redone the commits with enum names fixed. Just waiting for the tests to pass now.

**Comment by delcypher** [comment]
Linux builds are green :)

**Pull request merged**
