### PR TITLE
Fix compile with TARGET_PTX=OFF

### PR DESCRIPTION
**Pull request by mkbosmans**

### CODE REVIEW

**Comment by ronlieb** [comment]
lgtm

**Comment by zvookin** [comment]
Thank you for the PR. I tagged Steven to review this and I'll open an issue that we should test building without support for various features if they are optional (which theoretically all llvm backends are).

Are you building with the Makefile or cmake? It looks to me like the Makefile will still try to build the cuda version of the mangling test filter and I'd expect that to fail as well.

**Comment by mkbosmans** [comment]
This was with CMake.
I saw that generating cxx_mangling_gpu was protected in test/CMakeLists.txt by `if (TARGET_PTX)`, so I thought the source file should have a conditional around the include too.

**Comment by steven-johnson** [comment]
LGTM

**Pull request merged**
