### PR TITLE
Fix the ability to remote debug the simulator

### PR DESCRIPTION
**Pull request by pranavb-ca**
@dsharletg @ronlieb @dpalermo

### CODE REVIEW

**Comment by dsharletg** [comment]
How does this work? Doesn't the simulator need to be able to run without exiting a few times before actually running the kernel? For example, it's going to try to run initialize_kernels, and after that, it needs to return control to Halide in order to actually execute a kernel. Won't this just attach the debugger when it first tries to run a simulator side function, and never return?

**Comment by pranavb-ca** [comment]
So the simulator will open a port only when you sim->Run(). So in effect you can sort of debug only the kernel and that is a limitation so far. In all other cases, such as initialize_kernels we step 1000 cycles at a time and the debug port doesn't really matter. So the only function that stops and waits for the debugger is "run". After your "quit" from the debugger, this proceeds to completion.

**Comment by dsharletg** [comment]
Ah, I see. I forgot that Message::Run was a specific message to run a kernel!

Can you rebuild the prebuilt? Only hexagon_sim_remote should change.

**Comment by pranavb-ca** [comment]
Done. Updated libhalide_hexagon_host.so.

**Comment by dsharletg** [comment]
Ahh right, not hexagon_sim_remote. Thanks.

**Pull request merged**
