### PR TITLE
More intrinsics -> LLVM assembly for HVX

### PR DESCRIPTION
**Pull request by dsharletg**
Remove more intrinsics that have now-supported standard LLVM equivalents.

### CODE REVIEW

**Comment by dsharletg** [comment]
This has likely been supported for a long time, probably several LLVM versions. I think QC is only interested in supporting trunk-ish LLVM, @dpalermo ?

**Comment by dpalermo** [comment]
Yes, I believe this support was present for at least the previous release of LLVM and likely even one or two more.  LGTM

**Comment by steven-johnson** [comment]
Looks like an HVX failure:

Internal Error at /home/halidenightly/build_bot_new/worker/linux-64-gcc53-testbranch-trunk/halide/src/CodeGen_Hexagon.cpp:2055 triggered by user code at : Condition failed: fn: Function 'halide.hexagon.sub.vh.vh' not found
../halide/Makefile:1865: recipe for target 'quiet_correctness_simd_op_check_hvx' failed
make: *** [quiet_correctness_simd_op_check_hvx] Error 1

**Comment by steven-johnson** [comment]
Looks all green now. Ready to land?

**Pull request merged**
