### PR TITLE
Fix realizing into multiple existing buffers

### PR DESCRIPTION
**Pull request by abadams**
The natural way to realize into multiple existing buffers currently is
to put them in a temporary Realization:

f.realize({im1, im2});

This doesn't do precisely you want (it used to, before the Buffer
change). The Realization constructor makes a copy of those buffer
objects that it can own, so you'll lose any mutation of the metadata
(e.g. device allocations). It's also different to this:

f.realize(im1);

which takes im1 by reference and updates the metadata

This PR adds a new realization-like class that collects an array of
mutable references to existing buffers. It's a temporary type solely
used for passing groups of buffers to realize and infer_input_bounds. It
changes the meaning of

f.realize({im1, im2})

to take im1 and im2 by reference, the way it used to be.

### CODE REVIEW

**Comment by abadams** [comment]
PTAL. 

std::tie didn't seem like the right thing on closer examination. I needed something which erased the types of the buffers, and something constructible from an existing realization too

**Comment by zvookin** [comment]
LGTM.

**Comment by abadams** [comment]
Actually I think I need a different solution to this general issue. Stay tuned. Do not merge.

**Comment by abadams** [comment]
My different solution turned into a nasty swamp of indirection. I made Dillon's suggested fix, and am going to merge this.

**Pull request merged**
