### PR TITLE
CMake linking clean ups

### PR DESCRIPTION
**Pull request by delcypher**
This should help #861 by reducing the linker memory footprint which should make it possible to build the tests under CMake in the memory constrained TravisCI environment.

### CODE REVIEW

**Comment by delcypher** [comment]
Note I've tested this under Linux and OSX. I'm still waiting for the Windows build to finish...

**Comment by abadams** [comment]
lgtm. Note that the cmake build is currently broken due to the last commit. Dillon was on it, but was called away to a meeting. It's just a missing -I. Feel free to fix if it's trivial.

**Comment by abadams** [comment]
(and yes, running travis on each PR would have caught this)

**Comment by dsharletg** [comment]
I just pushed the fix I had started before I left.

**Comment by delcypher** [comment]
Thanks. merging.

**Pull request merged**
