### PR TITLE
Output image max

### PR DESCRIPTION
**Pull request by dsharletg**
I'm finding myself computing the max of an ImageParam very frequently, this helper function would be nice. There's already `right`, `bottom` that do the same thing, but only for the first two dimensions.

### CODE REVIEW

**Comment by steven-johnson** [comment]
LGTM

**Comment by abadams** [comment]
How about adding a matching method to Image?

**Comment by zvookin** [comment]
What is the use case? There are a lot of anti-patterns around this. E.g. "clamp(x, im.min(0), im.max(0))" is an antipattern. As is RDom r(im.min(0), im.max(0)).

There are also lot of min/max things now. std::min/max, min/max(Expr, Expr), minimum/maximum. I'd propose naming this "limit" instead of "max," but I think "dim_min"/"dim_max" might be good as well. This implies renaming the min field of buffer_t, which we should consider as well.

I've said this before, but I'd like dimensions to have an actual data structure that is the same one used for RDom with a good interface for doing range math. The big opportunity is to make this a first class type so ranges can be passed as inputs and outputs.

**Comment by dsharletg** [comment]
It's exactly the two cases you pointed out, but, only on a subset of the ImageParam dimensions, so I can't simply use BoundaryConditions or RDom's constructor. I'm working with tiled ImageParams where my four dimensions are (x, y, tx, ty). I often want a boundary condition or an RDom over only the first two or last two dimensions. If you have another way around this, I'm all ears.

Aside from all that, I don't see why it is so surprising that we should have a 'max' along side 'min'. I'm not against adding a Range or some other type to support them more directly, but even with all that, having a max method still makes sense IMO.

**Comment by zvookin** [comment]
There is a larger problem in that if you construct the boundary condition
by hand you don't get the likely support and it affects performance. So we
need to figure that out anyway. Perhaps a version of boundary conditions
that takes a list of dimension specifiers to bound is the right thing.

It isn't surprising that max is being added to mirror min, however the min
name likely should not have been used in the first place. Languages become
complex and confusing one logical decision at a time and I'm pushing back
on the overall design. Especially since this is syntactic sugar to make the
code easier to understand. I feel the overloading of the naming min/max
requires to high a degree of context awareness anyway.

**Comment by dsharletg** [comment]
Looking closer at my code here, I can't use the boundary conditions namespace anyways. I need to bound an expression, and then use it further before using it to index a Func/ImageParam, so I can't see ever not needing to explicitly compute the max. I don't think this is the one and only time this will happen either, we shouldn't assume that people can and will *always* use BoundaryConditions or a directly constructed RDom.

**Comment by abadams** [comment]
Naming aside, Zalman calls referring to the min and max of an imageparam directly an antipattern because it breaks using the pipeline as an extern stage in the case where that imageparam is provided by some Func in the outer pipeline. Bounds inference in the outer pipeline asks the inner pipeline "how large should this input be", and the pipeline says "lol idc there's a boundary condition", and so the outer pipeline evaluates and provides it over a 1x1 box and the user gets very confused. If the location of the boundaries is instead passed through as more meaningful Exprs you don't get this problem. 

While that concerns me, I'm putting that aside, because in the common cases it's very natural to refer to the bounds of an Image.

I don't think min/extent/max are an unreasonable names to use consistently if the context is clear. I'm not sure that's really true in this case though. Perhaps they should be deprecated in favor of a ImageParam::dim(int) method that returns something with a min(), max(), and extent() method - that makes the integer argument considerably less mysterious: input.dim(2).max() reads better than input.max(2). This will likely mirror buffer_t's future interface too: (buf.dim[3].min). 

Do people like that suggestion? If so it can come in as part of halide_buffer_t.

**Comment by zvookin** [comment]
I like this. We can also add overloads on the clamp and BoundaryConditions
functions to take the range type directly. Methods such as inset/outset,
intersection, and union on ranges are really good for making code clearer
as well. A sense that there is a better design, such as Andrew's proposal,
is the main reason I pushed back in the first place.

**Comment by dsharletg** [comment]
Superceded by #1001

**Pull request closed without merging**
