### PR TITLE
Prefer calling count() and treating result as bool to find() == end()

### PR DESCRIPTION
**Pull request by abadams**
For std::map, map.count(foo) just inlines to (map.find(foo) == map.end()
? 0 : 1), so the assembly is identical. This is purely a stylistic
choice that I'm raising for discussion because Steven brought it up as
being clearer in one context in another PR.

Opinions? Is this clearer on average? It's certainly fewer characters.
I'm leaning towards yes.

### CODE REVIEW

**Comment by steven-johnson** [comment]
My nit is that it's better to explicitly add `> 0` or `== 0` everywhere to make it clearer that we have a bool result that's being evaluated; I know it shouldn't make any difference to codegen either way. (I won't go to war over this, but am in the habit of preferring actual bool expressions for `if`, etc conditions)

**Comment by steven-johnson** [comment]
(But LGTM)

**Comment by steven-johnson** [comment]
Do we want to land this? (No urgency but would be good to decide)

**Comment by abadams** [comment]
I'm dithering on if I want to defend treating count as a bool or whether I agree with you. I wish std::map had a contains() method.

**Comment by steven-johnson** [comment]
> I wish std::map had a contains() method.

...it does in C++20 :-)

(Side note: does clang-tidy have a mode for "enforce that all ifs use boolean conditions rather than implicit int checks"? Would be interesting to know just how frequently we already fail that.)

**Comment by abadams** [comment]
We convert from pointers to bool everywhere:

```
if (const LT *op = foo.as<LT>()) {
}
```

**Comment by steven-johnson** [comment]
Ouch. OK, problem solved.

**Comment by steven-johnson** [comment]
Did we ever decide if this change was worthwhile?

**Comment by abadams** [comment]
I don't think it's important and have no strong feelings one way or the other. I'll just close it.

**Pull request closed without merging**
