### PR TITLE
Change get_device_interface_for_device_api so it does not require target

### PR DESCRIPTION
**Pull request by zvookin**
passed in to contain the GPU API being requested. Only uses the
passed in target to resolve the default GPU API and to get the debug
flag now.

### CODE REVIEW

**Comment by zvookin** [comment]
Alternative to https://github.com/halide/Halide/pull/2353 and https://github.com/halide/Halide/pull/2385 .

**Comment by ronen** [comment]
At first glance looks good to me, for `device_wrap_native`.  Better than #2385 (of course!) and I suppose better than #2353.

This does leave some lingering differences in edge behavior `device_wrap_native` vs. `copy_to_device` & `device_malloc`, and the semantics of when & how the `target` parameter gets used seems obscure:

param `DeviceApi d` | param `Target t` | env `HL_JIT_TARGET` | | `device_wrap_native` | `copy_to_device` & `device_malloc`
------- | ------ | ----- | - | ---- | ---- |
`Default_GPU` | *unset* | `e` | | *ERROR* | *uses `e`*
`d` | *unset* | `e` | |  *uses `d`, ignores `e`* | *uses `d`, ignores `e` except for `Debug` feature*
`Default_GPU` | `t` | *ignored* | | *N/A* | *uses `t`*
`d` | `t` | *ignored* | | *N/A* | *uses `d`, ignores `t` except for `Debug` feature*

Also this leaves no way to set `Debug` for `device_wrap_native`.    

But, taking a step back, what is the reason for being able to pass a DeviceAPI at all?  I'd expect that the common case is that if the client is using a GPU, the target (whether explicit parameter or from env) will have that device feature set.    So in the common case should suffice for the client to provide that target to the device methods, indeed `device_malloc` and `copy_to_device` have signatures that take the target and no DeviceAPI.   The only reason for the client to ever need to explicitly specify a DeviceAPI would be in multi-device settings, where the target might have multiple device features set, so you'd need to disambiguate, no?

So I think my PR #2353 started the discussion going in the wrong direction.  I think the right way to fix the breaking opengl test is to be able to change:

```cpp
    out2.device_wrap_native(DeviceAPI::GLSL, texture_id);
```
to
```cpp
    out2.device_wrap_native(target, texture_id);
```
I.e. add a new overloaded method to `device_wrap_native` that takes the target.  Yes, this would create new API which will be hard to take away, but again this follows precedent, and would be cleaner and DRYer from the client's perspective, and obviates the need for most people to learn about the `DeviceAPI` data type.  Plus it would pick up `Debug` and other features on the target.  As such, see new PR #2391.

Getting back to this PR:  On one hand, it may seem reasonable that if you request a DeviceAPI you should get it regardless of any target or environment.  But on the other hand, when would you ever want to specify a DeviceAPI that *isn't* in your target?    So I'm thinking that this PR may actually be getting it backwards, and rather than synthesizing a target, what should be done is to verify that the passed DeviceAPI *is* in the target, and raise a user error if it isn't.  And from that perspective, actually #2353 is still relevant for the multi-device cases.

**Comment by zvookin** [comment]
I need to track down the failures for this. I'm not entirely surprised this change is surfacing some bugs in the underlying caching of the runtime modules.

That said, proposing passing the target is a complete non-starter. There can be multiple GPUs specified in the target and there is no indication as to which one to use. Halide is trying to do two things:
    1) Make it possible to write code that can generically run on any one GPU API that meets certain requirements
    2) Provide a general model in which a graph of computations can be mapped to many different pieces of hardware, including CPUs, multiple GPU APIs, etc.

In the first case, one writes `Default_GPU` and lets the target determine what that actually means. In the second case, at least when one is using more than one GPU API, one never wants to write `Default_GPU`. There is some mixing of these use cases in the tests, which is perhaps not a good idea. (E.g. the code in gpu_jit_explicit_copy_to_device.cpp ends up testing the default GPU API twice if it is cuda or opencl. This isn't a problem per se, but if it were intentional, I'd expect a comment.)

The `device_wrap_native` call is special in that the `handle` argument is from a specific GPU API. It is either a `cl_mem` type or an OpenGL texture ID or whatever. The C++ code around the `device_wrap_native` call had to explicitly handle the GPU API handle type. In as much as any abstraction is provided to support more than one GPU API transparently, that abstraction can be carried through to wrapping the handle into a Halide buffer. As such it pretty much *never* makes sense to pass `Default_GPU` to `device_wrap_native`. (And it will most often be a bug to do so as changing the target will cause the code to crash unless someone very carefully allocated the right thing by looking at the target in the first place.)

One could argue that we should pass the device interface as we do with the lower level runtime API. This typically requires an AOT runtime. One includes the GPU API specific header (e.g. `HalideRuntimeCuda.h`) and then calls a routine exported from that header (e.g. `halide_cuda_device_interface`) to get the device interface. This is problematic for JIT as we can't export the name `halide_cuda_device_interface` from libHalide.a and the runtime both. The app may not have a runtime until the first JIT, etc. The buffer interface is working to make a bunch of problems of this sort go away for JIT use cases.

Also explicitly passing the device interface kind of breaks the `Default_GPU` use case unless we add a way to get the default device interface. Likely direction would be to require calling get_device_interface_for_device_api explicitly before using all of these APIs. This has some efficiency advantages actually, but it seems a lot more wordy and inconvenient. I vaguely recall a conversation with Andrew in which we discussed this and decided to make the API a bit simpler.

**Comment by abadams** [comment]
DeviceAPI is supposed to be the front-end language equivalent to halide_device_interface_t *.

I think there are lots of ways to slice this. So far my preferred improvement to the current situation is #2353 plus an assertion that the device api is supported by the given target and that it's not DefaultGPU. If you're passing an opaque uint64_t I think you should have to explicitly declare what sort of beast it is. I think that's the least surprising fix, given the way the related functions work.

**Comment by zvookin** [comment]
This PR had two advantages over https://github.com/halide/Halide/pull/2353 . First it did not make an API change and second it was stricter in a couple ways I felt prevent bugs.

However at least one way in which it was stricter resulted in breaking behavior. (Code can use get_device_interface_for_device_api to detect if a DeviceAPI is available, thus changing that routine to assert that the target supports the DeviceAPI or automatically inserting it into the target changes behavior that is used for something. Note that the current behavior for requesting a DeviceAPI that isn't in the target results in an assert that the device_interface is non-null in HalideBuffer.h failing, which is hardly ideal.)

Avoiding changing the API forces some code to still read an environment variable, which is at least as unpleasant as the overspecification of information in the new API.

**Pull request closed without merging**
