### PR TITLE
Simplifications for unrolling sliding window

### PR DESCRIPTION
**Pull request by abadams**
Unrolling happens after sliding but before partitioning, so the extents of the unrolled loop are complex, but should have an upper bound that enables unrolling. It can be hard for the compiler to see this through all the selects. 

This PR makes things way more aggressive in the about-to-fail case in unrolling. It now exhaustively substitutes in everything for maximally aggressive simplification, and there are a bunch of new simplifier rules to help cancel things through select nodes. This exhaustive substitution is somewhat dangerous, but this is a case where the compiler is about to throw an error if it doesn't simplify down to almost a constant.

### CODE REVIEW

**Comment by steven-johnson** [comment]
This PR LGTM, but applying it to the original source where I found this bug still fails with a 'can't unroll over constant extent'... but now the Expr for the non-constant-extent is much much much more complex. :-(

**Comment by abadams** [comment]
I plugged your monster Expr into the super-simplifier and it's spitting out more missing rules, so stay tuned.

**Comment by abadams** [comment]
Added some more rules. Please try again.

**Comment by steven-johnson** [comment]
Looks good so far; let me do some more torture testing.

**Comment by steven-johnson** [comment]
OK, looks good.

**Pull request merged**
