### PR TITLE
Add FFT app

### PR DESCRIPTION
**Pull request by dsharletg**
This is a major update to the FFT implementation. Here are a list of the changes:

- Moved to apps folder.
- Added FuncT/ComplexExpr/ComplexFunc to make complex arithmetic easier to express.
- Added some features/options to the FFT, such as enabling the user to pass in a gain to be applied as part of the FFT, and more scheduling options.
- Improved performance:

16x16 c2c: 22.2 -> 25.9 (1.16x)
16x16 r2c: 11.4 -> 17.5 (1.5x)
16x16 c2r: 10.7 -> 14.8 (1.38x)

32x32 c2c: 25.9 -> 27 (1.04x)
32x32 r2c: 17.3 -> 21.7 (1.25x)
32x32 c2r: 15.8 -> 19.5 (1.23x)

All measured in GFLOP/s.

### CODE REVIEW

**Comment by abadams** [comment]
Cool. My two main comments are:

What's with the custom boundary condition helpers? Are the builtin ones not sufficient, or does this code just predate them?

This is all in Google C++ style instead of Halide style (4-space indent, functions_with_underscores, etc).

**Comment by dsharletg** [comment]
> What's with the custom boundary condition helpers? Are the builtin ones not sufficient, or does this code just predate them?

I vaguely remember struggling to use the built-in ones due to not being able to use them with ComplexFunc. Thinking about it now, it seems like it should be fine with some small workarounds.

> This is all in Google C++ style instead of Halide style (4-space indent, functions_with_underscores, etc).

Yeah... I'll see if I can use clang-format or something to make this easier.

**Comment by dsharletg** [comment]
OK, believe I've fixed the style issues. Also, I removed the custom boundary conditions stuff, but it required adding an overload of constant_exterior that I think we should have for bounding Tuple valued functions.

**Comment by ppwwyyxx** [comment]
Hope it's not a bad place to ask this question. I feel confused about how the complex type here is defined and used. And this causes trouble when I'm trying understand the behavior.

I'm using fft2d for convolution of a batch of images (as in neural network), and I'm seeing the multiplication of `ComplexFunc` in frequency domain is the bottleneck. From the implementation of `ComplexExpr`, it seems to me that the real/imag part of each complex number are not stored together in memory when I'm doing the multiplication. Is that correct?

**Comment by dsharletg** [comment]
That's correct, `ComplexFunc` and `ComplexExpr` are just syntactic sugar for `Tuple`s in Halide. When a Tuple valued `Func` is realized, each `Tuple` element is stored in a separate buffer.

This is usually the best way to represent complex values (real and imaginary parts stored in separate buffers) because no SIMD shuffling/reordering is required to implement complex multiplication.

Can you clarify, are you actually using this specific FFT code, and you are seeing performance suffer due to multiplication in the DFT domain? This might be due to a problematic schedule of the code between the FFTs. Scheduling code between/around the FFT can be a bit tricky. If you are processing a batch of images, you'll want something like this:

    Var x, y, i; // i is the batch index.
    ComplexFunc dft_in = fft2d_r2c(in, ...);
    ComplexFunc dft_kernel = fft2d_r2c(kernel, ...);

    ComplexFunc dft_result("dft_result");
    dft_result(x, y, i) = dft_in(x, y, i) * dft_kernel(x, y, i);

    Func result = fft2d_c2r(dft_result, ...);

    // Schedule everything to be computed at each output FFT:
    dft_in.compute_at(result, i);
    dft_kernel.compute_at(result, i);
    dft_result.compute_at(result, i).vectorize(x, target.natural_vector_size<float>());

There's also the `schedule_input` option of Fft2dDesc. If you set that to true for the inverse FFT, then the schedule for dft_result would look like this:

    // The inverse FFT already computed dft_result at an internal stage, we just need to vectorize it.
    dft_result.vectorize(x, target.natural_vector_size<float>());

**Comment by ppwwyyxx** [comment]
Thanks a lot for these details! I'm using this FFT code but what I'm doing is a bit more complicated, where the multiplication is performed on a reduction domain:
```cpp
int N = 64, Cin = 128, Cout = 128, H = 64, W = 64;
Var x, y, z, n;
Image<float> img(W, H, Cin, N), kernel(W, H, Cin, Cout);
ComplexFunc dft_img = fft2d_r2c(make_real_4d(img), W, H, target);
ComplexFunc dft_kernel = fft2d_r2c(make_real_4d(kernel), W, H, target);

ComplexFunc cgemm{"cgemm"};
RDom rv(0, Cin, "rv");
cgemm(x, y, z, n) = ComplexExpr{0,0};
cgemm(x, y, z, n) += dft_img(x, y, rv.x, n) * dft_kernel(x, y, rv.x, z);
Func result = fft2d_c2r(cgemm, W, H, target);
```
In this case, scheduling `cgemm` inside `result` always hurt performance and I don't understand why. So I just did `cgemm.compute_root()` and some reordering, then saw it becoming the bottleneck.

**Comment by dsharletg** [comment]
I think the best "simple" schedule for something like this would be something like the following:

    cgemm.compute_at(result, n);
    cgemm.update(0).reorder(x, y, z, rv.x, n).vectorize(x, target.natural_vector_size<float>());
    dft_kernel.compute_root();
    dft_img.compute_at(cgemm, rv.x);

I didn't test it, so it might be wrong. The idea is to compute the DFT of each image, multiply that with a column of the kernels, and add it to the matrix product. This means we can compute the DFT of each image in the inner loop, but the kernels need to be computed at root. The matrix product itself can be computed at columns of the output.

There's probably something better that could be adapted from a proper GEMM schedule though.

**Comment by ppwwyyxx** [comment]
I did have something similar in mind, then I just found out the reason I didn't get benefits from scheduling `cgemm` inside `result` is this line I had:
```cpp
cgemm.bound(x, 0, W).bound(y, 0, H/2+1).bound(z,0,Cout).bound(n,0,N); // it hurts
```
I thought adding a bound never hurts. But seems like "compute-by-need" doesn't work well with a static bound.
Thanks a lot for your suggestions! I'll explore more on what I can do.

**Pull request merged**
