### PR TITLE
Reorder vectorization and fuse gpu thread loops

### LINKED ISSUE #3061: Incorrect output for OpenCL target
The same code sample works differently before and after a PR https://github.com/halide/Halide/pull/2526

```cpp
#include <Halide.h>

int main(int argc, char** argv)
{
    // Fill input buffer.
    Halide::Buffer<float> input(2, 2, 3);
    Halide::Buffer<float> output(2, 2, 3);
    float* inputData = (float*)input.raw_buffer()->host;
    for (int i = 0; i < 12; ++i)
        inputData[i] = i;
    input.set_host_dirty();

    // Define a function.
    Halide::Var x("x"), y("y"), c("c"), xo("xo"), xi("xi"), yo("yo"), yi("yi"), co("co"), ci("ci"), n("n");
    Halide::Func func("func");
    Halide::RDom r(0, 1, 0, 1);
    func(x, y, c) = sum(input(x + r.x, y + r.y, c));

    // Schedule.
    func.bound(x, 0, 2).bound(y, 0, 2).bound(c, 0, 3)
        .split(x, xo, xi, 2).split(y, yo, yi, 2).split(c, co, ci, 3)
        .gpu_blocks(xo, yo, co)
        .gpu_threads(xi, yi)
        .reorder(xi, yi, ci, xo, yo, co)
        .vectorize(ci);
    func.print_loop_nest();

    // Compile.
    Halide::Target t = Halide::get_host_target();
    t.set_feature(Halide::Target::OpenCL);
    func.compile_jit(t);

    // Execute.
    func.realize(output);

    // Print output.
    output.copy_to_host();

    float* outputData = (float*)output.raw_buffer()->host;
    for (int i = 0; i < 12; ++i)
        std::cout << inputData[i] << " " << outputData[i] << std::endl;

    return 0;
}
```

Using Halide from a commit 8d428e013718a2b7eef955059b70258053018dff:
```
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
```

However with a commit 59bca3c8e535f7f99c90efd1d932db934f9c01b6:
```
0 8
1 9
2 10
3 11
4 8
5 9
6 10
7 11
8 8
9 9
10 10
11 11
```

A function without `Halide::RDom` works fine.
```cpp
func(x, y, c) = input(x, y, c);
```
GPU:
```
  Platform Name                                   Intel(R) OpenCL
Number of devices                                 2
  Device Name                                     Intel(R) HD Graphics
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0 
  Driver Version                                  r5.0.63503
```

### PR DESCRIPTION
**Pull request by abadams**
In an attempt to fix #3061 

Let's see if the buildbots like this.

### CODE REVIEW

**Comment by abadams** [comment]
Thanks, it would be bad to merge it if it causes performance regressions. There are other ways to fix the underlying issue, this was just the simplest one.

**Comment by dkurt** [comment]
@abadams, In example, the same accuracy reproducer but with bigger sizes:

```
#include <Halide.h>
#include <sys/time.h>

int main(int argc, char** argv)
{
    // Fill input buffer.
    Halide::Buffer<float> input(200, 200, 64);
    Halide::Buffer<float> output(200, 200, 64);
    float* inputData = (float*)input.raw_buffer()->host;
    for (int i = 0; i < 200*200*64; ++i)
        inputData[i] = i;
    input.set_host_dirty();

    // Define a function.
    Halide::Var x("x"), y("y"), c("c"), xo("xo"), xi("xi"), yo("yo"), yi("yi"), co("co"), ci("ci"), n("n");
    Halide::Func func("func");
    Halide::RDom r(0, 1, 0, 1);
    func(x, y, c) = sum(input(x + r.x, y + r.y, c));

    // Schedule.
    func.bound(x, 0, 200).bound(y, 0, 200).bound(c, 0, 64)
        .split(x, xo, xi, 16).split(y, yo, yi, 16).split(c, co, ci, 16)
        .gpu_blocks(xo, yo, co)
        .gpu_threads(xi, yi)
        .reorder(xi, yi, ci, xo, yo, co)
        .vectorize(ci);
    func.print_loop_nest();

    // Compile.
    Halide::Target t = Halide::get_host_target();
    t.set_feature(Halide::Target::OpenCL);
    func.compile_jit(t);

    // Execute.
    func.realize(output);
    output.device_sync();

    const int numRuns = 100;
    timeval start, end;
    gettimeofday(&start, 0);
    for (int i = 0; i < numRuns; ++i)
    {
        func.realize(output);
        output.device_sync();
    }
    gettimeofday(&end, 0);
    std::cout << ((end.tv_sec - start.tv_sec) * 1e+3 + (end.tv_usec - start.tv_usec) * 1e-3) / numRuns << '\n';

    return 0;
}
```

before: 1.14654ms
with a current PR: 2.04331ms

LLVM version 6.0.0
```
  Platform Name                                   Intel(R) OpenCL
Number of devices                                 2
  Device Name                                     Intel(R) HD Graphics
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0 
  Driver Version                                  r5.0.63503
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               24
  Max clock frequency                             1150MHz
```

```
$ sudo cat /sys/kernel/debug/dri/0/i915_min_freq
1150
```
```
$ sudo cat /sys/kernel/debug/dri/0/i915_max_freq
1150
```

**Comment by steven-johnson** [comment]
What's the status of this PR?

**Comment by dkurt** [comment]
@steven-johnson, I'm sorry for delay. I'll try to check an efficiency again.

**Comment by steven-johnson** [comment]
Monday morning ping: what's the status of this PR?

**Comment by dkurt** [comment]
@abadams, I tested 8d428e013718a2b7eef955059b70258053018dff (tag release_2018_02_15) and c19316bab9705de5f6753a155f16d37f77e16f60 (this PR) commits. Unfortunately I cannot reproduce numbers above again. Both version gives the same efficiency now (about 2ms). I remembered that I already faced this thing but I don't remember how it was fixed.

**Comment by steven-johnson** [comment]
This PR has been languishing for a while. Still interesting?

**Comment by abadams** [comment]
Yes, it's still a valid bugfix. I guess I need to merge with master.

**Comment by dkurt** [comment]
@abadams, I think it's OK if you merge it. Thank you!

**Comment by abadams** [comment]
The buildbots really don't like my PRs lately

**Pull request closed without merging**
