### PR TITLE
Fix intentional read-before-write of shared mem allocation

### PR DESCRIPTION
**Pull request by shoaibkamil**
`correctness_gpu_thread_barrier` was intentionally reading shared memory before writing to it; HLSL compilers will complain about the code.  This makes the test just have a pure definition, while still testing that undef stages don't mess up thread barrier behavior.

### CODE REVIEW

**Comment by shoaibkamil** [comment]
Any ideas on how to replicate this build failure?  It doesn't occur on my Windows machine with LLVM 10.0.1 built from source.

**Comment by steven-johnson** [comment]
Not offhand, no. I don't even have a local Windows machine. If you want to log into the windows buildbot and try it there, please do :-)

**Comment by steven-johnson** [comment]
Alex's suggested change makes no difference when I applied it manually on the windows buildbot. I'm gonna try a git bisect.

**Comment by alexreinking** [comment]
> Alex's suggested change makes no difference when I applied it manually on the windows buildbot. I'm gonna try a git bisect.

That's actually a good thing.

**Comment by alexreinking** [comment]
@shoaibkamil please be sure to revert the `-g` change I suggested before merging.

**Comment by shoaibkamil** [comment]
Closed in favor of #5003.

**Pull request closed without merging**
