### PR TITLE
Use bound_correlated_differences in find_constant_bounds

### LINKED ISSUE #6044: Bounds Inference problem for sliding over guard with if
Hello
Here is my algorithm
`output(x, y) = input(x, y) + input(x, y + 1) + input(x, y + 2) + input(x, y + 3) + input(x, y + 4);
`

I tried the following schedule in Generator

    add_requirement(output.dim(0).extent() > 0);    
    add_requirement(output.dim(1).extent() > 0);   
  
    output.compute_root()      
      .bound(x, 0, output.width())    
      .bound(y, 0, output.height())  
      .split(y, y, yo, 8, TailStrategy::GuardWithIf)  
      .split(yo, yo, yoo, 2, TailStrategy::GuardWithIf)  
      .unroll(yo)
      .unroll(yoo)
      ;

    input.in()      
      .compute_at(output, yo)   
      .store_at(output, y)   
      .unroll(_1)   
      ;  
  

In this case, Halide will infer the allocation bounds of input.in() to 8.
However, if I tried the following schedule,
Halide won't be able to infer the bounds of input.in() to a constant value.
In this case, I think the correct answer should be 8 * 2 = 16.
Thank you

    add_requirement(output.dim(0).extent() > 0);
    add_requirement(output.dim(1).extent() > 0);
    output.compute_root()
        .bound(x, 0, output.width())
        .bound(y, 0, output.height())
        .split(x, x, vx, 2, TailStrategy::RoundUp)
        .split(y, y, yo, 8, TailStrategy::GuardWithIf)
        .split(yo, yo, yoo, 2, TailStrategy::GuardWithIf)
        .unroll(yo)
        .unroll(yoo)
        .vectorize(vx)
        .reorder(vx, yoo, yo, y, x)
        ;
    input.in()
      .compute_at(output, yo)
      .store_at(output, y)
      .unroll(_1)
      .vectorize(_0)
      ;

### PR DESCRIPTION
**Pull request by rootjalex**
This PR is not ready yet (I probably need to add a few explaining comments), this is for running the buildbots and so I can get @abadams (and/or any other eyes) to check out this possible solution to #6044 .

The two rules at the end of the rewrites in `PartiallyCancelDifferences` are the only two I added, and they follow the reduction order and are formally verified. They might be worth adding to the simplifier, but they aren't very general so I'm not sure if it's worth it. Feedback appreciated.

Fixes #6044

### CODE REVIEW

**Comment by steven-johnson** [comment]
Where does this PR stand?

**Comment by rootjalex** [comment]
I need to do a little bit of clean-up + commenting + remove one issue I just noticed. I will try to get to it today or tomorrow

**Comment by rootjalex** [comment]
@steven-johnson any idea why this is breaking here but master is fine? Seems like an LLVM 13 issue (am building locally with LLVM 12 and have no issues)

**Comment by steven-johnson** [comment]
Fix was in https://github.com/halide/Halide/pull/6080, just re-sync to master

**Comment by rootjalex** [comment]
@steven-johnson thanks!

**Comment by steven-johnson** [comment]
Is this ready to review / land?

**Comment by rootjalex** [comment]
It is ready for review

**Comment by abadams** [comment]
I think this was going to be subsumed by your work on find_constant_bounds?

**Comment by abadams** [comment]
Suggested changes:

refactor_correlated_differences -> bound_correlated_differences
move the call into find_constant_bounds

**Review by abadams — APPROVED** [review]

**Pull request merged**
