### PR TITLE
Cloning #3309 for testing

### PR DESCRIPTION
**Pull request by dsharletg**

### CODE REVIEW

**Comment by aankit-ca** [comment]
I guess the histogram example is bound to fail without scatters. Changing the testcase to vectorize the hist update definition only for for hvx_v65.

**Comment by aankit-ca** [comment]
@dsharletg Is it good to merge?

**Comment by pranavb-ca** [comment]
@aankit-ca  - There are conflicts that you should resolve first

**Comment by aankit-ca** [comment]
@pranavb-ca @dsharletg Resolved the conflicts on #3309

**Pull request closed without merging**
