### PR TITLE
Image<> -> Buffer<>

### PR DESCRIPTION
**Pull request by abadams**
This is a jumbo renaming PR to switch usage from Image<T> to Buffer<T>, as discussed in my prior PR. It's all search-and-replace plus some comment fixes, and some more aggressive naming fixes in the python bindings.

I decided to keep Image as an alias for Buffer, to not unnecessarily disturb people using the JIT to produce things that are decidedly images, so this shouldn't affect any actual users.

### CODE REVIEW

**Comment by abadams** [comment]
This changes the look of the language quite a bit for jit usage. I'm inclined to abandon this PR. What do people think? Is it bad to have Halide::Buffer and Halide::Image with them meaning the same thing?

**Comment by dsharletg** [comment]
I think it's a good change. I don't think using Buffer instead of Image even when the thing is obviously an image is a big deal, and I think it's better not to have two names for the same thing. If we resolve the conflicts, I think we should merge this.

**Comment by steven-johnson** [comment]
Agree with Dillon. It's a one-time dislocation but having exact synonyms in the language does no one any favors in the long run.

**Comment by jrk** [comment]
I agree, too, for the same reason. You could also argue that Image was
always a bit of a confusing and off-putting name for people not doing
vanilla image processing. (What about 3D volumes? What about videos? What
about tensors? Do they have to be 2D?)

**Comment by Dr-Emann** [comment]
For the sake of making sure a future searcher could find the prior PR mentioned:

This is a follow up to PR #1481

**Pull request merged**
