### PR TITLE
Bug fix: halide_opengl_detach_texture() doesn't fully detach

### PR DESCRIPTION
**Pull request by ronen**
If you wrap a texture using `halide_opengl_wrap_texture(user_context, &buffer, texture_id)` then after running your filter you detach it using ` halide_opengl_detach_texture(user_context, &buffer)`, you should later be able to attach that same texture again to run another filter.  But attempting to do so caused an error `Error: Internal error: texture 3 is already wrapped.`

In order to fix the bug,  I wanted to follow TDD style:  first create a failing test and then fix it.  Unfortunately, `halide_opengl_wrap_texture()` seems to only be available with AOT compilation, but the `test_opengl` suite was only doing JIT compilation. 

So, this PR includes 3 commits:

* e4fb857 - Modifies the `Makefile` to add the ability to do AOT compilation in the `test_opengl` suite, following the  mechanism used in the `test_generators` suite (A file named `%_generator.cpp` is an AOT-compiled filter generator, and a file named`%_aottest.cpp` is a test that needs to link in an AOT-compiled-filter.)

* 917e699 - Adds a failing test that demonstrates the bug

* 18f08b1 - Fixes the bug, the test now passes.

I could do two separate PRs: one for the Makefile changes, followed by one for the test & bug fix, if you'd rather.  But the Makefile-only PR would be odd in that it wouldn't demonstrate that the Makefile changes work.

Shout out to @shoaibkamil for identifying and tracking down the bug.

### CODE REVIEW

**Comment by ronen** [comment]
Sigh, forgot that building using Make on OS X isn't enough.  Three more commits:

*  81ddfda - include `OpenGL/gl.h` on `__APPLE__` and `GL/gl.h` elsewhere.  (This allows the files to compile on travis-ci.)   

* 8a96f1e - Add the test_opengl AOT mechanism to `CMakeLists.txt`

* eaa46c6 - The cmake build attempts to compile and link everything, although not all tests get run by the build.  Unfortunately the AOT opengl tests require linking against OpenGL, which isn't configured in the travis-ci environment.  So I've added a guard in `CMakeLists.txt` to skip building the opengl AOT tests if OpenGL isn't found, since they won't get run anyway.

The Makefile will also need to have `OPENGL_LD_FLAGS` defined for platforms other than Darwin; I haven't done that since I don't have Linux with OpenGL available for testing.

**Comment by shoaibkamil** [comment]
This does seem to fix the bug, and works for me on Mac OS X.

**Comment by zvookin** [comment]
How much of the hair in the CMake support is just to add AOT support for this test? (As opposed to adding any cmake support for opengl testing. I'm not sure if it was there before at all.)

The reason I ask is because the GPU API specific runtime functions (e.g. halide_opengl_wrap_texture) should work in JIT mode and it may not be too difficult to fix that bug. I'll try to look at that shortly and if it is quick to do, it may be worth going down that route on the tests.

The basic fix of unlinking the texture from the lookaside list even if it isn't a render target one seems correct.

**Comment by ronen** [comment]
> How much of the hair in the CMake support is just to add AOT support for this test? (As opposed to adding any cmake support for opengl testing. I'm not sure if it was there before at all.)

The CMake was already building all the OpenGL tests; the new hair is adding AOT support, copying what was already there for AOT testing of generators.   It's possible that with a bit more thought and CMake mojo it could be cleaner and less repetitive. 

> The reason I ask is because the GPU API specific runtime functions (e.g. halide_opengl_wrap_texture) should work in JIT mode and it may not be too difficult to fix that bug. I'll try to look at that shortly and if it is quick to do, it may be worth going down that route on the tests.

Yeah I agree that it would be good for those functions to work in JIT mode.  Their symbols aren't currently available in `libHalide.{so,a}`, I don't know if it's just a build-and-archive issue or if there's anything deeper preventing them from being used.

And if those functions worked in JIT mode then yeah, the Makefile & CMake stuff wouldn't be needed for this test.

That said, In principle it seems that being able to do AOT tests in OpenGL (or any of the test suites) could be handy in case there are ever some AOT-specific bugs or issues.  I think that with a little more care the Make/CMake mechanisms for AOT tests that's currently specific to `generator/`-- and that I mostly cloned for `opengl/` in this PR--could be made to work consistently in any of the test suite subdirectories.    But that could be a separate issue, and could be left until if/ever the need arises.

**Comment by zvookin** [comment]
Look at src/DeviceInterface.cpp to see why the functions are not available. If you add wrappers similar to halide_opengl_device_interface at the end of that file forthe wrap/unwrap functions, they should become available in JIT mode. We'll need to do this for all the extra GPU API functions. Happy to accept that on this PR if you want to test it now, or it can happen in another PR soon.

**Comment by ronen** [comment]
OK, will do.  I'll force a push here with the AOT stuff gone and with the test done as JIT.    Back soon, hopefully...

**Comment by ronen** [comment]
Much cleaner!  But still one nagging travis/cmake build issue remains...

I modified the Makefile to link the opengl tests with the OpenGL library, since this test makes explicit OpenGL calls (and I've got another one or two coming which will similarly make OpenGL calls).  That works on travis since the `build_travis.sh` script doesn't try to build `test_opengl`

But I haven't (yet) made a corresponding change to `CMakeLists.txt`  to link with OpenGL.  So the `BUILD_SYSTEM=CMAKE` travis test fails because the test can't link.  If I did change `CMakeLists.txt`, it would fail on travis anyway since `find_package(OPENGL)` won't find it.

I *think* the best solution is to add the find_package(OPENGL) to CMakeLists.txt for those who use CMake outside of travis, and and to change the `build_travis.sh` script to skip the OpenGL tests for CMAKE.  

What do you think?

**Comment by zvookin** [comment]
I agree with the proposal to add find_package and to have the script skip
the tests. Alternatively, if find_package fails, the test could be skipped,
but I think the script solution is better.

-Z-

**Comment by ronen** [comment]
> I agree with the proposal to add find_package and to have the script skip
the tests.

OK, will do that.  But probably not til tomorrow.

**Comment by ronen** [comment]
Done:  

* `CMakeLists.txt` now links the opengl tests with the OpenGL library (found using `find_package(OPENGL)` 

* `build_travis.sh` now runs cmake with `-DWITH_TEST_OPENGL=OFF` to skip the opengl tests.

With that, I think this PR should be good to go -- subject to any code review comments and suggestions of course.

**Comment by shoaibkamil** [comment]
I can confirm that the tests work using `make` on Ubuntu 16.04 with Mesa's OpenGL implementation.

**Pull request merged**
