### PR TITLE
Enable parallelism on the Hexagon simulator

### PR DESCRIPTION
**Pull request by dsharletg**
This is an alternative implementation of #1465, which uses the existing thread pool implementation. This PR implements the threading primitives (spawn_thread, mutex, condition variable) required to enable the thread pool.

This branch is not currently working, opening this PR to continue discussion from #1465

### CODE REVIEW

**Comment by pranavb-ca** [comment]
I found one problem. I added a log_printf in halide_spawn_thread and for HL_JIT_TARGET=host-hvx_128 HL_TARGET=host-hvx_128, I see 
creating thread1
creating thread2
creating thread3

**Comment by pranavb-ca** [comment]
Got it. Problem is in qurt_get_hvx_mode in sim_remote.cpp. It returns 64 or 128
not 0 or 1.

**Comment by pranavb-ca** [comment]
Fixing it.

**Comment by dsharletg** [comment]
Ah, good catch! I even thought about that when I was adding qurt_get_hvx_mode, but apparently not hard enough :)

Note that it will still create 4 threads, but only 2 of them should get used when in HVX 128 byte mode.

**Comment by pranavb-ca** [comment]
Worked.
Received archstring from environment=--l2cache_perfect 1
ARCHSTRING set l2cache_perfect = 1
creating thread1
Hexagon simulator executed function 0x27b80 in 6770000 cycles
Hexagon simulator executed function 0x27b80 in 6748000 cycles
Hexagon simulator executed function 0x27b80 in 6747000 cycles
Hexagon simulator executed function 0x27b80 in 6736000 cycles
Hexagon simulator executed function 0x27b80 in 6748000 cycles

**Comment by pranavb-ca** [comment]
The threads try to acquire locks in halide_do_task, i.e they claim a job but they arent able to get a lock. Theoretically there should be a moment of synchrony when a starved thread gets the lock, but may be that took too long making me think that the camera_pipe was hanging.

**Comment by dsharletg** [comment]
I'm still seeing incorrect output from correctness_convolution

**Comment by pranavb-ca** [comment]
Yup, same here. Under diff simulator versions, either convolution or dilate runs incorrectly.

**Comment by dsharletg** [comment]
In general, I'm still continuing to see very unstable/unpredictable behavior from the simulator. I just tried fixing qurt_get_hvx_mode to return 0, 1, or -1 (64B, 128B, or "not available"), and again, new and different failures pop up that appear totally unrelated.

**Comment by pranavb-ca** [comment]
@dsharletg : Are you sure that just locking and unlocking is enough in cond_wait? Everytime I put printfs tests seem to start passing as if to suggest a race condition.

**Comment by kgnk** [comment]
Condition wait can be tricky. If no thread is waiting, the notify goes unnoticed. You have to watch the order of unlocking and notifying or your receiving loop will miss notifications. At the same time, the loop may be notified (spuriously) even though no other thread has notified the condition variable. Coming from Windows' events and semaphores, this was all a bit of a surprise to me.

**Comment by dsharlet** [comment]
The problem I see is not a hang but an incorrect result, so while the cond wait implementation might not be sufficient to avoid hangs (no other threads get a chance to run between unlock and lock), it shouldn't lead to incorrect results if the program does finish.

**Comment by zvookin** [comment]
kgnk's comments on cond_wait belies a deep misunderstanding of the mechanism. The entire point is that it is stateless. Notifications are not stored/rememebered/etc. The original Windows APIs had a plethora of synchronization primitives, all of which made it hard to write code that is free of sleep/wakeup races and in practice these are legion in shipping code because of the inherent flaws in the design.

The fundamental question here is under what circumstances the simulator switches threads. Can someone from Qualcomm answer this? If this can be made to happen inside the part of cond_wait where the mutex is released, this should avoid the livelock (hang) issue. As Dillon points out, the incorrect results seems like another bug, though it could be related if there is some sort of timeout or watchdog error happening due to the livelock.

**Comment by pranavb-ca** [comment]
@zvookin : Each SW thread is bound to a HW thread when running on the simulator (i.e. in the absence of an OS with thread scheduler). The simulator cycles between the HW threads in a round-robin cyclical manner with each HW thread getting a time slice.

**Comment by zvookin** [comment]
Does it literally cycle on every instruction or are there only certain
types instructions on which it will cycle? If it switches on every
instruction, then maybe a small loop, with care to ensure it is not
optimized out, inside cond_wait will be enough to prevent live lock. The
rationale for this is that the other threads are going to proceed in tandem
with the thread calling cond_wait and it would be possible for them all to
line up such that the other threads never win the lock. (Choosing a random
number of loop trips between say 10 and 1000 might be the right first
approach. Accessing some memory location declared volatile would prevent
the loop from getting optimized out.)


On Tue, Aug 30, 2016 at 1:20 PM, Pranav Bhandarkar <notifications@github.com

**Comment by dsharletg** [comment]
What's happening with this one? Any update on the simulator issues we were seeing?

**Comment by ronlieb** [comment]
Its been on hold for quite a while, we are planning to look at  it again after out January 31 release.

It turned out to be far more difficult to get working. Race conditions we ran out of time to work on.

 

Is this becoming more urgent to you?

 

---

Qualcomm Innovation Center, Inc. is a member of Code Aurora Forum, hosted by The Linux Foundation

**Comment by dsharletg** [comment]
It's not any more urgent than it was, I just wanted to check on some stale PRs.

I think that this is worth debugging because I suspect there's a deeper issue that we should understand. It might be a simulator issue.

**Comment by dsharletg** [comment]
Closing this and opening an issue instead.

**Pull request closed without merging**
