### PR TITLE
Allow LLVM targets to run custom bitcode optimization passes.

### PR DESCRIPTION
**Pull request by pranavb-ca**
Presently, only Hexagon, AMDGPU & NVPTX implement the adjustPassManager method of LLVMTargetMachine

### CODE REVIEW

**Comment by zvookin** [comment]
LGTM.

**Comment by zvookin** [comment]
Though it looks like this may need to be conditionalized on the LLVM version.

**Comment by abadams** [comment]
Yeah, this will probably only work with trunk

**Comment by pranavb-ca** [comment]
That's true. I am trying to figure out the first release of LLVM that shipped with this target hook. It is likely a release after 3.7. However, all of this morning llvm.org/docs has been unreachable for me. Once, I am able to determine the earliest release that this was available in I'll push up a change.

**Comment by pranavb-ca** [comment]
@abadams, @zvookin - Good to go?

**Pull request merged**
