### PR TITLE
Remove buggy let visitor in Deinterleaver

### PR DESCRIPTION
**Pull request by abadams**
The Let visitor in Deinterleaver makes some bad assumptions about how the resulting variable is used. If it's used lane-wise it's correct (by far the most common case), but if it gets used inside an inner shuffle it's nonsense. This fixes the repro case in #3353

### CODE REVIEW

**Comment by dsharletg** [comment]
As far as I can tell, this change only does two functional changes: deletes visit(const Let*) and calls substite_in_all_lets prior to running the visitor.

I'd really like to see the functional changes separated from the formatting changes.

**Comment by abadams** [comment]
Sorry, should have just listed the functional changes. I was moving code around and getting confused with the formatting so I just clang-formatted the whole thing. The functional change is that Deinterleaver is now a graph mutator, which meant I could delete the buggy code, but means I need to run substutite_in_all_lets before and CSE after all uses of it.

**Comment by abadams** [comment]
Only failure is unrelated. ptal.

**Comment by steven-johnson** [comment]
> I'd really like to see the functional changes separated from the formatting changes.

+1 -- the new formatting is an improvement but obscures the real changes.

**Comment by abadams** [comment]
Acknowledged, but I don't think it's worth redoing the PR to separate the two classes of change.

**Comment by steven-johnson** [comment]
LGTM

**Pull request merged**
