### PR TITLE
Add addtional needed path for hexagon LD_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by ronlieb**

### CODE REVIEW

**Comment by dsharletg** [comment]
I don't think this is right. LD_LIBRARY_PATH affects the behavior of the host dlopen only, but there are no x86/host binaries in the v60 folder, only Hexagon binaries.

I also don't use this on my command line when running HelloHexagon...

**Comment by ronlieb** [comment]
The issue was that hexagon_sim_remote is not found when following the instructions in the README.md, adding the v60 path allows the LD_LIBRARY_PATH approach to work.
what also works is explicitly setting the evar HL_HEXAGON_SIM_REMOTE

i am happy to document either approach. what is your preference?

**Comment by dsharletg** [comment]
Are you sure that works? I just tried it, and I couldn't get it to work without explicitly setting HL_HEXAGON_SIM_REMOTE.

If it were to work, that means this ConfigureExecutableBinary call uses LD_LIBRARY_PATH to search for the executable?? https://github.com/halide/Halide/blob/master/src/runtime/hexagon_remote/sim_host.cpp#L30

That would be pretty surprising, considering this isn't a shared library, and it isn't a host binary.

BTW, we really need to find a better way to do this. There are too many ugly dependencies on these runtime files.

**Comment by ronlieb** [comment]
yes, i tried that myself, i commented out HL_HEXAGON_SIM_REMOTE and added the v60 path to the existing ones.

**Comment by dsharletg** [comment]
Either this behavior was added since the 8.0.05 version of the Hexagon SDK, or something else is going on. Are you sure you don't have HL_HEXAGON_SIM_REMOTE set in an environment variable (i.e. setting it on the particular command line is redundant)? Does it *not* work if you remove the v60 folder from the LD_LIBRARY_PATH?

**Comment by ronlieb** [comment]
ok, i am seeing strange things going on here.
let me dig into it more, i see things working that should not be when i comment out the v60, so something else is going on here.

**Comment by ronlieb** [comment]
ok, sorry, i had a left over hexagon_sim_remote sitting in my HelloHexagon directory.

i will amend the README.md to use the evar

**Pull request merged**
