### PR TITLE
Fix incorrect deinterleave of a shuffle

### PR DESCRIPTION
**Pull request by abadams**
Bug was introduced by a recent PR

### CODE REVIEW

**Comment by shoaibkamil** [comment]
Yikes.

**Comment by abadams** [comment]
The GHA bots seem to have double-triggered. Perhaps they are also triggered by the approval?

**Comment by steven-johnson** [comment]
yeah, I still haven't figured out what the cause for multi triggering

**Comment by abadams** [comment]
Oh you're right, this dates back to the origin of this code but never triggered. I have a PR somewhere that changes this code but it hasn't been merged yet.

**Comment by steven-johnson** [comment]
So the two presubmit runs are because we are triggering when a PR is "opened" and again when a PR is "review requested". I really need to figure out how to avoid this in general (see https://github.com/halide/Halide/issues/4756). 

AFAICT, there isn't a baked-in tool in GHA to avoid redundant actions like this (I've made inquiries to verify I didn't miss something). 

I'm sure I can hand-roll something (the info I need seems to be available) -- I didn't think it would be a deal-breaker before I landed it, but it looks like it's a more significant issue than I thought. I'll get to work on it straightaway.

**Pull request merged**
