### PR TITLE
Drop support for LLVM5

### PR DESCRIPTION
**Pull request by steven-johnson**
Proposal to drop support for LLVM5 (since we are no longer testing it), and only support LLVM6, LLVM7, and trunk:

- Update Travis to test with with LLVM 6 instead of 5+6
- prune all ifdef'ed code that assumes LLVM can be < 60
- update README

### CODE REVIEW

**Comment by steven-johnson** [comment]
Rebased to remove all the debugging commits. 

Also note that Travis now tests *only* with LLVM6 (not 6+7); AFAICT, the prebuilt version of LLVM7 that claims to be compatible with Ubuntu Trusty is hard to get to work correctly; since Travis is meant as a quick-n-dirty check anyway, it's simpler to just check a single LLVM version (and rely on the buildbots for broad-spectrum coverage).

**Comment by shoaibkamil** [comment]
LGTM, but we'd like to do a bit of comprehensive testing over the next few days if you don't mind.

**Comment by steven-johnson** [comment]
Absolutely. Dropping an LLVM version needs wide buy-in at this point.

**Comment by steven-johnson** [comment]
Gentle ping to other reviewers -- would like to get wide buy-in from major users before landing this.

**Comment by abadams** [comment]
We track trunk llvm. sgtm.

**Pull request merged**
