### PR TITLE
ION: Support newer ioctl format for kernel 4.12 and up

### PR DESCRIPTION
**Pull request by ronlieb**
Check if older IOCTL format works, if so use it.
Otherwise try newer IOCTL format as required by kernel 4.12 and higher.

### CODE REVIEW

**Comment by steven-johnson** [comment]
All clean, ready to merge.

**Comment by ronlieb** [comment]
Dillon, did your testing go ok on this one?

**Comment by steven-johnson** [comment]
Monday morning ping to @dsharletg

**Comment by steven-johnson** [comment]
Is this still an active PR?

**Comment by dsharletg** [comment]
I was finally able to test this on a device where it can actually be tested.

**Comment by ronlieb** [comment]
@pranavb-ca @dpalermo : I wonder if its too late to get a qualstar for this patch :-)

**Pull request merged**
