### PR TITLE
Use $<TARGET_FILE> for build_halide_h

### PR DESCRIPTION
**Pull request by steven-johnson**
In theory this shouldn't be necessary, opening as draft

### CODE REVIEW

**Comment by steven-johnson** [comment]
So I know that explicitly expanding a target to full path isn't supposed to be necessary, but it appears to be necessary when crosscompiling for arm32 on an aarch64 machine; for simplicity, we compile *everything* (including our tools like build_halide_h) with the toolchain file, and my assumption here is that because it's a 'foreign' executable, the expansion doesn't happen, because the path isn't expanded and those tools don't get launched. Adding the TARGET_FILE decoration makes it work on those buildbots. (Maybe there's a different setting that is needed, but this seems harmless.)

**Comment by alexreinking** [comment]
Uggghhhh this is CMake at its most brain-dead and obtuse. The real solution is to split off our host-and-build-only tools into a separate project. I haven't had the time to make this change.

As a stopgap, I _think_ modifying the toolchain file (which is needed anyway) to _not_ set `CMAKE_SYSTEM_NAME` will trick CMake into thinking it's not cross-compiling and this should still work for 64-to-32 bit cross-builds.

**Comment by steven-johnson** [comment]
> _**Uggghhhh**_ this is CMake at its most brain-dead and obtuse

That's impressive, actually

**Comment by steven-johnson** [comment]
> 2\. Set `CMAKE_CROSSCOMPILING_EMULATOR` to `/usr/bin/env`, which will just launch the program directly.

This seems like the sounder/safer choice to me -- fudging CMAKE_SYSTEM_NAME seems like a recipe for weird miscompiles.  (Presumably we could also override CMAKE_CROSSCOMPILING_EMULATORon e.g. x86-64 systems to point to qemu?)

**Comment by alexreinking** [comment]
> This seems like the sounder/safer choice to me -- fudging CMAKE_SYSTEM_NAME seems like a recipe for weird miscompiles. (Presumably we could also override CMAKE_CROSSCOMPILING_EMULATOR on e.g. x86-64 systems to point to qemu?)

Yes, qemu ought to work for x86-to-arm scenarios (though obviously with overhead).

**Review by alexreinking — CHANGES_REQUESTED** [review]
Not the right approach. #5808 is better

**Pull request closed without merging**
