### PR TITLE
Make HelloAndroid sample Gradle-friendly.

### PR DESCRIPTION
**Pull request by aam**
With this change you can build HelloAndroid using Gradle - current choice for Android development.
You can also open(Import) this project into Android Studio and continue your development cycle there(which includes editing/recompilation of the Halide filter).

What do you think?

### CODE REVIEW

**Comment by abadams** [comment]
I'll try it out.

**Comment by abadams** [comment]
Why the upgrade to API version 21?

It would be good to add explicit instructions for Android Studio to the bottom of the readme. They appear to be: set up local.properties as described in the gradle section, then use "import project" in Android Studio and select Halide/apps/HelloAndroid/build.gradle.

I also had to change Application.mk to remove architectures not present in the archs map in build.gradle

**Comment by aam** [comment]
Thank you for taking a look, Andrew!

I reverted back to API 17 - good point.
I added instructions for getting Android Studio up and running and for keeping list of platforms in build.gradle and in Application.mk in sync.

Please take a look. Thanks.

**Comment by abadams** [comment]
Ok, looks good to me. Merging. One catch is that the nightlies are not currently built with the llvm MIPs backend enabled. I'll change that.

**Pull request merged**
