### PR TITLE
HelloPyTorch: allow for mixed python2 + python3 installs

### PR DESCRIPTION
**Pull request by steven-johnson**
I'm sure we don't want to bother supporting python2 anymore, but we probably still want to support running on systems that have both py2 and py3 installed (at least until Jan 1 2020); therefore, bottleneck python into a Makefile var and default it to be explicitly 'python3'.

attn @mgharbi

### CODE REVIEW

**Comment by steven-johnson** [comment]
Ping to @mgharbi for feedback on this

**Comment by mgharbi** [comment]
Looks good to me. The prints are ugly, but the app builds and test pass also with Python2.7.

**Comment by steven-johnson** [comment]
Asking from ignorance: does PyTorch still support Python2?

**Comment by mgharbi** [comment]
Maybe we can add `from __future__ import print_function` atop `test.py`.
Yes, PyTorch still support python2.7

**Comment by steven-johnson** [comment]
> Maybe we can add `from __future__ import print_function` atop `test.py`.

PTAL

**Comment by mgharbi** [comment]
I confirm this works for python2/3 on my end.

**Comment by steven-johnson** [comment]
cool, ping to J. Random Reviewer for approval

**Comment by steven-johnson** [comment]
Monday Morning Review Ping

**Pull request merged**
