### PR TITLE
Make Callable::call_argv_fast public

### PR DESCRIPTION
**Pull request by twesterhout**
Addresses #7314.

I'm wondering, is the argv-based calling convention is documented somewhere? If so, I can add a reference to the doc string.

### CODE REVIEW

**Comment by steven-johnson** [comment]
> is the argv-based calling convention is documented somewhere

Probably not, at least not as well as it should be. Basically:
- All scalar arguments are passed by *pointer*, not by value, regardless of size
- All buffer arguments (input or output) are passed as `halide_buffer_t*`
- All arguments are passed in the same order as they appear in the C function argument list

**Review by steven-johnson — APPROVED** [review]
LGTM pending green buildbots.

**Comment by twesterhout** [comment]
One of the Windows builds is failing. It can't have anything to do with the latest commits, can it? I've only changed the wording in the comments...

**Comment by steven-johnson** [comment]
> One of the Windows builds is failing. It can't have anything to do with the latest commits, can it? I've only changed the wording in the comments...

Yes, unfortunately our Windows buildbots are in need of some love and that's one of the flakes. This is fine to land.

**Pull request merged**
