### PR TITLE
[serialization] Add Halide version and serialization version in serialization format

### PR DESCRIPTION
**Pull request by TH3CHARLie**
Add Halide version string and serialization version string as part of the format. The halide version records the halide build under which the pipeline is serialized, a pipeline generated under an older Halide build could be compatible with a newer one, but we generate a user warning. The serialization version reflects any changes in the format itself, if the serialization version string does not match then it must be incompatible so we issue an error.

We also discussed adding a target string into the format as well, but we only know the target when we realize the pipelines (i.e. when calling `realize`) so I'm not sure what's the best way to obtain a reasonable target string here.

### CODE REVIEW

**Comment by derek-gerstmann** [comment]
Actually the target is required when we serialize too (eg when they are exported from generators)  … it may be a default no-arch, no-platform, but it should be included in the header

**Comment by TH3CHARLie** [comment]
> Actually the target is required when we serialize too (eg when they are exported from generators) … it may be a default no-arch, no-platform, but it should be included in the header

Now we don't ask for target explicitly during serialization. Maybe we serialize a "host" equivalent target string?

**Comment by derek-gerstmann** [comment]
> > Actually the target is required when we serialize too (eg when they are exported from generators) … it may be a default no-arch, no-platform, but it should be included in the header
> 
> Now we don't ask for target explicitly during serialization. Maybe we serialize a "host" equivalent target string?

Yes, I think we should allow the target to be specified during serialization (so that generators which are evaluated for a specific target can indicate that the schedule is only appropriate for the chosen target), and default to something like no-arch, no-platform (meaning it is independent from the cpu/os).

We should probably also consider storing any autoscheduler that was used and it’s params.

**Review by steven-johnson — APPROVED** [review]

**Comment by steven-johnson** [comment]
Broken for Makefile builds because HALIDE_SERIALIZATION_VERSION_MAJOR and friends aren't defined there

**Comment by steven-johnson** [comment]
> Broken for Makefile builds because HALIDE_SERIALIZATION_VERSION_MAJOR and friends aren't defined there

fix pushed

**Pull request merged**
