### PR TITLE
allow building Python bindings as a standard Python package

### PR DESCRIPTION
**Pull request by minrk**
Based on existing Makefile

- simplifies installation of Python bindings (no need for PYTHONPATH),
  following Python standards (can be `pip install`ed).
- statically links halide and boost python in anticipation of building and distributing wheels
- finds halide, boost with HALIDE_DIR, BOOST_DIR env variables, if defaults
- finds halide from local build (../lib) by default, following Makefile

To build a redistributable wheel from a fresh clone of the repo:

```
make -j
cd python_bindings
python setup.py bdist_wheel
```

### CODE REVIEW

**Comment by abadams** [comment]
Does this replace the existing python_bindings/Makefile? Should we delete it?

**Comment by jrk** [comment]
It does. I contemplated doing that as part of this commit, but initially I
thought it might be lowest-risk to leave the Makefile as a document and
clean it up later as more work happens here. We could also delete it
immediately, I think, right @minrk?

I was also wondering: should we pull the Python bindings into a standalone
repo?

**Comment by minrk** [comment]
I'm happy removing the Makefile here. It's still in the history for reference, and hasn't changed since the latest release tag.

The Makefile made some assumptions about Python and boost that don't hold in general, so it already would need edits to build on most systems. I made a bit of an effort to loosen some of those with search and accept environment variables where defaults don't work.

> should we pull the Python bindings into a standalone repo?

I think this would probably be nice, but I might not do it if every halide release were going to require changes in the Python bindings. If changes in halide itself frequently require changes in the Python bindings, it may make sense to keep them together for easier coordinated updates.

**Comment by abadams** [comment]
Changes in Halide do frequently change the python bindings. Probably better to keep them in the same repo.

One minor problem I found with this PR is that on ubuntu, /usr/lib/x86_64-gnu-linux needs to be in the search path (it's where my boost python lives).

The other annoyance is that I can do make -j48 on the Makefile, but I can't figure out how to parallelize pip. Any tips?

**Comment by jrk** [comment]
Parallel build might be the other reason to keep the Makefile around—for
simple testing and development. That said, how long does this build take?
It's like 15 files, and should shrink since I believe the NumPy wrapper can
be dropped for basic core Boost features now. This is definitely a place
where custom strace trickery could be fun. :) (See also
http://stackoverflow.com/questions/11013851/speeding-up-build-process-with-distutils
)

The setup.py is still important, as it's by far the smoothest path to
building and packaging actual distributable Python modules, which I suspect
is how 9x% of potential users of this will want to get it.

**Comment by jrk** [comment]
Also, re: the need for tighter integration for version changes, are these bindings built at all as part of the regular testing process? I didn't think they were.

**Comment by abadams** [comment]
They are continuously tested along with everything else.

**Comment by abadams** [comment]
(The only things that aren't are some of the apps)

**Comment by minrk** [comment]
@abadams yeah, building with Python can be a bit slow and annoying. Python itself only supports parallel builds at the Extension level (doesn't help here, since there's only one). numpy 1.10 adds support for parallel builds at the object level, but I [discovered](https://github.com/numpy/numpy/pull/8767) that it doesn't actually do anything in parallel on mac. I can ship a patch for the numpy parallel builds in setup.py (I have it locally and it works), but that might be more than you want to maintain here.

**Comment by minrk** [comment]
with the current state, you can:

    python setup.py build -j48

or

    NPY_NUM_BUILD_JOBS=16 pip install .

to do parallel builds.

The patched `exec_command` is from an upstream fix providing parallel builds on Mac. Parallel builds work on Linux with numpy >= 1.10 without any patch, if you'd like to not ship the patch and wait for a numpy release to fix the parallel builds on darwin.

**Comment by abadams** [comment]
I'm having a hell of a time trying to get this to work on ubuntu, and I'm out of my depth at this point.

**Comment by minrk** [comment]
I'll set up a test VM to see if I can figure it out. The simplest version is probably to remove the parallel builds and leave it with the Python defaults.

**Comment by minrk** [comment]
Ubuntu does yet another thing for naming boost libs, so I had to update the possible names to include `boost_python-py35`. I also discovered that their static libs are not appropriate for pulling in to a shared library (not build with `-fPIC`), so I backed off statically linking boost, leaving it dynamically linked.

[This Dockerfile](https://gist.github.com/4a0f32ad6518624172ae48e295f6759c) (run from the python_bindings dir in this branch) builds the Python bindings on py2 and py3 on Ubuntu.

**Comment by abadams** [comment]
On ubuntu 14.04 at least, libraries are in /usr/lib/x86_64-linux-gnu, so setup.py doesn't find boost. It also seems to need to link to -lpython2.7 or -lpython3.4m or similar for the has_function thing to work. Making those changes I can build. However we also need a self-contained way to test many Halide/compiler/llvm version combos within one user account. Is there a way to install it somewhere within the build dir? When just building it, the name and location seems to differ depending on python version. pip3 install --root seems to expect a functioning python installation in the provided path. I hacked up the tests scripts to use find to look for something named halide.*so and add it to the python path. This feels a little gross. 

I have also been unable to get any build parallelism, with -j or with NPY_NUM_BUILD_JOBS in the environment.

Anyway, my modifications are in https://github.com/halide/halide/tree/minrk-python-package

**Comment by minrk** [comment]
I'll see what I can do to reproduce the issue on 14.04. 16.10 puts boost in the same place, but it is found without any additional help.

virtualenvs should be the answer to multiple installations without any need for messing with PYTHONPATH.

**Comment by jph00** [comment]
This looks really helpful. I had to add 'tinfo' to the libraries. Other than than, it built fine on the latest Ubuntu 16, although I wasn't able to use parallel build.

However, running any of the sample python apps gives the error:

```
Traceback (most recent call last):
  File "apps/interpolate.py", line 208, in <module>
    main()
  File "apps/interpolate.py", line 175, in main
    input = ImageParam(float_t, 3, "input")
Boost.Python.ArgumentError: Python argument types in
    ImageParam.__init__(ImageParam, Type, int, str)
did not match C++ signature:
    __init__(_object* self, Halide::Type t, int dims)
    __init__(_object* self, Halide::Type t, int dims, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > name)
```

I'm using the standard conda boost package an anaconda python 3.6 with all updates.

**Comment by steven-johnson** [comment]
This PR is pretty old. Is it still applicable?

**Comment by dsharletg** [comment]
Based on no reply to @steven-johnson above, and the fact that this PR appears to be behind the repo rewrite, I'm going to close this.

**Pull request closed without merging**
