### PR TITLE
Use n32:64 in RISC-V data layout

### PR DESCRIPTION
**Pull request by dkurt**
related: https://github.com/llvm/llvm-project/commit/974e2e690b4024c2677dde26cc76ec31e0047c1d
resolves https://github.com/halide/Halide/issues/7174

### CODE REVIEW

**Comment by steven-johnson** [comment]
LGTM, please push one more commit to trigger the buildbots

**Comment by zvookin** [comment]
Only question here is whether this should be conditional in the LLVM version. It looks like it was kind of always wrong. I guess the way to find out would be to make the change unconditional and see if if it still works with LLVM 15, but that may not be worth it. (The buildbots will not test that and I don't have an LLVM 15 tree handy.) Going to LGTM this.

**Review by zvookin — APPROVED** [review]

**Comment by steven-johnson** [comment]
LGTM once buildbots are green.

**Comment by dkurt** [comment]
@zvookin, good point. Not sure if that will work but I can check with LLVM 15 as well.

**Comment by steven-johnson** [comment]
Thanks for the fix!

**Pull request merged**
