### PR TITLE
Remove support for legacy buffer_t via define_extern

### PR DESCRIPTION
**Pull request by steven-johnson**
This is step one towards (eventually) removing support for LegacyBufferWrappers; it keeps support for generating toplevel entry points that use buffer_t (via the LegacyBufferWrappers flag), but removes support for `define_extern` functions using buffer_t.

(This probably isn't ready to land yet, but the Google codebase is getting close to eradicating all legacy `define_extern()` usage, so I wanted to put this out for discussion, to see if other downstream users are also ready to drop this backwards support.)

### CODE REVIEW

**Comment by abadams** [comment]
I would love to see this killed with fire, but I'm not the one with legacy usage.

**Comment by steven-johnson** [comment]
Adding @shoaibkamil to comment on Adobe usage.

**Comment by shoaibkamil** [comment]
We don't use legacy `buffer_t` anymore at all, so this should be good from our perspective.

**Comment by steven-johnson** [comment]
I'm ready to land this on my side. Any objections?

**Pull request merged**
