### PR TITLE
Clone of https://github.com/halide/Halide/pull/5117 for testing

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by Infinoid** [comment]
https://buildbot.halide-lang.org/master/#/builders/8/builds/6 looks like something my patch may have caused.  Any way to get a backtrace?

**Comment by steven-johnson** [comment]
> https://buildbot.halide-lang.org/master/#/builders/8/builds/6 looks like something my patch may have caused. Any way to get a backtrace?

We're running CTest with `--output-on-failure`, so it *should* be doing that, but... sigh. Running it in super-verbose mode might help?

**Comment by steven-johnson** [comment]
> https://buildbot.halide-lang.org/master/#/builders/8/builds/6 looks like something my patch may have caused. Any way to get a backtrace?

Actually, I don't think so, it's showing up in another (unrelated) pending PR: https://buildbot.halide-lang.org/master/#/builders/8/builds/7

**Comment by Infinoid** [comment]
Ok, I was thinking the addition of new methods could possibly have changed pybind11's method dispatch in a subtle way, I've had troubles with that in the past.  But if the crash happens elsewhere, it makes that a lot less likely.  I'll trust your judgement, thanks.

**Comment by steven-johnson** [comment]
I rebooted the winbot in question and restarted your build. Let's see if it runs OK overnight.

**Comment by steven-johnson** [comment]
It's happening everywhere, so LGTM

**Pull request closed without merging**
