### PR TITLE
Revise cmake build

### PR DESCRIPTION
**Pull request by darkbuck**
Use LLVM cmake package from LLVM project with several minor refinement.
- auto-detect available targets (similar to make build)
- add missing PowerPC backend
- remove two unused options
- revise travis build script

### CODE REVIEW

**Comment by abadams** [comment]
The cmake build mostly exists for windows. I have queued up tests of this PR on the windows build bots. Will report back when they're done.

**Comment by ashishUthama** [comment]
I have setup a common build flow (win64, glnxa64, maci64) using Halide's cmake build. Mainly because I have to automate building LLVM/Clang and Halide from source and it was easier this way.

If cmake is tailored for Windows, should I revisit this decision and use the usual make approach for glnxa64 and maci64?

**Comment by abadams** [comment]
The buildbots use the Makefile on linux and OS X, and cmake on Windows, so
that's the most reliable path. We keep cmake tested on linux using travis,
so that should also be solid. I don't think our cmake build is regularly
tested on OS X.

Frankly, all the Halide devs hate cmake, but it's currently the easiest way
to generate MSVC solutions. I'm continually tempted to just write a damn
nmake file, and srj is hoping that bazel gets mature enough on windows to
use instead.

**Comment by abadams** [comment]
Looks like a compatible change to the windows buildbot config would need to be made too:

https://buildbot.halide-lang.org/master/builders/win-64-trunk/builds/1872/steps/Configure%20Halide%20Release/logs/stdio

That's in this repo: https://github.com/halide/build_bot/blob/master/master/master.cfg

This is going to need manual testing. I'll poke at it when I'm next sitting in front of a windows box.

**Comment by darkbuck** [comment]
We need to define LLVM_DIR instead of LLVM_BIN/LLVM_INCLUDE to direct cmake where to find LLVM-Config.cmake. That buildbot script needs fixing just as the travis build script revised here. Also, Windows needs more polishing and it's always handled specially in the current CMake.

**Comment by kgnk** [comment]
Hey if you're updating the Windows build, these are the configurations I would like to see (CMAKE build types notwithstanding):

- Debug : For debugging the Halide library itself. Produces Halide.pdb. Not necessary for binary releases of Halide.
- OptimizedDebug : For linking with a Debug build application, but not to debug the Halide library itself. It has all the asserts but fast enough to use most of the time during development. Produces Halide.pdb.
- ReleaseWithSymbols : Similar to above. Fast enough for testing but it's still possible to produce a stack trace, minus inlined functions. Produces Halide.pdb.
- Release : Same as the current Release.

The OptimizedDebug and ReleaseWithSymbols builds are different in that they use different standard runtime libraries.

**Comment by abadams** [comment]
Here's what happens on windows:

    $ cmake -DLLVM_DIR=D:\\b\\slave\\win-64-trunk\\llvm-build\\lib\\cmake\\llvm -DBUILD_TYPE=Release -G "Visual Studio 14 Win64" ..\\halide
    -- Found LLVM 4.0.0svn
    -- Using LLVMConfig.cmake in: D:\b\slave\win-64-trunk\llvm-build\lib\cmake\llvm
        CMake Error at CMakeLists.txt:37 (message):
      Tool llvm-as not found at
      D:/b/slave/win-64-trunk/llvm-build/$(Configuration)/bin/llvm-as.exe
    Call Stack (most recent call first):
      CMakeLists.txt:43 (check_tool_exists)

    -- Configuring incomplete, errors occurred!
    See also "D:/b/slave/win-64-trunk/halide-build-Release/CMakeFiles/CMakeOutput.log".
    See also "D:/b/slave/win-64-trunk/halide-build-Release/CMakeFiles/CMakeError.log".

It looks like the check_tool_exists lines are failing because $Configuration is present in variables like LLVM_AS. Commenting out the check_tool_exists lines works fine. Maybe they're not necessary? Not sure what the elegant solution is here.

**Comment by abadams** [comment]
Ugh, I take it back. There are also unresolved symbols galore on Windows: 

https://gist.github.com/abadams/ac5c401da3feb1a892ebb0c56fb3008c

The missing symbols start around line 1320

**Comment by darkbuck** [comment]
That looks like the inconsistent NDEBUG definition.

**Comment by darkbuck** [comment]
My change doesn't handle cmake on Window yet. I will make the similar change soon.

**Comment by darkbuck** [comment]
cmake on Windows is revised as well. I verified locally with Halide(Release build) against LLVM(Debug/Relase build) build as well as Halide(Debug build) against LLVM (Debug/Release build). All of them works for me. Paste [log](https://gist.github.com/darkbuck/73f2a9169dab36327a25d41cd7340365) from one combination (Halide Relase + LLVM Debug).

**Comment by abadams** [comment]
Works! ... but I still need to comment out the check_tool_exists lines due to the $Configuration variable present in them. Was that not an issue for you?

**Comment by darkbuck** [comment]
no, that's not issue for me. Can paste the details of your cmake command line and build command line?

for me, if I populated PATH with the path to that LLVM binary (I could use LLVM_DIR as well, it's an alternative approach for cmake to find LLVMConfig.cmake), the steps are quite trivial

```
cmake -DCMAKE_BUILD_TYPE=<Debug|Release> ..\Halide # to generate solution files
cmake --build . # build Halide
```

**Comment by abadams** [comment]
It's only an issue on windows for me. My command line is

    cmake -DCMAKE_BUILD_TYPE=Release LLVM_DIR=/path/to/llvm-build/lib/cmake/llvm ../halide

Then I build it by opening the solution file in visual studio

The $(Configuration) variable is correct - the location of the tools does indeed depend on whether you want Debug or Release. But check_tool_exists doesn't understand it. Perhaps my llvm build is different to yours?

**Comment by darkbuck** [comment]
What kind of errors you got?

**Comment by abadams** [comment]
The same as in the comment above:

    $ cmake -DLLVM_DIR=D:\\b\\slave\\win-64-trunk\\llvm-build\\lib\\cmake\\llvm =DBUILD_TYPE=Release -G "Visual Studio 14 Win64" ..\\halide
    -- Found LLVM 4.0.0svn
    -- Using LLVMConfig.cmake in: D:\b\slave\win-64-trunk\llvm-build\lib\cmake\llvm
        CMake Error at CMakeLists.txt:37 (message):
      Tool llvm-as not found at
      D:/b/slave/win-64-trunk/llvm-build/$(Configuration)/bin/llvm-as.exe
    Call Stack (most recent call first):
      CMakeLists.txt:43 (check_tool_exists)

    -- Configuring incomplete, errors occurred!
    See also "D:/b/slave/win-64-trunk/halide-build-Release/CMakeFiles/CMakeOutput.log".
    See also "D:/b/slave/win-64-trunk/halide-build-Release/CMakeFiles/CMakeError.log".

**Comment by estollnitz** [comment]
In your command, should `-DBUILD_TYPE` be `-DCMAKE_BUILD_TYPE`? Not sure if that affects the expansion of `$(Configuration)`...

**Comment by abadams** [comment]
It should, I fixed that, but didn't update the copy-paste

**Comment by darkbuck** [comment]
how LLVM is build through cmake? have you set CMAKE_CONFIGURATION_TYPES in LLVM builds?

**Comment by abadams** [comment]
Here's what the buildbots do:

https://buildbot.halide-lang.org/master/builders/win-64-trunk/builds/1887/steps/Configure%20LLVM/logs/stdio

**Comment by abadams** [comment]
IIRC, they (intend to) use release LLVM for both Release and Debug halide. Debug LLVM is really slow.

**Comment by darkbuck** [comment]
Do you need to replace 
-DLLVM_DIR=D:\\b\\slave\\win-64-trunk\\llvm-build\\lib\\cmake\\llvm

with

the path where LLVM is really installed?

cmake log suggests that LLVM should be installed ../llvm-install.

cmake -DCMAKE_INSTALL_PREFIX=../llvm-install

**Comment by darkbuck** [comment]
LLVMConfig.cmake in build path D:\\b\\slave\\win-64-trunk\\llvm-build\\lib\\cmake\\llvm\LLVMConfig.cmake is not the final one being installed

**Comment by abadams** [comment]
LLVM isn't installed anywhere, just built. The buildbots don't have permissions to actually install anything in the system.

**Comment by abadams** [comment]
I could add an additional build step to install it in a temp directory, but just commenting out check_tool_exists makes everything work fine, so I suspect there's a simpler solution

**Comment by darkbuck** [comment]
you could install anywhere under D:\b\slave\win-64-trunk\llvm-build, says D:\b\slave\win-64-trunk\llvm-build\install. Without building the install target, LLVMConfig.make is still invalid to be referenced.

Here's the difference from that file in build dir and install dir

- in build dir
```
set(LLVM_TOOLS_BINARY_DIR "C:/halide/build.llvm/$(Configuration)/bin")
```

- in install dir

```
set(LLVM_TOOLS_BINARY_DIR "${LLVM_INSTALL_PREFIX}/bin")
```

**Comment by darkbuck** [comment]
removing 'check_tool_exists' should be fine. $(Configuration) is only replaced with the real configuration name by the build system. So, it won't be resolved when we run 'cmake'.

**Comment by darkbuck** [comment]
One more thing may still require 'install'. We may run 'llvm-config' even though it's only required on non-Windows build.

**Comment by estollnitz** [comment]
@abadams: No need to add an extra build step if you want to install LLVM in a temp directory. You can simply change `ALL_BUILD.vcxproj` to `INSTALL.vcxproj` in the existing build step in `master.cfg`, and LLVM will be built and then installed in (i.e., copied to) `../llvm-install` (the value of `CMAKE_INSTALL_PREFIX`). After that, you should be able to point `LLVM_DIR` at the installed location.

**Comment by abadams** [comment]
Ah, a very easy change. That seems to work fine. I'll merge this and then fix up the buildbot master. Thanks for bearing with me.

**Comment by estollnitz** [comment]
The section of `README.md` titled "Building Halide with cmake" also needs updating. Would be great to see a clear explanation of what `LLVM_DIR` should point to.

**Pull request merged**
