### PR TITLE
Add configure_cmake.sh

### PR DESCRIPTION
**Pull request by steven-johnson**
I find that I'm frequently doing copypaste of old cmake commands to reconfigure my build in certain ways; this script makes my life easier, so maybe it will make other people's life easier, too.

### CODE REVIEW

**Comment by alexreinking** [comment]
This is pretty much what presets are for. Have you considered using those?

https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html

**Comment by steven-johnson** [comment]
> This is pretty much what presets are for. Have you considered using those?

Didn't know that was a thing. Let me take a look.

**Comment by steven-johnson** [comment]
I find it amusing that apparently presets weren't added to CMake will v3.19, but we specify cmakeMinimumRequired=3.16 in out CMakePresets.json file...

**Comment by steven-johnson** [comment]
Looking over the CMake presets documentation, it looks like it may be capable of doing the stuff I want (though I'm not a fan of the invocation syntax) -- I'll withdraw this PR for now, and offer a new one (with mods to CMakePresets.json if needed, or maybe just an addition to .gitignore to allow me to use my bespoke script locally)

**Comment by alexreinking** [comment]
You can also use CMakeUserPresets.json, which I believe is already in our `.gitignore`.

**Comment by alexreinking** [comment]
@steven-johnson -- something like this might meet your requirements:

```
{
  "version": 3,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 21,
    "patch": 0
  },
  "configurePresets": [
    {
      "name": "srj",
      "displayName": "Personal settings",
      "description": "Personal build template",
      "generator": "Ninja",
      "binaryDir": "${sourceDir}/build/halide-$env{LLVM_VERSION}",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release",
        "CMAKE_INSTALL_PREFIX": "$env{HOME}/halide-$env{LLVM_VERSION}-install",
        "Halide_CCACHE_BUILD": "ON",
        "Halide_TARGET": "host",
        "LLVM_ROOT": "$env{HOME}/llvm-$env{LLVM_VERSION}-install"
      }
    },
    {
      "name": "srj-11",
      "inherits": "srj",
      "environment": { "LLVM_VERSION": "11" }
    },
    {
      "name": "srj-12",
      "inherits": "srj",
      "environment": { "LLVM_VERSION": "12" }
    },
    {
      "name": "srj-13",
      "inherits": "srj",
      "environment": { "LLVM_VERSION": "13" }
    },
    {
      "name": "srj-14",
      "inherits": "srj",
      "environment": { "LLVM_VERSION": "14" }
    }
  ]
}
```

Then just run:

```
$ cmake --preset=srj-14
$ cmake --build build/halide-14
```

Also note that `cmake --build` now supports `--verbose` and `--clean-first` flags that do what you'd expect. Bash completion for CMake is aware of these flags, too.

**Comment by steven-johnson** [comment]
I didn't notice the `inherits` keyword, that makes things a bit more doable.

And while it's nice that `cmake --build` now supports verbose and clean verbs, I never use that command (I use `ninja` directly).

**Pull request closed without merging**
