### PR TITLE
Add Input<Buffer> and Output<Buffer> to Generator

### PR DESCRIPTION
**Pull request by steven-johnson**
Currently, you are disallowed from using `ImageParam` with new-style Generators; this is problematic for Generators that need to make scheduling decisions based on attributes of the underlying Buffer. 

We could just allow ImageParams back in, but:
- syntactically this is weird
- we need something for `Output<>` as well, and using `OutputImageParam` for this is even weirder syntactically

This PR proposes to add `Input<Buffer<>>` and `Output<Buffer<>>` to new-style Generators:

- `Input<Buffer<>>` and `Output<Buffer<>>` autoconvert to `Func` (just like `ImageParam`), but also provide methods to set constraints on the required min/extent/stride of the underlying Buffer, and to get the actual min/extent/stride from the underlying Buffer.

- Any Generator that uses either `Input<Buffer>` or `Output<Buffer>` doesn't get a Stub (ie, it can't be used in fusion); it's toplevel only.

- Buffer template parameters must be specified explicitly, e.g.:

  ```
  Input<Buffer<uint8_t, 3>> input{"input"};  // OK
  Input<Buffer<>> input{"input"};            // Not OK, Halide compilation error
  ```

- Buffer type-and-dimensions are specified via template args, not via Halide::Type, e.g.

  ```
  Input<Buffer<uint8_t, 3>> input{"input"};    // OK
  Input<Buffer> input{"input", UInt(8), 3};    // Not OK
  ```

The controversial part here is probably that this is actually *more* restrictive than existing usage of ImageParam, in that the type-and-dim of the buffer can't be modified based on GeneratorParams. I could be persuaded that this is a bad idea, but my thinking is that the existing customization was a workaround for the lack of genericity; with new-style Generators, we can separate such a Generator into the interior, reusable part (using Input<Func>) and several explicitly-typed exterior parts (using Input<Buffer>).

This PR also converts enough Generators in the tests and apps to demonstrate that this concept should be adequate to meet existing needs.

### CODE REVIEW

**Comment by steven-johnson** [comment]
Friendly ping. Any comments on this?

**Comment by shoaibkamil** [comment]
> The controversial part here is probably that this is actually more restrictive than existing usage of ImageParam, in that the type-and-dim of the buffer can't be modified based on GeneratorParams.

This isn't a deal-breaker, but it does force one to enumerate (even if it's through templatization) the types/# of channels supported by a generator.  I can't decide whether that's a bug or a feature. 

The more annoying part is selecting which of the options to use at generation-time.

**Comment by steven-johnson** [comment]
I'm actually having second thoughts on this approach and am offering an alternate approach for consideration; see PR#1658

**Comment by steven-johnson** [comment]
I've revised this to allow unspecified-at-compile-time type/dim for Buffer; here are the revised PR notes. PTAL:

-------------------------------

Currently, you are disallowed from using `ImageParam` with new-style Generators; this is problematic for Generators that need to make scheduling decisions based on attributes of the underlying Buffer. 

We could just allow ImageParams back in, but:
- syntactically this is weird
- we need something for `Output<>` as well, and using `OutputImageParam` for this is even weirder syntactically

This PR proposes to add `Input<Buffer<>>` and `Output<Buffer<>>` to new-style Generators:

- `Input<Buffer<>>` and `Output<Buffer<>>` autoconvert to `Func` (just like `ImageParam`), but also provide methods to set constraints on the required min/extent/stride of the underlying Buffer, and to get the actual min/extent/stride from the underlying Buffer.

- Any Generator that uses either `Input<Buffer>` or `Output<Buffer>` doesn't get a Stub (ie, it can't be used in fusion); it's toplevel only.

- Buffer template parameters can be specified explicitly, e.g.:

  ```
  Input<Buffer<uint8_t, 3>> input{"input"};
  ```

In this case, you *cannot* override the type/dimensions via synthetic GeneratorParams (e.g. input.type=uint16 or input.dim=2 would fail).

- Buffer template parameters can be omitted:

  ```
  Input<Buffer<>> input{"input"};
  ```

In this case, you *must* override the type/dimensions via synthetic GeneratorParams.

This PR also converts enough Generators in the tests and apps to demonstrate that this concept should be adequate to meet existing needs.

**Comment by steven-johnson** [comment]
Ping for comments on this revised version (vs PR#1658)

**Comment by steven-johnson** [comment]
FYI: as of right now, we seem to be thinking that this solution looks better than the competing one in https://github.com/halide/Halide/pull/1658, but it needs a little more work to produce useful stubs for Input<Buffer>. Please don't land yet.

**Comment by shoaibkamil** [comment]
After the added functionality, I agree this solution is better than #1658.

**Comment by steven-johnson** [comment]
(Closing this PR in favor of PR#1709, which supersedes it)

**Pull request closed without merging**
