### PR TITLE
Handle saturating_cast in compute_expr_cost()

### PR DESCRIPTION
**Pull request by rootjalex**
Addresses #6944

### CODE REVIEW

**Review by abadams — APPROVED** [review]

**Comment by steven-johnson** [comment]
...lotsa failures in `performance_inner_loop_parallel` on Linux machines?

**Comment by rootjalex** [comment]
That's super weird, those tests don't even use saturating casts at all. It also appears to be failures both on linux-worker-1, is there an issue with that buildbot?

**Comment by rootjalex** [comment]
The piece of code that was changed isn't even touched by the execution of that test (on my machine), so this seems like a weird flake

**Comment by rootjalex** [comment]
I just confirmed that this code is also not touched by that test on an x86 machine, so this seems like a builedbot flake, I'm going to assume it is fine to merge.

**Pull request merged**
