### PR TITLE
Add Buffer::mutable_raw_buffer()

### PR DESCRIPTION
**Pull request by steven-johnson**
Cherry-picking from the discussions in PR#3206 and PR#3186; this will make my life a little less painful while longer-term issues around Buffer mutability are discussed.

### CODE REVIEW

**Comment by steven-johnson** [comment]
> The fundamental issue here

Yeah, the thing really is a bit of a disaster, unfortunately; there's a *lot* of existing code that passes things around by const ref, then uses a const-cast at the point of calling into Halide-generated code; really all this method does it make that horrible hack a bit easier to identify at the point of use.

As I've mentioned before, the semantics we have for Buffer mean that 
- they essentially can't ever be correctly passed by const-ref
- passing by non-const ref would be fine, but the Google C++ Style Overlords make this completely impossible for our codebase; I don't agree with this, but it's a battle I cannot hope to win
- passing by non-const pointer would *technically* be fine, but will mean that using temporaries for things like slicing become much more verbose. (And also would be kinda jarring to our users, style-wise, but at this point beggars can't be choosers)

My real motivation for this method is mainly that using it in my codebase means that the violations at least become much more tractable to identify and improve at some later date (ie: searching for calls to `mutable_raw_buffer` are much more robust than looking for every variant on const-casting that can crop up in our codebase). I don't pretend that this is anything like an actual solution, only that it is slightly less bad than the status quo.

**Comment by steven-johnson** [comment]
(I agree that better commenting is necessary. I'm pondering if I should just abandon this PR entirely and add this method as a Google-specific patch, but I fear that if I do that, the issue will be dropped from the public codebase indefinitely, and the existing suboptimal situation will continue...)

**Comment by abadams** [comment]
I take your point regarding providing a single idiomatic way to hack around the issue :) Other companies may well have the same issue, so I think it's reasonable to do this in the public repo.

That said, I doubt the overhead of making a local copy of the Buffer object is significant most of the time. For non-owned buffers it's just a few stack-to-stack move instructions. It has the added advantage of scoping any temporary device allocations.

**Comment by steven-johnson** [comment]
> I doubt the overhead of making a local copy of the Buffer object is significant

I agree that it's not significant in terms of real code. The textual overhead of more-lines-of-code is what I'm concerned about. I'll do some pondering over the long weekend.

**Comment by steven-johnson** [comment]
(In particular I want to experiment with changing a decent section of our code to pass all `Buffer<>` by pointer rather than ever using const-ref, and see how it actually feels; I've based my judgement on small snippets + pattern matching of existing code, which may not serve well in this case)

**Comment by abadams** [comment]
A lot of the time the textual overhead may be changing the containing function to accept a Buffer by value instead of by const ref. We could add sugar for that too though. E.g. an .alias() method that returns a non-owning view of the same memory as a fresh Buffer<T>. Then you could do:

```
my_pipeline(input_const_ref.alias(), ...)
```

and it would create a local copy of the metadata, then free anything like a device allocation when the temporary gets cleaned up.

**Comment by steven-johnson** [comment]
Say we have a function like so:

```
    void HalidePipeline(Buffer<const uint8_t>* input, Buffer<uint8_t>* output);
```

The input should be `const uint8` because duh, it's the input; since the underlying pipeline might alter the buffer's metadata, it needs to be either by-ref or by-ptr. (Since I'm writing this code inside Google, the former isn't an option, so by-ptr it is for our purposes here, though by-ref should have the same issues.)

Now, I want to write a simple test harness using a utility function I have handy to read a common-format image file into a buffer:

```
    // Read src from file. Needs to be non-const uint8 because we're writing the pixels.
    Buffer<uint8_t> input;
    CHECK_OK(HalideBufferFromFile("/path/to/file.png", &input));
```

You see where this is going, right? If I want to call `HalidePipeline` with this, I do something like:

```
    Buffer<uint8_t> output = Buffer<uint8_t>::make_with_shape_of(input);
    CallSomeHalideWrapperFunction(&input, &output);
```

Oops, that won't compile, because Buffer<const uint8_t>* is required and I'm giving it a Buffer<uint8_t>*, which isn't acceptable. To make this not-at-all-uncommon construct work, I need to either add an overload to `HalideBufferFromFile` (and all similar utility functions) to allow filling in non-const Buffers (which is conceptually weird, but OK), or add some impedance-matching code:


```
    Buffer<const uint8_t> const_input = input;  // yuck
    Buffer<uint8_t> output = Buffer<uint8_t>::make_with_shape_of(input);
    CallSomeHalideWrapperFunction(&const_input, &output);
```

... :-(

**Comment by steven-johnson** [comment]
> accept a Buffer by value instead of by const ref

Doesn't that just paper over the problem (not to mention adding extra calling overhead)? If the goal is to allow a calling mode which is "make a temporary for me which will always discard any gifted device allocs", wouldn't it be cleaner to to that internally to the generated wrappers?

**Comment by abadams** [comment]
Sure, you could do the by-value solution in a generated wrapper too. By-value implies some stack-to-stack moves that add a little overhead, but at this point it might be the least-bad solution for all the existing code giving you grief.

Regarding the const issue with pointers - I think the wrapper would have to have const and non-const variants? Or maybe it would have to take a template type which may or may not have a const on the value type. E.g. it accepts a `Buffer<T>` where `std::is_same<std::remove_cv<T>, float>::value`. Passing by value gives you a lot more leeway here.

**Comment by steven-johnson** [comment]
> By-value implies some stack-to-stack moves that add a little overhead, but at this point it might be the least-bad solution

Sadly, the Google Style Overlords will also give me grief for passing ~any struct by value (seriously, even passing `Expr` by value rather than by const-ref will generate reams of automated complaints, as you well know). I realize this is not your problem, just stating where I'm coming from for possible public readers. (In this case, I happen to agree with the guidelines; passing something as large/nontrivial as Buffer by-value on a regular basis seems like a bad idea.)

> I think the wrapper would have to have const and non-const variants?

In this case it's not even about a wrapper; `CallSomeHalideWrapperFunction` in the above example is hand-written code that invokes a Halide pipeline. Asking Halide users to write their code using `std::is_same<std::remove_cv<T>, float>::value` in order to accept both const and non-const Buffers is a nonstarter.

**Comment by abadams** [comment]
Google checkers complain if you accept an object by value and then never mutate it. We're specifically talking about a case where it gets mutated - and that's *why* we want to pass it by value. I don't think it should trigger that same automated complaint.

Creating a non-host-owning temporary buffer alias should involve just a memcpy of the halide_buffer_t and halide_dimension_t array. A quick and dirty-test shows that it requires these instructions:

```
        ## InlineAsm Start
        ##Wrapper start
        ## InlineAsm End
        vxorps  %ymm0, %ymm0, %ymm0
        vmovaps %ymm0, 96(%rsp)
        vmovaps %ymm0, 64(%rsp)
        vmovups (%rbx), %ymm0
        vmovups 24(%rbx), %ymm1
        vmovups %ymm1, 24(%rsp)
        vmovaps %ymm0, (%rsp)
        movq    40(%rbx), %rax
        vmovups (%rax), %ymm0
        vmovups 32(%rax), %ymm1
        vmovaps %ymm1, 96(%rsp)
        vmovaps %ymm0, 64(%rsp)
        leaq    64(%rsp), %rax
        movq    %rax, 40(%rsp)
        ## InlineAsm Start
        ## Temporary buf constructed. Calling pipeline
        ## InlineAsm End
        movq    %rsp, %rdi
        vzeroupper
        callq   __Z8pipelineP15halide_buffer_t
        movl    %eax, %r14d
        ## InlineAsm Start
        ## Back from pipeline, cleaning up temporary
        ## InlineAsm End
        movq    (%rsp), %rax
        cmpq    (%rbx), %rax
        je      LBB0_2
## BB#1:
        movq    %rsp, %rsi
        xorl    %edi, %edi
        callq   _halide_device_free
LBB0_2:
        ## InlineAsm Start
        ## Returning result
        ## InlineAsm End
```

This was my wrapper:

```

extern int pipeline(halide_buffer_t *in);

int test(const Runtime::Buffer<float> &buf) {
    int ret = 0;
    asm volatile ("#Wrapper start");
    {
        halide_buffer_t tmp_buf;
        halide_dimension_t tmp_shape[4]; // Dimensionality is statically known
        memcpy(&tmp_buf, buf.raw_buffer(), sizeof(halide_buffer_t));
        memcpy(tmp_shape, buf.raw_buffer()->dim, sizeof(halide_dimension_t) * 4);
        tmp_buf.dim = tmp_shape;
        asm volatile ("# Temporary buf constructed. Calling pipeline");
        ret = pipeline(&tmp_buf);
        asm volatile ("# Back from pipeline, cleaning up temporary");
        if (tmp_buf.device != buf.raw_buffer()->device) {
            halide_device_free(nullptr, &tmp_buf);
        }
    }
    asm volatile ("# Returning result");
    return ret;
}

```

**Comment by steven-johnson** [comment]
Did experimenting with pass-by-value; this can be made to work, but I'm skeptical that it won't get pushback on my side for cultural reasons.

Looking further at your idea of an `.alias()` method actually looks a bit more appealing, though:
- there are ways to finesse the helper-function issue 
- groups that really want to continue the style of passing inputs by const-ref can slap on an `.alias()` call to make it work; I'm gonna assume that we can make it clear that adding this adds small-but-nonzero overhead, and what the tradeoffs are.
- groups that care about maintaining device allocations across calls can pass by pointer everywhere.

**Comment by abadams** [comment]
Sounds good! Alias would be slightly higher-overhead than the wrapper I wrote above, because e.g. the compiler doesn't statically know that the buffer that gets passed into the Halide pipeline isn't gifted an owned host allocation, and doesn't statically know the dimensionality, so there are more checks in the setup and teardown. These things should all branch predict perfectly, so mostly it's a code size cost, I think.

**Comment by abadams** [comment]
Also I realized that my wrapper is slightly incorrect: if the input has an existing device allocation, and the pipeline bounces it to another device, then the original buffer now has a dangling device field.

**Comment by steven-johnson** [comment]
Regardless of what else happens, at this point I think `.alias()` is a less-bad alternative to `.mutable_raw_buffer()`, so I'm closing this PR.

**Pull request closed without merging**
