### PR TITLE
Add simplify rules for a modulo of a difference.

### PR DESCRIPTION
**Pull request by jingpu**

### CODE REVIEW

**Comment by abadams** [comment]
We're about to land a large change to the simplifier that this would conflict with (see the metaprogrammed_simplifier_rules PR). You might want to check that PR to see if it has coverage of these rules.

**Comment by jingpu** [comment]
I tried the metaprogrammed_simplifier_rules PR. Unfortunately, all the new tests except the last one (which I now think might pass even without the modification in this PR) didn't pass.

**Comment by jingpu** [comment]
Reopen the PR, as I hope to use them sooner on master. A equivalent PR #2996 is already merged into the new simplifier branch.

**Comment by jingpu** [comment]
I assume the crash in `correctness_simd_op_check` is unrelated. Merging.

**Pull request merged**
