### PR TITLE
Refactoring src/CMakeLists.txt

### PR DESCRIPTION
**Pull request by parkhc**
Using macro for runtime module generation.

### CODE REVIEW

**Comment by abadams** [comment]
This change appears to have broken the build on Windows: https://buildbot.halide-lang.org/master/builders/win-64-trunk/builds/1725/steps/Configure%20Halide%20Release/logs/stdio

**Comment by abadams** [comment]
Sigh, I hate cmake. https://cmake.org/Bug/view.php?id=5389

**Comment by steven-johnson** [comment]
"We don't want to have to pass result expressions with twice as many escapes, like "\\\\\\\\1\\\\\\\\2\\\\\\\\3". It's error prone."

*cough*

**Comment by steven-johnson** [comment]
To be fair, this bug has only been known about since 2007

**Comment by abadams** [comment]
Hilariously, in the email form of your message, I only see half as many backslash characters.

**Comment by parkhc** [comment]
Should I switch to function instead?

**Comment by abadams** [comment]
I think I have it figured out. PR incoming.

**Comment by parkhc** [comment]
Thanks!

**Comment by abadams** [comment]
#1695

**Pull request merged**
