### PR TITLE
[Hexagon] Provide alignment info to Hexagon offloaded kernels

### PR DESCRIPTION
**Pull request by dsharletg**
This PR plumbs through the alignment info that a hexagon kernel would have had if it were compiled without the closure for offloading.

It makes a few other changes:

- Re-added slice_vector, to make the IR easier to read. It still lowers to a shuffle_vectors in CodeGen_LLVM, so it still ultimately passes through the same code path.
- Add zero-copy buffer allocation for Hexagon buffers.
- Update the HelloHexagon app to take advantage of alignment and zero-copy buffers.

### CODE REVIEW

**Comment by ronlieb** [comment]
i am having difficulty compiling the HelloHexagon after the makefile changes
i am setting
export ANDROID_ARM64_TOOLCHAIN=/local/mnt2/ronl/SDK/Hexagon_SDK/2.0/tools/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64

but i get an error about stdio.h 


/local/mnt2/ronl/SDK/Hexagon_SDK/2.0/tools/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-c++ -std=c++11 -I ../../include/ -I ../../tools/ -I ../../apps/support/  --sysroot /local/mnt2/ronl/SDK/Hexagon_SDK/2.0/tools/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/platforms/android-21/arch-arm64 -Wall -O3 process.cpp pipeline-arm-64-android.o -o process-arm-64-android -llog -fPIE -pie
process.cpp:1:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^

**Comment by dsharletg** [comment]
Did you run make-standalone-toolchain.sh per the comment in the Makefile?

**Comment by ronlieb** [comment]
nope, oops, thx

**Comment by ronlieb** [comment]
ok, that took care of my build issue, thx

**Comment by dsharletg** [comment]
I'm going to merge this since I've got a few other branches behind this one. Feel free to comment on the changes if you see something you'd like changed.

**Pull request merged**
