### PR TITLE
Require LLVM >= 16.0

### PR DESCRIPTION
**Pull request by steven-johnson**
Per policy, we only support top-of-tree LLVM, plus two versions back; let's update to require LLVM >= 16, and drop workarounds for older versions.

### CODE REVIEW

**Comment by zvookin** [comment]
Why are you changing `#if LLVM_VERSION < 170` to `#if !(LLVM_VERSION >= 170)`? This is difficult to read. If there is a strong reason for making the change, maybe add a comment. In general there likely ought to be a comment on every LLVM version conditional.

**Comment by abadams** [comment]
I think the reason we were delaying this is that vcpkg was stuck on llvm 15, and our install instructions say to use vcpkg's llvm. We should check that vcpkg has moved on before landing this.

**Comment by steven-johnson** [comment]
> Why are you changing `#if LLVM_VERSION < 170` to `#if !(LLVM_VERSION >= 170)`? This is difficult to read. If there is a strong reason for making the change, maybe add a comment. In general there likely ought to be a comment on every LLVM version conditional.

IMHO it was easier to normalize everything to a form of `>=` but I don't feel strongly about this. I'll revert those.

**Comment by steven-johnson** [comment]
> I think the reason we were delaying this is that vcpkg was stuck on llvm 15, and our install instructions say to use vcpkg's llvm. We should check that vcpkg has moved on before landing this.

Good call, will do. Also, this should probably wait to land until after I create a fork for the Halide 17 release, since it ostensibly should still support LLVM 15..17.

**Comment by steven-johnson** [comment]
> > I think the reason we were delaying this is that vcpkg was stuck on llvm 15, and our install instructions say to use vcpkg's llvm. We should check that vcpkg has moved on before landing this.
> 
> Good call, will do. Also, this should probably wait to land until after I create a fork for the Halide 17 release, since it ostensibly should still support LLVM 15..17.

I have verified that vcpkg for Windows now provides LLVM17 as default.

**Review by vksnk — APPROVED** [review]

**Comment by steven-johnson** [comment]
OK to land (finally)?

**Comment by abadams** [comment]
Fine by me

**Pull request merged**
