### PR TITLE
Make compile time assert failures into warnings

### PR DESCRIPTION
**Pull request by dsharletg**
This PR makes compile time assertion failures into warnings instead of errors. This enables one to inspect the IR, which is often by far the most useful way to diagnose and fix these kinds of assertion failures.

### CODE REVIEW

**Comment by steven-johnson** [comment]
Suggestion: only make it a warning if (e.g.) HL_DEBUG_CODEGEN_LEVEL > 0, so that the default is still to fail.

**Comment by abadams** [comment]
I disagree on the HL_DEBUG_CODEGEN - I think if someone says compile_to_lowered_stmt, then it should still work with the constant-false assertion.

**Comment by zvookin** [comment]
I misread the description initially and I think that may be a common problem. If I understand the code change, this changes the very specific case where Halide has proved the conditional of an AssertStmt is always false from a compile time error to a warning. Assertion failures in the compiler, e.g. internal_assert, user_assert are unaffected. Is this correct?

I do like the idea of continuing to fail if generating a .o or equivalent executable thing and debugging is not turned on. That would leave compile_to_lowered_stmt working.

Another option is to simply refuse to generate the .o if there were any warnings. (As in I don't believe in compiler flags to treat warnings as errors because that flag should always be turned on and I never want to deal with code that only compiled with it turned off.)

**Comment by abadams** [comment]
You are correct, Zalman, this is just if the condition in an AssertStmt simplifies to false. The error is there because it seemed like a compile-time error would be more useful than a guaranteed runtime error. This turns out to not be the case in practice. No errors are suppressed if we turn this into a warning, it just delays the failure from compilation time to the first time you run it.

**Comment by abadams** [comment]
I'm going to merge this, because I think that even people who ignore warnings (or use build systems that don't surface them) will run their code directly after compilation, thus triggering the error.

**Pull request merged**
