### PR TITLE
[x86] Codegen phaddw, phaddd, and pmaddwd

### PR DESCRIPTION
**Pull request by rootjalex**
This PR adds support for `int16 -> int32` horizontal widening adds to use `pmaddwd`, and pattern matches on horizontal adds to use `phadd(w | d)`, which is faster than the permute + padd that we currently generate for such reductions (cite @abadams + llvm-mca because my x86 machine is currently broken). 

Also fly-by move of some code that I incorrectly placed in the wrong runtime file in #6677 .

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]
LGTM pending green -- I assume these changes are good against non-trunk LLVM versions too.

**Comment by rootjalex** [comment]
Yes, it should be fine - the phadd intrinsics have been in LLVM for over a decade [sse3](https://github.com/llvm/llvm-project/commit/2377206923c1b77296899b44a77ae814806ff2f2) [avx2](https://github.com/llvm/llvm-project/commit/682b850602d3380528c5ecafe352c48422e19724).

**Comment by steven-johnson** [comment]
`The vector and scalar versions of op_phaddw_285 disagree. Maximum error: 60123`

**Comment by rootjalex** [comment]
Failures were due to a shuffling mistake, I forgot that AVX2 has the 128 bit boundaries for instructions - fixed in 0acae70, and confirmed that we still produce better codegen for reductions.

**Comment by abadams** [comment]
There's a trade-off between adding new llvm ir implementations of things, and rewriting Halide Exprs into forms that would match existing patterns. E.g. for the widening add, you could rewrite the Expr so that it matches should_use_dot_product.

My question is: Did you consider that, and does this PR fall on the right side of that line?

**Comment by rootjalex** [comment]
We don't have any existing patterns for `phadd` instructions, so I'll only respond to your question in regards to the use of `pmaddwd` here.
I did not consider rewriting within Halide IR, but your suggestion raises a good point - I realize that I did not provide LLVM implementations for the AVX512 dot_product instructions, which could be similarly used. I suspect that your suggest would benefit from greater generality, and would be better suited for extensibility, so I will change this PR to transform all of the `horizontal_widening_add`s into the pattern that will match against the existing dot_product patterns

**Comment by rootjalex** [comment]
I will say that I don't think these particular patterns are suitable for rewriting to enable `should_use_dot_product`, but instead I will aim for producing the patterns that will match the VectorReduce dot_product instructions.

**Comment by steven-johnson** [comment]
buildbots are green -- is this ready to land?

**Comment by rootjalex** [comment]
I might close this PR in favor of #6884 , which will make the `horizontal_widening_add` patterns useful on any architecture that has `pmaddwd` variants. Just waiting to get feedback on whether that PR is indeed a better way of doing things.

**Comment by steven-johnson** [comment]
Monday Morning Review Ping -- where does this PR stand? Is it still likely to be dropped in favor of #6884?

**Comment by rootjalex** [comment]
Yes, I am closing this in favor of #6884 . If we end up not merging #6884 for some reason, I will re-open this PR.

**Pull request closed without merging**
