### PR TITLE
Allow Param<void>

### PR DESCRIPTION
**Pull request by steven-johnson**
Disclaimer: the goal of this is really to simplify the Python Binding implementation, so it may be misguided. That said, the change is pretty modest and safe, I think.

The problem: in the Python bindings, there is no equivalent to a compile-time type bindng; for Param, the type is always specified by a Halide::Type, rather than a compile-time type.

Since the existing Param structure *requires* a compile-time type, the existing Python bindings jump through great hoops: it provides a set of bindings for every likely instantiation of `Param<T>`, then provides an extremely complex set of factory methods to create the right underlying wrapper based on the Type (and other arguments) you pass.

Since `Param<>` already contains dynamic type information (by way of Parameter::type()), this just expands on it (much as `Buffer<void>` vs `Buffer<int>` does): Param<void> allows the type to be specified at runtime (rather than compiletime), then does typechecking on the runtime type.

The one exception, of course, is the get() and set() method, which still need to be special-cased; however, this is *much* less onerous.

Realistically, no 'real' Halide code is ever likely to make use of `Param<void>`, but it does make binding to dynamic languages like Python substantially simpler.

(Note that `Param<>::address()` was totally unused, and so it was removed.)

### CODE REVIEW

**Comment by steven-johnson** [comment]
Note also: since Param<> is really just a thin layer around Internal::Parameter, I could just add the necessary code in the python-binding layer instead; so far, I've avoided adding any 'original' code to those bindings, no matter how trivial, except for what's required for argument conversion. This might be one of those cases, since Param<> is mighty thin.

**Comment by abadams** [comment]
+1 to the idea, but it looks like there are legit builder breakages.

We need a scalar equivalent of ImageParam/OutputImageParam for generic
introspection/metaprogramming code

**Comment by steven-johnson** [comment]
Given that all builders are broken right now I haven't looked into breakages specific to this PR. Will do so probably early next week.

**Comment by steven-johnson** [comment]
Note that a side-effect of this change is that some calls to Param::set() may need explicit typing now, e.g.

    Param<uint8_t> f; 
    f.set(1); // error, as '1' is assumed to be int, not uint8
    f.set<uint8_t>(1); // this is fine

Adding code to fix this is not hard (we already do the same sort of thing in Generator.h), but it adds some ugly stuff to Param.h that I'm not sure pays for itself, as (in practice) the cases that break tend to be uncommon.

**Comment by abadams** [comment]
That pattern looks like it would be very common indeed for anyone heavily using the JIT. Could turn this PR into a breaking change.

**Comment by steven-johnson** [comment]
> looks like it would be very common indeed

Maybe, but consider that Halide own tests use the JIT heavily and this change only affected ~3 of them.

**Comment by steven-johnson** [comment]
(I certainly don't object to making the more robust fix if we prefer; it's just a little uglier.)

**Comment by steven-johnson** [comment]
Revised Param::set() to allow extant usage to work as-is, as well as adding some sanity checking; PTAL.

**Comment by zvookin** [comment]
If I have a `Param<T>` how do I get the `Param<>` for the same `Parameter`? (Apologies if this is obvious, but I can't quite see it from the diff.)

**Comment by steven-johnson** [comment]
> how do I get the Param<> for the same Parameter

Good point. I'll add appropriate conversion ctors a la Buffer<>

**Comment by steven-johnson** [comment]
PTAL

**Comment by steven-johnson** [comment]
Just waiting for buildbots to be clear-ish (aside from known current issues)

**Comment by steven-johnson** [comment]
The one failure is unrelated. Landing.

**Pull request merged**
