### PR TITLE
Fix clang-format issues

### PR DESCRIPTION
**Pull request by steven-johnson**
I don't know how/why the master branch isn't clean this way. (Maybe I have a different clang-format locally?)

### CODE REVIEW

**Comment by steven-johnson** [comment]
...hmm, yeah, something *is* different between my local make-format and the one running on GHA. Which is the one that has changed?

**Comment by abadams** [comment]
I don't think the remote one has changed recently. Are you using a different clang-format version?

**Comment by steven-johnson** [comment]
`make clang-format` uses your active llvm install, whereas GHA uses some stable version; maybe clang-format in trunk changed recently? I'll investigate.

**Comment by steven-johnson** [comment]
Looks like the change got injected here:

https://github.com/llvm/llvm-project/commit/4db94094b469b4715d08ef37f1799bf3ea7ca8ea

basically, it affects how nested ternary expressions are formatted. 

I'd argue that the new format is definitely *better*, but there doesn't appear to be a setting that allows us to preserve the old formatting, so this means that clang-format-11 can't be identical to previous clang-format versions for this.... sigh

**Comment by steven-johnson** [comment]
I added clang-format as necessary (and/or tweaking other code) to deal with this variation.

**Comment by abadams** [comment]
Yeah, definitely an improvement for ternary operators. At some point we'll just have to switch clang-format versions and update everything.

**Comment by steven-johnson** [comment]
So from the comments on the LLVM bug above, it appears that Team Clang-Format makes a deliberate decision *not* to try to maintain backwards compatibility across versions of clang-format, so we should probably consider requiring a specific version of clang-format (both in our presubmits and via `make format`, etc) to ensure drift doesn't occur.

**Pull request merged**
