### PR TITLE
CMake clean ups

### PR DESCRIPTION
**Pull request by delcypher**
These clean ups are in preparation for fixing the build of the tutorials and apps under CMake. I've tested this PR under Linux, OSX and Windows.

### CODE REVIEW

**Comment by abadams** [comment]
I made a comment on a commit. To ensure that it shows up as a comment on the PR I'll repeat it: 

I don't think the initial modules need any of these #defines (WITH_X86, etc). If my understanding is correct, they're just a bunch of static arrays. I'm a little confused that they exist as a separate target though - they should be in libHalide

**Comment by delcypher** [comment]
@abadams Sure I can remove the defines. All I've really done is made it explicit where the defines are being added, prior to my PR the same thing should have been happening.

I'll add a commit to remove those defines.

Regarding the ``InitialModules`` target I don't really understand this either why it's this way either. The ``libHalide`` target seems to call into code that appears ``InitialModules`` so it would make more sense for there just be a single library.
It would be possible in CMake to have all the generated ``cpp`` files (that are currently used for ``InitialModules``) be sources for the ``libHalide`` target rather than a separate ``InitialModules`` target.
@abestephensg thoughts? Is there any reason to not to do this?

**Comment by delcypher** [comment]
@abadams The defines have been removed. Regarding the issue with ``InitialModules`` being separate: this issue is orthogonal to this PR so can that be addressed in another issue? I have the fixes for the tutorials (Linux, Windows and OSX) and apps (Linux and OSX only) ready so I'd like to open a new PR but I can't until this PR is merged into ``master`` due to those fixes being dependent on this PR.

**Comment by abadams** [comment]
Sure. I mostly asked because I was confused.

**Pull request merged**
