### PR TITLE
Small refactoring of CodeGen classes to fix naming of CodeGen, make LLVM logic common.

### PR DESCRIPTION
**Pull request by zvookin**
This PR makes the naming of our CodeGen classes a bit more logical and eliminates duplicated code in compiling for LLVM. I originally started on this while tracking down the optimize_module crash, which turned out to be something else, but I feel this is an improvement to the code and sets up some other changes as follows:

1) Adding a top-level CodeGen class which is independent of LLVM. This should make some parts of StmtCompiler cleaner and can make it clear that functionality such as function_takes_user_context is not connected to LLVM.

2) CodeGen_Posix should go away. It has nothing to do with Posix and can either be folded in to CodeGen_LLVM, or made into a helper class. (CodeGen_Allocation or some such.)

3) All LLVM specific codegen for GPU backends should be built on Halide IR so that we can do things like call GPU code from the C backend. (There is not much of a use case for doing this from C, but it makes a lot of sense for a JavaScript backend, which I hope we will have.) Hopefully this will allow getting rid of the templated CodeGen_GPU_Host classes.

### CODE REVIEW

**Comment by dsharletg** [comment]
I started trying to merge this PR... it's a pretty ugly merge (massive diffs from entirely deleted code is obscuring meaningful changes that should be kept). I'm tempted to just replicate the changes in a new branch off of master. 

I'll probably do the same thing with the modules branch too.

**Comment by dsharletg** [comment]
I learned git rebase, and it made this merge tractable (with a lot of swearing). I'm going to push it up soon hopefully, then merge gpu_api_naming.

**Comment by dsharletg** [comment]
I think this merge is done, please take a look! Especially @zvookin.

**Comment by dsharletg** [comment]
This branch is now current again... PTAL!

**Comment by abadams** [comment]
What's the distinction between CodeGen.{h,cpp} and CodeGen_Internal.{h,cpp} in this branch? They both seem to be common functionality used by various codegen modules.

**Comment by dsharletg** [comment]
I removed CodeGen.h/cpp and moved its code to CodeGen_Internal.h/cpp, I agree that it makes sense, and everything that was including CodeGen.h was already including CodeGen_Internal.h anyways.

**Comment by abadams** [comment]
I have done a release, so let's get this merged. Looks like there are some merge conflicts to work through though :(

**Comment by dsharletg** [comment]
I just merged it.

**Comment by abadams** [comment]
Ok, I kicked off the windows tests

**Comment by abadams** [comment]
It's passing the tests on Windows.

**Pull request merged**
