### PR TITLE
Attempt to fix nested vectorization gemm performance on new build bot

### PR DESCRIPTION
**Pull request by abadams**
This new schedule is about the same speed as the old one on an M1, but generates much less code, spills less, and avoids the use of tbl instructions in favor of zips.

### CODE REVIEW

**Comment by abadams** [comment]
Looks like this did indeed fix the performance regression on the new buildbot for that specific test:

https://buildbot.halide-lang.org/master/#/builders/81/builds/178

However it seems other things are broken now

**Comment by steven-johnson** [comment]
ugh, looks like my Mac maintenance yesterday broke Python on max-x86-3, that should be easy to fix, but the armbots just pull the source and then fail with no explanation? wtf?

**Comment by steven-johnson** [comment]
looks like the armbot just needed a reboot, working on the other one now

**Comment by steven-johnson** [comment]
Is this ready to land?

**Comment by abadams** [comment]
Yes, failures appear to be unrelated

**Review by steven-johnson — APPROVED** [review]

**Pull request merged**
