### PR TITLE
Add additional check in compute_with for stages within a function

### PR DESCRIPTION
**Pull request by psuriana**
The additional check makes sure that stages of a function are computed with only with one function, and that later stage should be computed with similar or higher stage of function that are computed with at previous stage. 

For example, for the following example:
```
    f(x, y) = x + y;
    f(x, y) += 5;
    g(x, y) = x - y;
    g(x, y) += 10;
```
`f.update().compute_with(g.update(), ...)` is only legal if `f.compute_with(g, ...)` or `f.compute_with(g.update(), ...)` is also specified. This is necessary since the current `realization_order` and `schedule_functions` are done per function instead of per stage. For the above example to be correct, `f.s0` and `g.s0` need to be realized first followed by `f.s1` and `g.s1`.

### CODE REVIEW

**Comment by steven-johnson** [comment]
What's the status of this PR?

**Comment by steven-johnson** [comment]
What's the status of this PR?

**Comment by steven-johnson** [comment]
Is this PR defunct? If so, it should be closed.

**Comment by steven-johnson** [comment]
This PR has been untouched for a very long time. Does anyone else want to take over and finish the work?

**Comment by steven-johnson** [comment]
One more check to see if we should keep this PR open.

**Comment by vksnk** [comment]
I think this is useful change, I can try to update it to work with the current master and see if there any other issues.

**Comment by steven-johnson** [comment]
tagged with 'skip_buildbots' for now; untag if/when we revisit this

**Pull request closed without merging**
