### PR TITLE
Handle negative shifts in CodeGen_C

### PR DESCRIPTION
**Pull request by vksnk**

### CODE REVIEW

**Review by dsharletg — APPROVED** [review]

**Comment by steven-johnson** [comment]
Some opencl failures -- related?

**Comment by vksnk** [comment]
> Some opencl failures -- related?

yeah, it's a real failure. It took me a while to reproduce locally -- for some reason it only happens in cmake build. Looking into it now.

**Comment by vksnk** [comment]
> > Some opencl failures -- related?
> 
> yeah, it's a real failure. It took me a while to reproduce locally -- for some reason it only happens in cmake build. Looking into it now.

Apparently, OpenCL codegen for the case of `int` >> `unsigned int` will cast the second argument to the signed integer and pass it to CodeGen_C which will try to lower signed shift, and pass it back to OpenCL codegen, which will cast again and so on, which is causing infinite recursion.  PTAL.

**Comment by vksnk** [comment]
> Looks sensible, but I don't understand why this would only affect CMake?

Good question, it should affect both. Maybe I messed up something while testing with make.

**Comment by vksnk** [comment]
All tests are green, submitting.

**Pull request merged**
