### PR TITLE
Remove -Wl,--export-all-symbols from CMake+MinGW build

### PR DESCRIPTION
**Pull request by steven-johnson**
This should no longer be necessary as of https://github.com/halide/Halide/pull/2295

### CODE REVIEW

**Comment by abadams** [comment]
I'm not sure cmake+mingw is a tested config, but lgtm.

**Comment by steven-johnson** [comment]
I don't think it is either, but that's the only config I can think of that would make use of this code.

**Comment by steven-johnson** [comment]
FWIW, using the CMake build in a MinGW shell still prefers MSVC to g++ (at least on my system), so I'm not sure if this code was ever exercised in the first place. Pretty sure it shouldn't be necessary anymore at any rate.

**Comment by steven-johnson** [comment]
FWIW: even with -G "MSYS Makefiles", the CMake-under-MinGW doesn't build properly (link errors with or without this patch). Since it's unsupported/untested I'm not going to spend time investigating. Still going to land this patch in the name of minor simplification.

**Pull request merged**
