### PR TITLE
Add RAII utility class for Scope save/restore

### PR DESCRIPTION
**Pull request by steven-johnson**
Many of our visitors/mutators use a pattern of Scope.push+dosomething+Scope.restore; we should prefer to use an RAII class to guard against early-return incorrectness. (This PR is only a partial usage of it; many more possibilities exist for conversion, but first I want buy-in for the name and the concept.)

### CODE REVIEW

**Comment by zvookin** [comment]
Will review in detail. Love the idea, but I think plain "Scope.h" is a bad name for this inside of a compiler.

**Comment by steven-johnson** [comment]
"Scope.h" is a pre-existing file in Halide

**Comment by zvookin** [comment]
Sorry, misunderstood the PR on quick read. The name that's gotta go is "PushScope". One is temporarily binding a name within a scope, but this doesn't actually make a new Scope. (Conceptually every binding could be a new scope, but that is not how this works.) How about "ScopedBinding" or "ScopedBind"?

**Comment by zvookin** [comment]
Sigh, even those names are a bit tricky. The issue is there are two meanings of "scope" here. One is the actual type Scope, which is a collection of Bindings representing names in a scope in our language. The second is the RAII scope implied by this new class. This is simply confusing. "RAIIBinding" is probably close to the right thing, but is fairly ugly.

**Comment by abadams** [comment]
Why "bind"? It's a call to Scope::push with an automatic Scope::pop when the resulting object leaves scope. It's a scoped Scope::push.

**Comment by abadams** [comment]
(our messages crossed)

**Comment by zvookin** [comment]
"It's a scoped Scope::push" and if you don't think the two different meanings of scope in that phrase aren't confusing to someone who doesn't already know *exactly* what is going on... well then I don't know what to say. If you already know what the code is doing, it doesn't really matter what the names are.

**Comment by abadams** [comment]
I don't disagree that "scoped Scope::push" is confusing as a basis for a name to settle on. I was trying to clarify the issue for this discussion.

ScopedBinding?

**Comment by abadams** [comment]
Heh, that's one of the things you already suggested, so perhaps that's a good sign.

**Comment by zvookin** [comment]
The underlying concept is "This name binding applying to the IR has the duration of this C++ object's lifetime." Part of me says "Yeah, that's a totally obvious thing" and part of me says "I'm not precisely sure what that means." The issue comes from C++ practice using "Scoped" as a name for RAII but that word aliases with a different concept inside the compiler. I guess this is sort of a fundamental thing. (E.g. the use of the variable name "klass" to hold the data structure representing a class declaration in a C++ compiler because class is a reserved word :-))

ScopedBinding with a comment above the class explaining this discussion?

**Comment by steven-johnson** [comment]
As we all know, "naming things" is one of the three hard problems in computer science

**Comment by zvookin** [comment]
Fear, surprise, and ruthless efficiency and a fanatical devotion to naming things properly?

**Comment by zvookin** [comment]
LGTM.

**Comment by steven-johnson** [comment]
Failure is unrelated. Merging.

**Pull request merged**
