### PR TITLE
Backport #6471 to release/13.x, bump version to 13.0.2

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Review by alexreinking — APPROVED** [review]
Rebase, don't squash, please.

**Comment by LebedevRI** [comment]
Is there intentionally no tag because it's not actually a .4 yet?

**Comment by alexreinking** [comment]
There should be a tag and release made.

**Comment by alexreinking** [comment]
@LebedevRI - done https://github.com/halide/Halide/releases/tag/v13.0.2

**Comment by LebedevRI** [comment]
Thank you!

**Pull request merged**
