### PR TITLE
Apply simplify_correlated_differences to comparisons too

### PR DESCRIPTION
**Pull request by abadams**
GuardWithIf conditions can include comparisons with correlated values on
each side, e.g. `((x*8) + y)*2 + z <= x*16`. It's worth cancelling them -
in one case @aekul found it avoids an if statement tree in an unrolled
block.

This would be a fairly trivial change by itself, but I did some light
refactoring while I was there to avoid blowing up the number of template
instantiations.

### CODE REVIEW

**Comment by abadams** [comment]
Seems to be breaking on metal. Investigating.

**Comment by abadams** [comment]
Can't repro locally, and didn't repro with the makefile build. Possibly a flake. Rerunning that build

**Comment by steven-johnson** [comment]
Looks good to land.

**Comment by abadams** [comment]
Still needs a review

**Pull request merged**
