### PR TITLE
Update onnx app to Adams2019 autoscheduler and new autoscheduler API

### LINKED ISSUE #7670: Halide AutoSchedule Error
### How to use autoscheduler in the latest version of halide?

##I modified the code in the auto_schedule section of app/onnx/model.cpp by referring to the halide documentation
`std::string auto_schedule(const HalideModel &pipeline) {
    // Generate a schedule for the pipeline.
    Halide::Target tgt = Halide::get_host_target();
    // auto schedule = pipeline.rep->auto_schedule(tgt);
    Halide::AutoschedulerParams autoscheduler_params = Halide::AutoschedulerParams("Adams2019");
    auto schedule = pipeline.rep->apply_autoscheduler(tgt, autoscheduler_params);
    return schedule.schedule_source;
}`

##When I compile and test, the following error occurs
`PYTHONPATH="bin/host/:$PYTHONPATH" python3 -m unittest model_test.py -v
test_empty_model (model_test.ModelTest) ... ok
test_model_with_initializer (model_test.ModelTest) ... ok
test_scalars (model_test.ModelTest) ... ERROR
test_small_model (model_test.ModelTest) ... ERROR
test_tensors_rank_zero (model_test.ModelTest) ... ok

======================================================================
ERROR: test_scalars (model_test.ModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gager/Halide/apps/onnx/model_test.py", line 64, in test_scalars
    schedule = model.OptimizeSchedule()
  File "/home/gager/Halide/apps/onnx/model.py", line 30, in OptimizeSchedule
    return model_cpp.AutoSchedule(self.pipeline)
RuntimeError: Caught an unknown exception!

======================================================================
ERROR: test_small_model (model_test.ModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gager/Halide/apps/onnx/model_test.py", line 36, in test_small_model
    schedule = model.OptimizeSchedule()
  File "/home/gager/Halide/apps/onnx/model.py", line 30, in OptimizeSchedule
    return model_cpp.AutoSchedule(self.pipeline)
RuntimeError: Caught an unknown exception!

----------------------------------------------------------------------
Ran 5 tests in 0.402s

FAILED (errors=2)
`

### PR DESCRIPTION
**Pull request by abadams**
Fixes #7670

This app had rotted, largely because the linux bots don't have the prereqs installed so they weren't testing it. Unfortunately one of the prereqs seems to be the package python3-onnx, which isn't available on the ubuntu distribution installed on the bots (focal fossa).

### CODE REVIEW

**Comment by steven-johnson** [comment]
If python3-onnx is installable via pip that would be easy to correct on the bots

**Comment by steven-johnson** [comment]
Is https://pypi.org/project/onnx/ what we need?

**Comment by steven-johnson** [comment]
(If we can install the right packages, let's do that first and get testing working before we land this)

**Review by steven-johnson — APPROVED** [review]

**Comment by abadams** [comment]
Errors unrelated (they are also occuring on main)

**Pull request merged**
