### PR TITLE
Attempt to make the compiler thread-safe.

### PR DESCRIPTION
**Pull request by abadams**
I believe these are the changes required to make the whole compiler thread-safe. Unfortunately it comes with a 5% slowdown (in compile times) due to the atomic increment/decrement in the shared pointer.

Is a thread-safe compiler worth a 5% slowdown?

### CODE REVIEW

**Comment by abadams** [comment]
I clawed back some of the performance with a move constructor and assignment operator to reduce the number of times we incref/decref. Now the slowdown is in the noise.

**Comment by dsharletg** [comment]
If the slowdown is in the noise, I don't see why we shouldn't do this. The changes look good to me.

**Comment by abadams** [comment]
I'm seeing a 5% compile-time slowdown again on other apps (the fft compilation). @zvookin, do you have an opinion on whether thread-safety of the compiler is worth a 5% slowdown?

We could also conditionalize it on a preprocessor define. You can turn on and off the part that hurts performance by switching RefCount between an ```atomic<int>``` and an ``int``. We'd still need to pick a default value, so I'd rather just make the decision.

**Comment by abadams** [comment]
Per offline discussion, merging this.

**Pull request merged**
