### PR TITLE
Modify benchmark.h to not rely on C++ headers

### PR DESCRIPTION
**Pull request by dsharletg**
This enables usage in Android NDK example apps.

### CODE REVIEW

**Comment by steven-johnson** [comment]
But Android NDK supports C++.

**Comment by dsharletg** [comment]
Not without a lot of bending over backwards, or using an Android.mk file (which I'd rather not do because this app should work on any platform and I don't want two build systems).

**Comment by dsharletg** [comment]
That said, Andrew pointed out this is a low precision clock. I'm going to try to get the C++ standard library working in the NDK rather than try to fix this.

**Comment by dsharletg** [comment]
I found the solution to this: https://github.com/halide/Halide/commit/13170e64fbf1eb4f90c220d26885ae8ba47fa41f

(I think this will also solve a lot of other Android annoyances...)

**Pull request closed without merging**
