### PR TITLE
Add Intel APX and AVX10 target flags and LLVM attribute setting.

### PR DESCRIPTION
**Pull request by zvookin**
Opened for discussion on naming. Probably can land as soon as TODOs are resolved, though LLVM support is still nascent. Likely some new intrinsics patterns can be added.

### CODE REVIEW

**Review by steven-johnson — COMMENTED** [review]
LGTM

**Comment by steven-johnson** [comment]
Looks like legit failures in correctness_simd_op_check_x86

**Comment by zvookin** [comment]
They're spurious in the sense that we cannot turn on AVX10 testing while llvm is still working on it. It won't be testable for a while no matter what.

**Comment by steven-johnson** [comment]
Ah, so this PR won't land until LLVM is ready?

**Comment by zvookin** [comment]
Open question, but the testing will have to be disabled if it does land. It is probably useful to land it early for folks doing early development.

**Comment by zvookin** [comment]
I'd like to go ahead and land this if there are no objections. Pending passing tests, which it should now.

**Comment by abadams** [comment]
There appear to be some TODO(resolve before landing) comments

**Comment by zvookin** [comment]
TODOs should be addressed.

**Review by abadams — APPROVED** [review]

**Pull request merged**
