### PR TITLE
Rewrite test/error to avoid need for special handling in Build files

### PR DESCRIPTION
**Pull request by steven-johnson**
Currently we have to special-case all the expected-to-fail tests in the Makefiles; this is awkward, and (currently) doesn't work at all on Windows if you aren't using msys2 or mingw, as it relies on a shell script to wrap the test.

This PR instead adds HALIDE_EXPECT_DEATH (inspired by GoogleTest): calling this as the first statement in main() re-runs as a subordinate process (via fork() or CreateProcess()), transmuting the exist code appropriately. The upshot is that the outer test only succeeds if the inner test fails, and vice versa, so (from an external perspective) the tests are no different from any other.

### CODE REVIEW

**Comment by steven-johnson** [comment]
Finally clean. PTAL.

**Comment by abadams** [comment]
I'm wondering if it would be slightly better to have roughly the same CreateProcess code replace the shell script - i.e. a binary that runs another binary and reports success if it fails.

It might make debugging easier because the inner binary doesn't do any weird forking.

**Comment by zvookin** [comment]
LGTM.

**Comment by steven-johnson** [comment]
@abadams So basically your proposal is to replace the previous expect_failure.sh with expect_failure[.exe]? That would be an improvment over the previous status quo (since it would work without bash), but would still make the test/error cases "special"; you couldn't just run them standalone like ~all other tests (instead of `./bin/error_foo` you'd need something like `./bin/expect_failure ./bin/error_foo`. This isn't necessarily a dealbreaker (it can be wrapped in the build system) but is still kind of warty.

[Side note: the test/warnings directory still has a similar problem in that it needs to have its output verified by the build file; thus the test runs under CMake are actually not meaningful yet.]

**Pull request closed without merging**
