### PR TITLE
Metal: Allow client to control to command buffer

### PR DESCRIPTION
**Pull request by shoaibkamil**
This PR adds two new override points to the Metal runtime, which allow Halide to share a command buffer with client code.  The default implementation does not change the current behavior.

This is motivated by scenarios where a single client thread wants to enqueue a mixture of Halide and non-Halide work, or when a client thread wants to enqueue multiple Halide operations on the same command buffer.

CC @zvookin @slomp

### CODE REVIEW

**Comment by shoaibkamil** [comment]
Investigating build failures (looks like I may have screwed up a Makefile rule).

**Comment by zvookin** [comment]
Can you say a bit about whether this is for performance or to satisfy a correctness constraint?

**Comment by shoaibkamil** [comment]
@zvookin This is intended mostly for performance-- giving clients control of when command buffers are created/committed allows more flexible usage for when Halide pipelines are small.

**Comment by slomp** [comment]
Just adding that with the now ubiquitous support for multiple asynchronous queues on GPUs, having this flexibility in filling/submitting command buffers is very important to allow clients to interleave work in the GPU effectively.

**Comment by shoaibkamil** [comment]
@steven-johnson It looks like the CMake build failed because `TEST_OPENCL` is true in the CMake build but not in the Makefile build.  I'm not sure if the buildbots are supposed to test OpenCL or not, but I suspect not.

**Comment by steven-johnson** [comment]
Yeah, this is weird; my reading of the Makefile made it look like TEST_OPENCL defaults to on, but clearly I'm wrong. Investigating.

**Comment by steven-johnson** [comment]
Oh, I see: the Makefile logic is to enable TEST_OPENCL (etc) only if WITH_OPENCL is defined *and* HL_TARGET contains the opencl feature. In CMakeLists.txt, change the OR to AND:
```
if(TARGET_METAL AND HL_TARGET MATCHES "metal")
  add_definitions(-DTEST_METAL)
endif()
if(TARGET_OPENCL AND HL_TARGET MATCHES "opencl")
  add_definitions(-DTEST_OPENCL)
endif()
if(TARGET_CUDA AND HL_TARGET MATCHES "cuda")
  add_definitions(-DTEST_CUDA)
endif()
```

**Comment by shoaibkamil** [comment]
#2587

**Pull request closed without merging**
