### PR TITLE
Clean up halide_handle_traits

### PR DESCRIPTION
**Pull request by steven-johnson**
No functional change, just consolidation & simplification of code.

### CODE REVIEW

**Comment by zvookin** [comment]
Just did a quick glance. Can't say I've grokked it, but it looks ok. Will try to fully understand it. I think we need at least a few comments. Not sure what is part of an exposed API, thus needed doc comments, but at least consider whether there's anything you want to write down for our future selves.

**Comment by steven-johnson** [comment]
Re `halide_handle_traits has to go outside the Halide namespace due to template resolution rules` -- I don't remember why this is. What rules prevent us from putting it in a namespace?

**Comment by dsharletg** [comment]
From the context, my guess would be some template/overload resolution issue. But I don't really know, does nothing go wrong when it is in a namespace?

**Comment by steven-johnson** [comment]
> does nothing go wrong when it is in a namespace?

Don't know: haven't tried yet.

**Comment by steven-johnson** [comment]
PTAL

**Pull request merged**
