### PR TITLE
[vulkan] Fix SPIR-V IR references causing leaks

### PR DESCRIPTION
**Pull request by derek-gerstmann**
Removed parent/owner back references (which weren't actually needed)
Fixed ownership transfers
Explicitly destruct and clear contents

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]
Thanks so much for this! LGTM pending green.

**Comment by derek-gerstmann** [comment]
> Thanks so much for this! LGTM pending green.

Thanks for finding these!  The ASAN toolchain is a massive help!

**Comment by abadams** [comment]
I believe after this PR and the memoize fix one (which is still failing on windows, unfortunately), that's all the leaks.

**Comment by steven-johnson** [comment]
> I believe after this PR and the memoize fix one (which is still failing on windows, unfortunately), that's all the leaks.

Sweet! LMK how the Windows issues go.

**Pull request merged**
