### PR TITLE
Support buffer sizes of 2^63 - 1 bytes on 64-bit systems

### PR DESCRIPTION
**Pull request by tdenniston**
This PR implements initial support for buffers of size 2^63 - 1 on 64-bit systems. Previously the limit was 2^31 - 1 bytes. The extents of a buffer must still be < 2^31 - 1, but the overall buffer size can now exceed 2GB.

The initial implementation upcasted buffer coordinates to 64 bit integers during storage flattening. This would have required making many changes to following passes and the simplification system. So, the current implementation is as a separate lowering pass that occurs after all other lowering passes.

All internal tests pass, and running `make test_correctness` on my 64-bit system reports all tests pass. However, I don't have access to a 32-bit development environment, so I have not run the correctness tests for 32-bit targets.

### CODE REVIEW

**Comment by tdenniston** [comment]
I see some of the CI tests have failed. I'm guessing it's because the modified tests now require 4GB of memory to allocate buffers. Is there a better way to write those tests that doesn't actually require >2GB of memory? Also, is there a way to get interactive access to the machines that the tests failed on?

**Comment by abadams** [comment]
I think this approach is dangerous - it less a bunch of IR propagate
through lowering and then changes the meaning of it by upgrading it to
64-bit.

E.g. what if we change an earlier pass to make the rewrite: (x*xstride +
y*ystride)*16 -> (x*xstride + y*ystride) << 4. It's legal in isolation, but
it'll break the logic in UpcastBufferIndices, which only looks through
certain IR nodes. Or what if we pull a common (32-bit) subexpression out of
some load and store indices and make it a let statement somewhere much
further away.

I don't think the original approach will require that many changes to
simplification rules. The problematic one you mentioned in an email
(i64(ramp(a, b, w)) -> ramp(i64(a), i64(b), w) is valid when a and b are
types with undefined overflow (i.e. i32 or i64).

Either way there are problems with large buffers that I don't know yet how
to solve:
1) strides are still 32-bit, so this can't actually give you very large
buffers... I'm at a loss for how to work around this without making
buffer_t entirely 64-bit.
2) either approach risks slowing down in the common cases (because
vectorized 64-bit operations on coordinates are slower than vectorized
32-bit operations). Maybe this is not actually a problem - we'll need to
check performance of a bunch of stuff.

**Comment by tdenniston** [comment]
I see your point regarding upstream rewrites potentially breaking UpcastBufferIndices. I still have my other attempt in a separate branch, so I'll submit a separate PR for that once the tests are passing so we can compare.

I'm not sure that 32-bit extents/strides are a limiting factor though. Even for a 2D buffer, you can't max out the 32-bit extent without exceeding a 64-bit byte index. E.g. a square 2D buffer with 4-byte pixels can have a maximum x and y extent (and therefore y stride) of `sqrt(((1<<63)-1)/4) = 1518500249` which fits in a 32-bit signed integer. This is already an impractically enormous (8192 petabyte) buffer.

**Comment by abadams** [comment]
32-bit extents are probably fine, but I was worrying about strides for buffers of sizes like 2^20 x 2^20 x 3

i.e. a 2^20 x 2^20 color image stored planar. The stride on the last dimension is 2^40.

For a very large buffer, the outermost dimension needs to be one of the non-trivially-sized ones for this approach to work.

**Comment by abadams** [comment]
Superseded by #952

**Pull request closed without merging**
