### PR TITLE
Provide a minimum OS version for MachO objects

### LINKED ISSUE #7941: [macos] XCode 15 issues warnings for object files when linking
It appears XCode 15 now includes a custom (undocumented) version of LD which expects object files to be generated with a version number specified in the OS part of the LLVM target triple, otherwise it issues warnings like:

```
ld: warning: no platform load command found in 'static-lib.a[0](object-file.o)', assuming: macOS
```

This appears to have hit the JuliaLang team too, and they discovered they had to update their target triple for AOT compilation to include the OS version:
https://github.com/JuliaLang/julia/pull/51830

More discussion here:
https://github.com/JuliaLang/julia/issues/51562

So, it appears we may need to update the LLVM object file output to include the darwin/macos minimum deployment version in the target triple to be compatible with XCode 15 and future Apple toolchains.

### PR DESCRIPTION
**Pull request by alexreinking**
This gives LLVM enough information to generate a "platform load-command" in the MachO object file.

Frustratingly, there is not a simple API that sets this directly; it _must_ be passed in the os name.

Fixes #7941

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]
LGTM but please add a comment echoing the info in the PR description.

**Comment by alexreinking** [comment]
Done! As I'm thinking about this, we should probably do something similar for iOS

**Comment by alexreinking** [comment]
@steven-johnson -- I changed the approach to use the LLVM-computed minimum compatible version (e.g. 11 on macOS/ARM). This should generalize to iOS, watchOS, tvOS, etc.

**Review by steven-johnson — APPROVED** [review]

**Comment by steven-johnson** [comment]
I think this may have injected a link error in google when building for the iOS Simulator (which is not considered macOS by the linker), but I don't have time to diagnose before leaving for vacation -- hoping @vksnk can look at it next week

**Comment by vksnk** [comment]
Yes, can confirm this is causing a link error like:

``` ld64.lld: error: _some_binary_name_ has platform macOS, which is different from target platform iOS Simulator ```

**Comment by alexreinking** [comment]
> Yes, can confirm this is causing a link error like:
> 
> `ld64.lld: error: _some_binary_name_ has platform macOS, which is different from target platform iOS Simulator`

Well, that is vexing... can you try printing the LLVM target's OSName before and after the snippet here that injects the version information? I wonder if `iOS` is somehow being clobbered into `macOS`?

**Pull request merged**
