### PR TITLE
Add Buffer.defined() checks in Python bindings

### PR DESCRIPTION
**Pull request by BachiLi**
Currently the following Python code causes segmentation fault:
```
import halide as hl
b = hl.Buffer()
print(b)
```
Is there any reason why we want the users to construct an empty buffer? If no I propose just to remove these constructors in Python.

### CODE REVIEW

**Comment by steven-johnson** [comment]
I don't want to just disable it without finding out why it is broken.

**Comment by BachiLi** [comment]
> I don't want to just disable it without finding out why it is broken.

I think it is because `Buffer.__repr__()` (https://github.com/halide/Halide/blob/master/python_bindings/src/PyBuffer.cpp#L534) calls `get_buffer_shape` and `Buffer.buf` is `nullptr`. I can fix that too. Which one do you think is better?

**Comment by steven-johnson** [comment]
I'd strongly vote for having `get_buffer_shape` just return an empty vector if the `Buffer` is invalid.

**Comment by BachiLi** [comment]
I messed up the commits when trying to rebase. Let me open a new PR.

**Pull request closed without merging**
