### PR TITLE
Linear algebra cmake

### PR DESCRIPTION
**Pull request by ibtaylor**
I wanted to get this building in the hopes that maybe more people would have a look at it.

It may fail the build bot since there are lots of warnings regarding the use of deprecated methods (code rot).

# Changes
The `CMake` differs from the `Makefile`
- Removed `openmp` dependency by disabling `openmp` in `eigen`.
- Should be easier to add additional blas libraries.
- Output isn't as nice
- More high-level targets for running subsets of benchmarks (not very clean, maybe a better way?)

Updates to Makefile:
- only `halide_benchmarks` depends on `halide` and `halide_blas`

# Benchmarks
(I can move this to a separate issue if needed.)
I'm concerned about the inconsistencies in the benchmarks. I've been trying to pinpoint why I get drastically different results in different runs of the same compiled code. Hoping one of the core halide devs can shed some light on this. I get the same inconsistencies whether I build everything using the `Makefile` or `CMake`

For instance, running multiple times:
` make halide_l1_benchmark_sscal 2>&1 | grep Halide`
I get
```
Package     Subroutine    Size             Runtime     GFLOPS
  Halide              sscal      16            0.004645             6.88914
  Halide              sscal      64            0.007402             17.2928
  Halide              sscal     288            1.411560            0.408059
  Halide              sscal    1056            0.079586             26.5373
  Halide              sscal    2080            0.148849             27.9477
```
followed by
```
  Halide              sscal      16            0.085663            0.373558
  Halide              sscal      64            0.007501             17.0641
  Halide              sscal     288            1.401733             0.41092
  Halide              sscal    1056            5.143311             0.41063
  Halide              sscal    2080           10.106445            0.411619

```

I tried many, many things to try and get consistent benchmarks:
- disabling ASLR
- pinning all the benchmarks to run from the same CPU via taskset
- disabling frequency scaling
- replacing Halide::Tools::benchmark use of `high_resolution_clock` with `steady_clock`, `clock()`, `clock_gettime()` etc
- running with more samples and more iterations
- calling `sched_yield` right before the benchmark (hoping benchmark within full time slice)
I'm at a loss at what is causing these strange results. It seems like the results are either consistently good, or consistently bad within the programs execution. I've heard that fPIC can possibly enable 

FYI, I'm using
clang-4 with llvm-4 libs linked against libc++

### CODE REVIEW

**Comment by ibtaylor** [comment]
So, I finally found this conversation https://software.intel.com/en-us/forums/intel-isa-extensions/topic/710248 
I'm not sure the exact cause (if the source is denormal numbers), but it seems related.

With code in the branch, I now get a more-or-less consistent:
```
  Halide              sscal      16            0.004706             6.79997
  Halide              sscal      64            0.007755             16.5059
  Halide              sscal     288            0.024136             23.8652
  Halide              sscal    1056            0.079185             26.6716
  Halide              sscal    2080            0.148056             28.0975
```

Are Flush-To-Zero (FTZ) and Denormals-Are-Zero (DAZ) options adjusted by Halide? I did not see any special handling in my searching (except for cuda).
Seems like Eigen pays attention to this: https://github.com/RLovelett/eigen/blob/ebc657d1bc26aebd77ac9ecc817def4d92120b77/bench/btl/generic_bench/btl.hh#L49

**Comment by ibtaylor** [comment]
I don't think fast-math is the real solution, I was just trying to attain consistent performance. I'm really interested in hearing what halide devs think a reasonable solution to this is.

**Comment by abadams** [comment]
Halide-generated code does the equivalent of -ffast-math in how we configure llvm, but I'm totally unfamiliar with how LLVM lowers that directive.

The linear algebra app has a bunch of dependencies. Looks like our travis config doesn't have them installed. I'm not sure we should gate PRs on these all existing (e.g. it might be hard to get them all on the arm or windows buildbots). Can the cmake build be made robust to this (e.g. skipping eigen_benchmarks if eigen is not found)?

**Comment by ibtaylor** [comment]
The idea is to generate benchmarks for whatever is found. I can imagine for instance, `cublas`, `intel`, or any number of others. If nothing is found, it should only build the benchmarks for halide. I don't believe the benchmark targets are being added to `ALL`, so they will only run if the target is explicity made, e.g. `make [benchmark_target]`.

It seems like the test_halide_blas requires `cblas.h` and I'm addressing that now. I guess unless this dependency is relieved, the travis build will not ensure that the `linear_algebra` subproject continues to build if a `blas` is not available on the system.

Can you point me at where that halide equivalent `-ffast-math` would be? I can see if maybe it isn't being done on my machine for whatever reason. (It doesn't seem so). Do you know off-hand if that behavior must be communicated to halide explicitly?

**Comment by abadams** [comment]
I was referring to https://github.com/halide/Halide/blob/master/src/CodeGen_Internal.cpp#L397

That may well not set those flags though. I'm not sure we want to emit flag-setting code in every generated filter, no matter how small. Hrm.

**Comment by zvookin** [comment]
The idea is that the caller should manage any global processor state such
as FTZ and DAZ. Ian is correct that we should control for this in the
benchmarks and apps that use these filters. Especially if it is required to
get an apples to apples comparison with other packages such as Eigen. (I.e.
if I understand the Eigen link correctly, their benchmark sets these flags
to enable the fastest operation.)

It does require some care to set the flags as much older processors don't
support all of them and it is possible to crash setting them on the wrong
processor. My recollection is that on recent Intel processors, these flags
aren't huge needle movers unless one is actually using values on the edges
of IEEE representation, but that there were a few processors where changing
the mode did make a noticeable difference in performance in and unto itself.

If the benchmarks are using denormals and such, we should perhaps fix that
too...

**Comment by ibtaylor** [comment]
I can get behind it being up to the caller. I guess it does seem like it deserves an entry in a FAQ though if people notice inconsistent benchmark results.
Are there other instructions that can take more clock cycles depending on the operands?
I'm trying to build a real time system and this behavior really surprised me.

@zvookin As far as how the actual benchmark should behave, I would think that we would want to repeatedly call the function with the same exact input each time. That's a little annoying due to it being an in-place operation, but I can take a look at those cases if you agree that we should restore the buffer to contents identical to the first call. This may require some changes to `halide_benchmark.h` or using a modified version of the benchmark function in `linear_algebra`.

Thoughts?

**Comment by ibtaylor** [comment]
@abadams so, is this mergeable? Or should I bundle additional changes like some of what @zvookin and I were talking about? I could always do that in a later PR.

**Comment by abadams** [comment]
I want to stage merging this through an in-repo PR, so that I can get it working on all the buildbots (and install any missing blas libraries on them). Stay tuned.

**Comment by ibtaylor** [comment]
okay. I mainly tested with openblas, and atlas.

**Comment by abadams** [comment]
Merged as #2137 

Thanks again.

**Pull request merged**
