### PR TITLE
AVX2 detection in calculate_host_target appears to be wrong

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by zvookin** [comment]
LGTM. To add a bit more detail, this looks like it was signaling that AVX2 is available on machines that have VMX.

**Comment by steven-johnson** [comment]
Something is odd -- with this in place I'm now having correctness_simd_op_check fail on my OSX machine. We should roll this back and investigate further,

**Comment by steven-johnson** [comment]
OK, this may have actually revealed an underlying bug: my MacBook has AVX2, but calculate_host_target() wasn't reporting it as such before, so simd_op_check wasn't looking for AVX2 instructions. Now that it's looking for them, it isn't finding everything it expects to find.

**Comment by abadams** [comment]
I think correctness_simd_op_check may have avx2 bugs, which have never been caught because it's never been run, due to the original mistake :(

**Comment by steven-johnson** [comment]
sounds like a separate issue then. are you already investigating?

**Comment by abadams** [comment]
yes, stay tuned

**Comment by abadams** [comment]
Should be fixed.

**Pull request merged**
