### PR TITLE
Kernhanda kernhanda/cmake package pr

### PR DESCRIPTION
**Pull request by abadams**
Opening #2738  as a within-repo PR to get the buildbots to test it.

### CODE REVIEW

**Comment by abadams** [comment]
Looks like the resize app doesn't use no_runtime in its cmake build, so we're getting multiply-defined symbols. Not sure of the right way to fix this. @steven-johnson ?

**Comment by kernhanda** [comment]
How can I repro the issue you're seeing?

**Comment by steven-johnson** [comment]
@abadams Haven't tried this on Windows yet but from inspection I don't see the issue re resize app; it looks more or less the same as the other CMake generator-using apps.

**Comment by abadams** [comment]
So the halide_library_from_generator rule separately compiles a runtime? I'm getting duplicated symbol errors on windows of the form:

resize_linear_uint16_up.lib(resize_linear_uint16_up.lib.obj) : error LNK2005: _ceil_f64 already defined in resize_box_float32_up.lib(resize_box_float32_up.lib.obj) [D:\b\worker\win-32-testbranch-401\halide-build-Release\apps\resize\resize.vcxproj]

Hrm, those math functions are done with inline linkage, and don't go into the shared runtime. Maybe this is related to the win32 shenanigans we do.

**Comment by steven-johnson** [comment]
`halide_library_from_generator` runs a Generator to produce an aot-compiled library. IIRC it includes a runtime by default, unless you specify the no_runtime feature.

**Comment by steven-johnson** [comment]
Wait, ignore: `halide_library_from_generator` sets no_runtime by default.

**Comment by abadams** [comment]
ok, so then this is definitely related to the inlined math functions that don't go into the runtime.

**Comment by abadams** [comment]
@kernhanda You may be able to repro with a 32-bit build. Looks like win-64 worked fine.

The simplest fix may be to blacklist this app on windows and add a comment referencing the discussion here.

**Comment by kernhanda** [comment]
Is this building with VS 2017 or VS 2015?

**Comment by abadams** [comment]
2015. The log is here: https://buildbot.halide-lang.org/master/#/builders/26/builds/217/steps/13/logs/stdio

**Comment by abadams** [comment]
Those functions are marked alwaysinline, but they're not being inlined away on win-32:

```
abadams@abadams-mbp:~/projects/Halide/apps/resize
$ ./bin/resize.generator -g resize -o /tmp -e assembly target=linux-x86-32-no_runtime interpolation_type=lanczos input.type=float32 

abadams@abadams-mbp:~/projects/Halide/apps/resize
$ grep sin_f64 /tmp/resize.s 

abadams@abadams-mbp:~/projects/Halide/apps/resize
$ ./bin/resize.generator -g resize -o /tmp -e assembly target=windows-x86-32-no_runtime interpolation_type=lanczos input.type=float32 

abadams@abadams-mbp:~/projects/Halide/apps/resize
$ grep sin_f64 /tmp/resize.s  | head -n10
	.def	 _sin_f64;
	.section	.text,"xr",one_only,_sin_f64
	.globl	_sin_f64
_sin_f64:                               # @sin_f64
	calll	_sin_f64
	calll	_sin_f64
	calll	_sin_f64
	calll	_sin_f64
	calll	_sin_f64
	calll	_sin_f64
```

**Comment by kernhanda** [comment]
@abadams can you merge the latest commit into PR branch to make sure x86 VS issues are fixed? Should I create an issue for the resize app?

**Comment by abadams** [comment]
done

**Comment by kernhanda** [comment]
Needs to be done once more, sadly. Build errors for `camera_pipe` were hidden by `resize`.

**Comment by kernhanda** [comment]
I think we're good to go with this (finally). Yay :)

**Pull request merged**
