### PR TITLE
Fixed the regularization for BGU.

### PR DESCRIPTION
**Pull request by mcourteaux**
See discussion in #7681.

This patch simplifies the regularization. The most important takeaway is in the comment of the changed code, and a thought I had: https://github.com/halide/Halide/issues/7681#issuecomment-1638095230 :

 > The only thing I'm not sure about is that I changed it to regularize towards the identity function, instead of "towards the average gain in the cell". The problem I have with "the average gain" is that you also need samples to compute the average gain, which is exactly the problem being solved.

@jiawen @abadams I don't know if you want to validate the result by running the experiment setup of your paper? I guess that will be a more formal test.

### CODE REVIEW

**Comment by mcourteaux** [comment]
To compare the image I reported originally:

(before) https://user-images.githubusercontent.com/845012/253539155-09c73346-563f-4580-b781-089f4b0068ad.jpg

(after) https://user-images.githubusercontent.com/845012/253946895-792e6941-8cb4-475d-9a6c-95d48857d99c.jpg

Open both and toggle back and forth in two tabs. Result looks identical, except for the regularization artifacts.

**Comment by abadams** [comment]
Your argument about the original regularization makes sense to me. I'd appreciate @jiawen 's take on it though.

**Comment by steven-johnson** [comment]
ASAN failures are unrelated

**Comment by steven-johnson** [comment]
Ready to merge?

**Review by abadams — APPROVED** [review]

**Comment by mcourteaux** [comment]
:partying_face:

**Pull request merged**
