### PR TITLE
[Windows] Copy Halide.dll when building generators

### PR DESCRIPTION
**Pull request by kernhanda**
For Windows builds, copy Halide.dll to the directory where generators
are built and run. This is especially necessary if Halde is not
installed in a system-wide manner.

### CODE REVIEW

**Comment by steven-johnson** [comment]
This is a little troubling. Surely there's a way we can set a search path to point to the Halide.dll we need?

**Comment by abadams** [comment]
I think PATH does that on Windows, right?

**Comment by slomp** [comment]
Yeap, something like this should do:
`SET PATH=<Halide-dll-path>;%PATH%`
It is also possible to specify environment variables in the Visual Studio Project `vcproj` files.

**Comment by kernhanda** [comment]
Unfortunately, Windows doesn't have anything like rpath. There are a few alternatives, each with their drawback:

1. Try to modify the PATH environment variable within the CMake script. The downside of this is that it is transient. If the user were to run the exact same command outside of CMake, it would result in an error message that's fairly obtuse about the actual issue.

```shell
[11:56::42 A] C:\foo\build [kerha/halide/test ↑2 +1 ~3 -0 !]> C:/foo/build/bin/Debug/HalideTest.generator_binary.exe -e static_library,h,assembly,bitcode,stmt,html -o C:/foo/build/Debug/genfiles/HalideTest_gen -g HalideTest -f HalideTest_gen -x .s=.s.txt,.cpp=.generated.cpp target=host-no_runtime
User error triggered at C:\code\Halide\src\Generator.cpp:949
Condition failed: is_valid_name(name)
Error:
Invalid Generator name:
```
2. Write a batch script that's generated at build time that wraps the generator and sets the environment variable. This just seems brittle and convoluted.
3. Modify the CMake `halide_generator*` functions to take an additional boolean parameter that specifies whether to copy the DLL or not. This is exposing a platform specific problem to everyone.

For better or for worse, copying DLLs to the directories that contain executables that use them is fairly common. See https://msdn.microsoft.com/en-us/library/8kche8ah.aspx. Usually Visual Studio takes care of this for Windows developers, but here we have to do the work ourselves.

Thoughts?

**Comment by kernhanda** [comment]
Ping. Thoughts on what we should do here? I can do the first alternative (modifying the PATH variable within CMake only), but I predict that some users will file issues not understanding why they can only execute the generator executables through CMake.

**Comment by steven-johnson** [comment]
Sorry for delay in responding. I'm going to have to read the linked you posted and do some pondering to convince myself this is ok.

**Comment by steven-johnson** [comment]
The linked MS document talks about what DLLs from MSVC you might need to redistribute, but not about the issue of needing to copy already-on-your-system DLLs to a different directory.

**Comment by kernhanda** [comment]
Apologies for the delay. Please see https://msdn.microsoft.com/en-us/library/dd293574.aspx for a more explicit example.

There are three types of library deployments in Windows:
* Central (Installing in C:\Program Files)
* Local (in the same folder)
* Static library linkage

> When you deploy a Visual C++ application to another computer, you must install both the application and **any library files it depends on.** (emphasis mine)
 
> In local deployment, library files are installed in your application folder together with the executable 

There are explicit references to the VC libraries, but the guidance stands for any libraries.

Intel also recommends the same for their IPP library: https://software.intel.com/en-us/articles/intel-integrated-performance-primitives-intel-ipp-for-windows-deploying-applications-with-intel-ipp-dlls (specifically, in the section titled "Deploying the Application"). There's a handy table in there:


>  | System PATH | Permissions
>-- | -- | --
>%SystemDrive%\WINDOWS\system32 | This folder is listed on the system PATH by default. | >Administrator permissions may be required to copy files to this folder.
>Application Folder or Subfolder | Windows will first check the application folder for the DLLs. | Special permissions may be required.
>Other Folder | Add this directory to the system PATH. | Special permissions may be required.

Since we don't want to necessarily install Halide.dll in the user's path, especially during development, the only real option is the application folder.

**Comment by kernhanda** [comment]
Ping. :) Let me know if this is still not acceptable. If it isn't, would you like me to change it so that the PATH variable is modified within the CMake script only?

**Comment by steven-johnson** [comment]
Sorry, I just haven't had time to think about it. I don't pretend to be a Windows expert (I just usually draw the short straw of doing Windows stuff recently). I have to admit that this seems Really Really Weird to me, but if it's genuinely Best Practice on Windows, well, that's what we're stuck with. Anyone else want to chime in?

**Comment by abadams** [comment]
I am happy to defer to Kern on Windows-related topics

**Comment by steven-johnson** [comment]
Just want a clean Travis build before merging.

**Pull request merged**
