### PR TITLE
Remove OpenGLCompute

### PR DESCRIPTION
**Pull request by steven-johnson**
This was supposed to be removed in Halide 17 (oops), removing for Halide 18

### CODE REVIEW

**Review by shoaibkamil — APPROVED** [review]
LGTM, thanks for doing this!

@TH3CHARLie Do we need to bump the serialization version?  I'm not sure what our approach has been when deprecating features (maybe this is the first time since serialization was added).

**Comment by steven-johnson** [comment]
> LGTM, thanks for doing this!
> 
> @TH3CHARLie Do we need to bump the serialization version? I'm not sure what our approach has been when deprecating features (maybe this is the first time since serialization was added).

IMHO we should probably bump the version for every Halide release, regardless

**Comment by TH3CHARLie** [comment]
> LGTM, thanks for doing this!
> 
> @TH3CHARLie Do we need to bump the serialization version? I'm not sure what our approach has been when deprecating features (maybe this is the first time since serialization was added).

I think anything that changes the serialization definition needs to bump the serialization version, on the minor number(i.e. 0.1.0 -> 0.1.1). And second to Steven's comment, we should bump the serialization version number on every major release.

**Comment by steven-johnson** [comment]
> > LGTM, thanks for doing this!
> > @TH3CHARLie Do we need to bump the serialization version? I'm not sure what our approach has been when deprecating features (maybe this is the first time since serialization was added).
> 
> I think anything that changes the serialization definition needs to bump the serialization version, on the minor number(i.e. 0.1.0 -> 0.1.1). And second to Steven's comment, we should bump the serialization version number on every major release.

https://github.com/halide/Halide/pull/8080

**Comment by TH3CHARLie** [comment]
One thing I found about this PR is that, the serialization version numbers help users to find out they are deserializing from an old binary pipeline. But on the other hand, if you are using an old Halide build with a updated binary pipeline, the code may crash before we start to check the version numbers (because of a format change in this PR in particular): https://github.com/halide/Halide/blob/9a740b584e63cc67e841f134d61d79502e973252/src/Deserialization.cpp#L1405 (GetPipeline would crash internally here I believe)

**Pull request merged**
