### PR TITLE
Rework MSAN support to actually invoke the LLVM MSAN passes on generated code

### PR DESCRIPTION
**Pull request by steven-johnson**
…(including Halide code and runtime code) rather than simply annotating buffers; this provide meaningful checks for the cases in which you pass uninitialized buffers to Halide code.

Note that this means MSAN code is now much slower than before, but that's OK.

For the record, note also that it's tricky to build Halide in a way to use MSAN successfully:
- LLVM only supports MSAN on BSD+Linux (but not OSX)
- Mixing GCC and Clang tends to result in failure, so the usual recipe of defaulting to the Linux system compiler (typically GCC) for test harnesses will end in weird compile failures
- MSAN doesn't attempt to work well with either JIT or -O3, so most of our testing infrastructure is useless in this mode

(These objections were already the case; I'm just noting them for reference.)

### CODE REVIEW

**Comment by zvookin** [comment]
Is the define_extern issue on the bounds query path? Does the calling code initialize the entire buffer? Is the extern code compiles with MSAN as well? I can see this case being a bit tricky as theoretically the extern is supposed to fill in the values and MSAN could be detecting a failure to do so. (IIRC Halide is supposed to provide an acceptable default for all values however.)

**Comment by steven-johnson** [comment]
Added assert-fails for trying to use JIT with MSAN in the Target. (Considered making it a disable-and-warn, but apparently even using the MSAN runtime with our JIT code is crashy, and since the MSAN release notes warn up front that it doesn't even try to work with JIT, probably better to make it clear to the user that this is a known issue.)

**Comment by steven-johnson** [comment]
FYI: I think this is basically ready to land; I'm going to wait for the Buildbots to come back up for full testing, plus I need to do some torture-testing inside Google, but I'm hoping to land this within the next few days. Please speak up if you have concerns.

**Comment by steven-johnson** [comment]
This looks good inside Google. Once the buildbots are back up and we get a clean pass I'm going to land it.

**Comment by steven-johnson** [comment]
So, an update on this: as it stands, this generates too many false positives to land as-is; the problem (as demonstrated by https://github.com/halide/Halide/issues/3148) is that Halide intentionally generates vector loads from memory that is valid-but-maybe-not-computed (e.g., a load of int16x8 from a buffer that has only the first 5 values filled in, because Halide has determined those are the only values that ever affect the output). It appears that MSAN makes this poison the entire register. 

Adding code to detect-and-mask-off-the-trash in this case might be doable but (according to @abadams) would be nontrivial and would *definitely* be something that would be special-cased to MSAN mode only.

(MSAN claims to handle Masked-Load in the proper way, but we can't reliably use that here because it's slower and doesn't work on all types we need.)

Random Thought: would it suffice to add code for MSAN only that zeroes all allocations immediately? (Yes, this is slower, but likely insignificant relative to MSAN slowdown in general)

@alinas -- any thoughts from the LLVM side as to whether this could be made to work in a plausible way?

**Comment by alinas** [comment]
My worry of doing this on the MSAN side, is that you'd then fail to uncover issues like the use-of-uninitialized-value when they are true errors.

I would find it more intuitive to engineer Halide's behavior based on when MSAN is used, and when such behaviors are allowed by Halide. 

E.g., IIUC the situation in #3148 is that vectorization by some factor rounds up to a multiple of the factor, so may load initialized values, and that is WAI. If there's no vectorization, MSAN giving that error would be a valid one. So initializing all buffers to 0 for MSAN may hide real errors.
Whereas if we'd generate a "zero-all" assignment from Halide when using MSAN && only cases where undefined behavior is permitted, then that should remove MSAN errors only for examples like the above. 
I'm not sure how easy it is to define the set of cases when this is permitted, though.

**Comment by abadams** [comment]
Assuming no compiler bugs, it's impossible to have a use-of-uninitialized-value of an internally allocated Func that can affect the output. So using msan to detect that class of thing is pointless for users. We could mark all internal allocations as fully initialized, and then msan would be useful for catching bugs regarding use of uninitialized values in the input buffers. This should not mask any real errors (again, unless there are compiler bugs that make such errors possible).

The exception to the above is if the user explicitly uses the undef() intrinsic. It might be nice to catch bugs related to incorrect usage of it, but I'm really not sure how without false positives from the intentional behavior. Allocating and loading from slightly more memory than is actually computed is pretty common.

**Comment by steven-johnson** [comment]
I'm going to close this PR as it's unlikely that we can land this any time soon. (I'll keep the branch around for reference.)

**Pull request closed without merging**
