### PR TITLE
Fix LLVM 17+ build integration on 32-bit systems

### LINKED ISSUE #7319: dependencies/llvm/CMakeLists.txt incompatible with latest llvm-project
According to https://reviews.llvm.org/D139752#4006602 , latest llvm-project would cause `<command-line>:0:70: error: token "=" is not valid in preprocessor expressions`. According to https://reviews.llvm.org/D139752#4104371 , it's likely a fault in Halide `dependencies/llvm/CMakeLists.txt`.

### PR DESCRIPTION
**Pull request by alexreinking**
Fixes #7319

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]
LGTM, nice find. We should probably circle back to the LLVM patch review to tell them the resolution of this. (Also: is there any point to reporting this to the CMake maintainers as a bug?)

**Comment by alexreinking** [comment]
> We should probably circle back to the LLVM patch review to tell them the resolution of this.

Sure -- I just need to reset my LLVM reviews password...

> Also: is there any point to reporting this to the CMake maintainers as a bug?

If we can minimize the test case to something convincing, then sure.

**Comment by alexreinking** [comment]
I left a comment on the related LLVM issue: https://reviews.llvm.org/D139752#4107678

**Comment by alexreinking** [comment]
Actually, upon closer inspection, it has to do with the presence of an `=` in the list. When there's an `=`, it seems that CMake does not split on spaces automatically anymore. We've never built Halide on AIX or SunOS, which are the only other build scenarios where an = can appear in `LLVM_DEFINITIONS`.

**Pull request merged**
