### PR TITLE
Error out when calling rfactor() after fusing a pure var

### LINKED ISSUE #7854: segfault on rfactoring an RVar produced by fusing a Var with an RVar
This crashes:
```
#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv) {
    Func f;
    RDom r(0, 100);
    Var x, y;
    f(x, y) = 0;
    f(x, y) += r;

    RVar yr;
    Var z;
    f.update().fuse(y, r, yr).rfactor(yr, z);

    return 0;
}

```

I believe the issue is that the rfactor code has to handle splits, but doesn't correctly handle fusing a Var with an RVar to produce an RVar. Also it doesn't do enough validation. This should be an internal assert failure rather than a crash.

### PR DESCRIPTION
**Pull request by alexreinking**
Fixes #7854

### CODE REVIEW

**Comment by alexreinking** [comment]
This needs more work.

1. It doesn't handle a pure var higher up in a tree of fusions; that needs to be fixed somehow
2. I discovered a secondary bug, as follows:

```cpp
#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv) {
    Func f{"f"};
    RDom r({{0, 5}, {0, 5}, {0, 5}}, "r");
    Var x{"x"}, y{"y"};
    f(x, y) = 0;
    f(x, y) += r.x + r.y + r.z;

    RVar rxy{"rxy"}, yrz{"yrz"};
    Var z{"z"};

    // Error: In schedule for f.update(0), could not find remove dimension: r$z
    // Vars: r$x.rxy r$z.yrz x __outermost
    f.update()
        .fuse(r.x, r.y, rxy)
        .fuse(r.z, y, yrz)
        .rfactor(rxy, z);

    f.print_loop_nest();

    printf("Success!\n");
    return 0;
}
```

**Comment by steven-johnson** [comment]
What's the status on this PR?

**Comment by alexreinking** [comment]
> What's the status on this PR?

Not close to ready yet. Need to clear my plate a bit.

**Comment by alexreinking** [comment]
Closing in favor of a new PR

**Pull request closed without merging**
