### PR TITLE
Relax the condition for eliminating host allocation in inject_host_dev_buffer_copies.

### PR DESCRIPTION
**Pull request by jingpu**
The `!finder.touched_by_extern` clause seem unnecessary now because `finder.devices_touched` already tracks DeviceAPI of the extern definition. This clause now prevents the host allocation elimination if a buffer is only touched an extern definition and a normal definition with the same DeviceAPI.

### CODE REVIEW

**Comment by abadams** [comment]
buffers without host allocations are iffy, so I have historically been very conservative about letting them escape to extern stages.

E.g. if there's a host allocation but no device allocation, then copy_to_device has a clear meaning - it makes a new device_allocation. But what does copy_to_host do on a buffer with no host allocation? The cuda implementation looks like it will just crash.

@zvookin thoughts?

**Comment by zvookin** [comment]
I will try to get a look at this soon, but without a test case, it will be very difficult to approve even if the logic is clearly better.

**Comment by jingpu** [comment]
I added a test. PTAL. 
The buildbot didn't run. Are they down?

**Comment by jingpu** [comment]
ping?

**Comment by zvookin** [comment]
Need to figure out the build failures, but there's enough flakiness at the moment that it is likely they're unrelated to this PR. I'd like to convince myself this doesn't break any other cases, but I think I understand why the change needs to be made and that it looks good.

**Comment by jingpu** [comment]
Is it okay to merge? Or should I wait until the build is stable?

**Comment by jingpu** [comment]
I am not sure how to tell whether the failures are due to existing flakiness.

**Comment by steven-johnson** [comment]
None appear obviously related, OK to merge

**Comment by jingpu** [comment]
I cannot reproduce the failure of generator_aot_old_buffer_t locally. Is there any subtlety in the environment setting for the failure?

**Comment by abadams** [comment]
Looks like it's failing for cuda and opencl, so running the test with
environment variable HL_TARGET=host-cuda should be sufficient.

**Comment by jingpu** [comment]
I think I understand the failure. It is because `finder.devices_touched` only tracks the output of an extern stage but no inputs (https://github.com/halide/Halide/blob/master/src/InjectHostDevBufferCopies.cpp#L92). So this PR was incorrect when a buffer is produced by a device and consumed by host in an extern stage (not inspected in the modified `if` condition).

There are two options to fix it: making `finder.devices_touched` also tracks inputs, which seems to be an quite intrusive chage by itself; tracking the device api touched by extern definitions separately, which essentially extends the currently boolean value `touched_by_extern` to `set<DeviceAPI>`.

I guess the thing I don't understand is the rationale behind the current design of special casing the input and output buffers touched by an extern stage. I see comment "The extern stage is responsible for dealing with any device transitions for inputs"  at Line 93. This seems to be also related to an earlier discussion with @abadams about whether the outer pipeline should set host_dirty on the output of an extern stage, which could limit things we can do in the extern stage (e.g. extern stage dynamically choosing to use an hardware accelerator).

**Comment by abadams** [comment]
I would have to reconstruct the rationale from a careful reading of the code at this point. It's a shame I didn't write it down in more detail :(

The ```set<DeviceAPI>``` solution sounds fine to me.

**Comment by jingpu** [comment]
I think the behavior of the code is that (the code comment) "the extern stage is responsible for dealing with any device transitions for inputs", but, on the contrary, the outer pipeline is responsible for dealing with the transition for the output (e.g. setting the host dirty I mentioned above). I don't understand why it is reasonable because normal loop nests of a pipeline handle both inputs and outputs quite consistently. Maybe there were some historical things?

**Comment by abadams** [comment]
Your line of reasoning makes sense to me. I was probably being overly defensive. The extern stage is going to have to handle input state to function at all, but I don't trust people to correctly describe the output state (e.g. setting host_dirty). I'm totally opening to changing things to make it more consistent w.r.t. outputs and inputs to extern stages.

**Pull request merged**
