### PR TITLE
Add Sanitizer details to README_cmake.md

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Review by alexreinking — APPROVED** [review]

**Comment by TH3CHARLie** [comment]
I'm following the build instructions from this README update, one thing I've noticed is that I can build `fuzz_xxx` tests using the `--preset linux-x64-fuzzer` . But when I want to build the project without explictly enabling fuzzing, it still gives me fuzz tests build errors. Does this has something to do with newly enabled LLVM runtimes? And does this imply you need a different LLVM build specifically for fuzzing? (not compatible with the original one)

so this works:
```
CC=/home/xuanda/dev/llvm16-install/bin/clang  CXX=/home/xuanda/dev/llvm16-install/bin/clang++  cmake -G "Unix Makefiles" -DWITH_PYTHON_BINDINGS=off -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR=/home/xuanda/dev/llvm16-install/lib/cmake/llvm -S . -B build --preset linux-x64-fuzzer
```
this doesn't
```
CC=/home/xuanda/dev/llvm16-install/bin/clang  CXX=/home/xuanda/dev/llvm16-install/bin/clang++  cmake -G "Unix Makefiles" -DWITH_PYTHON_BINDINGS=off -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR=/home/xuanda/dev/llvm16-install/lib/cmake/llvm -S . -B build
```
it gives the below errors
```
[ 86%] Building CXX object test/fuzz/CMakeFiles/fuzz_bounds.dir/bounds.cpp.o
error: current translation unit is compiled with the target feature '-fsanitize=fuzzer-no-link' but the AST file was not
1 error generated.
make[2]: *** [test/fuzz/CMakeFiles/fuzz_bounds.dir/build.make:78: test/fuzz/CMakeFiles/fuzz_bounds.dir/bounds.cpp.o] Error 1
```

**Comment by TH3CHARLie** [comment]
I guess you have to explicitly turn off fuzz tests if you are using compiler that can set `HAS_FUZZ_FLAGS` to true

**Comment by steven-johnson** [comment]
Ah, interesting, looks like an oversight in our support. Let me see if I can smarten it.

**Comment by steven-johnson** [comment]
See https://github.com/halide/Halide/pull/7695

**Pull request merged**
