### PR TITLE
Add preliminary AOT Windows ARM64 support

### PR DESCRIPTION
**Pull request by shoaibkamil**
This was tested manually by:
1) Using a generator to generate a static library
2) Compiling the library along with a C++ file using the library using Microsoft's VC++ toolchain for ARM64
3) Copying the resulting file and running it.

Note that in this PR, `arm-64-windows-jit` is explicitly disallowed.

I did this for a few cases in `test/generator`, but would of course like this to be better tested.  The main hurdles are:
- Microsoft does not have an official toolchain that _runs_ on ARM64 devices.  One must use an x64 device Windows machine to compile for ARM64
- I haven't been able to cross-compile Halide for Windows ARM64 (#5040), which potentially could enable JIT (though some issues remain with upstream LLVM cross-compilation, e.g. [vcpkg cannot correctly cross-compile LLVM for Windows ARM64](https://github.com/microsoft/vcpkg/issues/11973) )

### CODE REVIEW

**Comment by steven-johnson** [comment]
> Microsoft does not have an official toolchain that runs on ARM64 devices. One must use an x64 device Windows machine to compile for ARM64

I will once again beat the same dead horse and say that we should really have a test suite that is capable of running ~entirely on AOT (aside from tests that are truly JIT-specific, of course).

**Comment by shoaibkamil** [comment]
@steven-johnson Somehow I missed this dead horse, but I would definitely support having an AOT test suite.  It would make testing much easier for iOS and possibly Android.

Presumably this would be the tests from `test/correctness` adapted to run AOT?

**Comment by steven-johnson** [comment]
> Presumably this would be the tests from `test/correctness` adapted to run AOT?

Yes, along with `error` `warning` `performance` etc. Aside from cross-compilation, it would make testing of WebAssembly vastly less painful (and more complete), as we wouldn't have to embed a WASM runtime of some sort into Halide.

**Comment by shoaibkamil** [comment]
Not sure why buildbots didn't run, but this won't be tested anyway.

**Pull request merged**
