### PR TITLE
OpenGL: Multiple stages and Update stages

### PR DESCRIPTION
**Pull request by shoaibkamil**
This is another attempt at sanely allowing multiple stages of a pipeline to be scheduled with `.glsl()`, including some kinds of update stages.  Creating the PR now for discussion.

For OpenGL, we pass in the kernel ID as the first parameter to the function; alternatively, we could alter the call to `halide_opengl_run()` but that seemed to require more manipulation (since the arguments are in an array intializer).  I'm happy to change this if it's objectionable.

Specific questions: 
- `bound()` is not a member of `Stage`, and the definition's schedule does not seem to get updated with `bound()` called on the `Func`.  Is there a way I'm missing to check the channel dimension is bounded for a `Stage`?
- This may have broken Renderscript/OpenGLCompute, but I have no way of checking
- Any advice on how to restrict the form of update stages to pre-check if it is of a form we support would be really appreciated.  Clearly OpenGL can't do things like

```
f(g(x,y)) = ...
```

but can do things like:

```
RDom r(0, 5, a, b);
f(r) = ...
```

### CODE REVIEW

**Comment by abadams** [comment]
bounds is a bit overloaded. It bounds the extent computed *and* stored along an axis for all of a func's stages. That's why it's attached to Func and not stage.

I think everything on the left must be a Var or a naked RVar, or a naked RVar plus a constant, or a constant minus an RVar. Is that the constraint? I don't think f(2*r.x, 2*r.y) is doable, right?

**Comment by shoaibkamil** [comment]
I think the constraints are basically what you pointed out:
- LHS must be a `Var`, a naked `RVar`, or a naked `RVar` plus a constant, or a constant minus an `RVar` (though I should add tests to make sure each of these cases works)
- RHS can't reference the `Func`-- perhaps unless it's an `undef` value (since we don't use the `EXT_shader_framebuffer_fetch` extension) 

I'll add tests and write a pass to check the update is computable in OpenGL.

**Comment by shoaibkamil** [comment]
On further thought, the current approach will only work for a Var or naked RVar.  If there's demand to add more, I'm willing to do so, but for now I'd like to just add a pass that checks to make sure it's a Var/RVar and otherwise errors.

Is that reasonable?  And can you suggest the right place to do this (e.g. should it be done within the `.glsl()` function or some other place)?

**Comment by shoaibkamil** [comment]
Closing, see #1755.

**Pull request closed without merging**
