### PR TITLE
Fix problem with HL_HEXAGON_CODE_SIGNING on windows.

### PR DESCRIPTION
**Pull request by ronlieb**
Files need to be in binary mode to avoid truncation issues.

### CODE REVIEW

**Comment by ronlieb** [comment]
@abadams are these test failures expected ?
i.e. ok to merge?

**Comment by abadams** [comment]
They are not expected. We should hold off on merging anything until we figure out what broke.

**Comment by abadams** [comment]
(Possibly #3044 )

**Comment by ronlieb** [comment]
sounds like a good plan, thx, shall wait

**Comment by ronlieb** [comment]
@abadams can you restart the bots for this one?

**Comment by abadams** [comment]
You'll probably need to merge with master to pick up the fix.

**Comment by abadams** [comment]
The hexagon tests are failing now, looks like the prefetch test. Doesn't seem like it could possibly be related to this PR though.

**Pull request merged**
