### PR TITLE
Minor optimization to make_shape_storage

### PR DESCRIPTION
**Pull request by steven-johnson**
Make a constexpr variant of make_shape_storage(), so that call sites that know at compiletime that dimensions <= D don't have to insert code to consider a dynamic allocation

### CODE REVIEW

**Comment by abadams** [comment]
The other option is inlining make_shape_storage so that the branch can resolve statically in cases where it is known statically. Is it not getting inlined in some build?

**Comment by steven-johnson** [comment]
Yeah, that probably is happening -- I got sucked into a late Friday afternoon premature optimization rathole. I'll recheck the statusquo and if the optimization is happening at reasonable optimizer levels, I'll drop this.

**Comment by abadams** [comment]
You could always force-inline it if you're getting code size issues in a debug build

**Comment by steven-johnson** [comment]
Nah, the only thing I really wanted to accomplish was streamlining copy_from() (PR#4026) and verifying my changes via disassembly led me to this temptation .

**Comment by steven-johnson** [comment]
Yeah, the templatized call was overkill (an 'ordinary' method gets inlined as you suspect), but the previous code wasn't able to elide the new, as the compile-time knowledge got lost via the store-and-load from buf.dimensions. PTAL.

Also note the drive-by change to use std::copy; at least for my compiler, this gets translated into a call to memmove (since the things being copied are POD).

**Comment by steven-johnson** [comment]
(rebased to minimize cruft)

**Pull request merged**
