### PR TITLE
Rename WITH_PTX to WITH_NVPTX so all WITH_* macros match LLVM component names

### PR DESCRIPTION
**Pull request by alexreinking**
I'm in the process of making CMake bundle LLVM as part of Halide and I'm finding that I need to contort my way around these defines because one of them -- WITH_PTX -- is not named after its corresponding LLVM component, NVPTX.

This one small change drops ~60 lines of CMake while touching ~10 lines elsewhere.

### CODE REVIEW

**Comment by abadams** [comment]
Probably worth changing the other uses in the makefile for consistency too.

**Comment by alexreinking** [comment]
> Probably worth changing the other uses in the makefile for consistency too.

Done

**Comment by abadams** [comment]
LGTM but also would like an OK from @steven-johnson

**Comment by alexreinking** [comment]
Failure is unrelated (trunk LLVM on HVX)

**Pull request merged**
