### PR TITLE
Fix #5012

### LINKED ISSUE #5012: cuda test error_atomics_gpu_mutex fails
The `error_atomics_gpu_mutex` test started failing for me after #4997 was merged, a couple days ago.

```
build$ HL_JIT_TARGET=host-cuda ctest -V -R error_atomics_gpu_mutex
UpdateCTestConfiguration  from :/home/infinoid/workspace/halide/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/infinoid/workspace/halide/build/DartConfiguration.tcl
Test project /home/infinoid/workspace/halide/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 348
    Start 348: error_atomics_gpu_mutex

348: Test command: /home/infinoid/workspace/halide/build/test/error/error_atomics_gpu_mutex
348: Test timeout computed to be: 10000000
348: Success!
1/1 Test #348: error_atomics_gpu_mutex ..........***Failed  Required regular expression found. Regex=[Success!]  1.96 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
error    =   1.96 sec*proc (1 test)

Total Test time (real) =   1.99 sec

The following tests FAILED:
	348 - error_atomics_gpu_mutex (Failed)
Errors while running CTest
```

Git commit 941a576f8326e5846717f6ea11b70af8128d0fdf fails.
Git commit b126ef7c2a611fffa0bf4d79249c62a18f90a356 succeeds.

I am using cuda 10.2, gcc 7.5.0 on linux amd64.

### PR DESCRIPTION
**Pull request by abadams**
The atomics gpu mutex test is now possible to run on the GPU, so it's not an error anymore. Made the test case harder so that it requires a mutex again.

### CODE REVIEW

**Comment by steven-johnson** [comment]
https://buildbot.halide-lang.org/master/#/builders/29/builds/81

FAILED TEST: half_native_interleave
correctness_half_native_interleave: /home/halidenightly/build_bot/worker/linux-64-gcc53-testbranch-trunk/llvm-project/llvm/include/llvm/Support/Alignment.h:78: llvm::Align::Align(uint64_t): Assertion `llvm::isPowerOf2_64(Value) && "Alignment is not a power of 2"' failed.
/home/halidenightly/build_bot/worker/linux-64-gcc53-testbranch-trunk/halide/Makefile:1904: recipe for target 'quiet_correctness_half_native_interleave' failed

FAILED TEST: hexagon_scatter
correctness_hexagon_scatter: /home/halidenightly/build_bot/worker/linux-64-gcc53-testbranch-trunk/llvm-project/llvm/include/llvm/Support/Alignment.h:78: llvm::Align::Align(uint64_t): Assertion `llvm::isPowerOf2_64(Value) && "Alignment is not a power of 2"' failed.
/home/halidenightly/build_bot/worker/linux-64-gcc53-testbranch-trunk/halide/Makefile:1904: recipe for target 'quiet_correctness_hexagon_scatter' failed

**Comment by alexreinking** [comment]
@steven-johnson - I don't think this change could possibly have introduced those failures. It only touches `test/error/atomics_gpu_mutex.cpp`

**Comment by steven-johnson** [comment]
> @steven-johnson - I don't think this change could possibly have introduced those failures. It only touches `test/error/atomics_gpu_mutex.cpp`

Hopefully just a blip then. Let's let the resync-to-master finish and see if it clears up.

**Comment by steven-johnson** [comment]
@alexreinking The failure on Windows is puzzling (and presumably related to the Ninja changes already being in place there):

https://buildbot.halide-lang.org/master/#/builders/15/builds/158/steps/14/logs/stdio

```
FAILED: haar_x.runtime.lib 
cmd.exe /C "cd /D D:\build_bot\worker\win-64-testbranch-1000\halide-Release\apps\app_test_wavelet && "C:\Program Files\CMake\bin\cmake.exe" -E env "PATH=[ELIDED]" D:/build_bot/worker/win-64-testbranch-1000/halide-Release/apps/app_test_wavelet/wavelet.generator.exe -r haar_x.runtime -o . target=host"
This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
```

**Pull request merged**
