### PR TITLE
Add hexagon_benchmarks app for CMake builds

### PR DESCRIPTION
**Pull request by prasmish**
This PR addresses the issue raised in #5374 regarding the lack of CMake support for hexagon_benchmark. Specifically, it introduces CMake build support for the `hexagon_benchmark` app which was previously missing.

During the process of adding this support, I observed that the `sobel` test was not building correctly with the target `host-hvx`. To keep this PR focused and manageable, the `sobel` test has been temporarily removed from this CMake script. A separate PR will be raised to rectify this issue and reintroduce the `sobel` test.

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]
Thanks so much for this fix! LGTM pending green.

**Comment by steven-johnson** [comment]
```
FAILED: hexagon_benchmarks/dilate3x3.generator 
: && /usr/bin/g++-9 -O3 -DNDEBUG -lc++abi hexagon_benchmarks/CMakeFiles/dilate3x3.generator.dir/dilate3x3_generator.cpp.o hexagon_benchmarks/CMakeFiles/dilate3x3.generator.dir/home/halidenightly/build_bot/worker/halide-testbranch-main-llvm17-x86-64-linux-cmake/halide-install/share/tools/GenGen.cpp.o -o hexagon_benchmarks/dilate3x3.generator  -Wl,-rpath,/home/halidenightly/build_bot/worker/halide-testbranch-main-llvm17-x86-64-linux-cmake/halide-install/lib  /home/halidenightly/build_bot/worker/halide-testbranch-main-llvm17-x86-64-linux-cmake/halide-install/lib/libHalide.so.18.0.0  -ldl && :
/usr/bin/ld: cannot find -lc++abi
```

**Comment by prasmish** [comment]
Earlier, I was building Halide with Clang, which led to a minor issue here. I’ve now eliminated an unneeded flag (-lc++abi) and now it should build smoothly.

**Comment by steven-johnson** [comment]
Failures are unrelated

**Pull request merged**
