### PR TITLE
Fix clang-tidy-19 errors

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Review by alexreinking — APPROVED** [review]

**Comment by abadams** [comment]
I think the change in HalideBuffer.h here caused #8534 

It's supposed to take src by value because make_with_shape_of_helper mutates src.buf.dim in-place.

**Comment by abadams** [comment]
A nice reminder that we should always wait for the tests to go green, even on trivial PRs.

**Comment by steven-johnson** [comment]
I'm confused about this diagnosis -- if it's mutating it in-place then how is it compiling now (since it's a const ref)?

**Comment by abadams** [comment]
It's taking a copy of a pointer member that points to storage contained within the same class (the dims array)

**Pull request merged**
