### PR TITLE
Fix CMakeLists.txt for msvc

### PR DESCRIPTION
**Pull request by mugwort-rc**

### CODE REVIEW

**Comment by steven-johnson** [comment]
LGTM, but we haven't been encountering problems with this -- can you share what sort of problem this caused, so I can test it?

**Comment by mugwort-rc** [comment]
It seems `CMAKE_BUILD_TYPE` is empty.

I'm using 

* cmake: 3.15.0-rc2
* Visual Studio 2019 Professional
* Halide@21f3be8

----------

cmake **without** `CMAKE_BUILD_TYPE`

```
X:\halide-3954>cmake ..\Halide-21f3be8
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.21.27702.2
-- The CXX compiler identification is MSVC 19.21.27702.2
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LLVM 8.0.0
-- Using LLVMConfig.cmake in: C:/Program Files (x86)/LLVM/lib/cmake/llvm
Windows: setting CMAKE_OBJECT_PATH_MAX to 260
CMake Error at CMakeLists.txt:102 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:111 (check_tool_exists)


-- Using llvm-as at C:/Program Files (x86)/LLVM/bin/llvm-as.exe
CMake Error at CMakeLists.txt:102 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:112 (check_tool_exists)


-- Using llvm-nm at C:/Program Files (x86)/LLVM/bin/llvm-nm.exe
CMake Error at CMakeLists.txt:102 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:113 (check_tool_exists)


-- Using clang at C:/Program Files (x86)/LLVM/bin/clang.exe
-- WARNINGS_AS_ERRORS enabled
-- Found OpenMP
-- PNG not found for _halide_library_from_generator_rungen; compiling with -DHALIDE_NO_PNG
-- JPEG not found for _halide_library_from_generator_rungen; compiling with -DHALIDE_NO_JPEG
-- Performing Test SUPPORTS_SIZED_DEALLOC
-- Performing Test SUPPORTS_SIZED_DEALLOC - Success
-- Building tests enabled
-- Internal tests enabled
-- PNG not found for correctness_image_io; compiling with -DHALIDE_NO_PNG
-- JPEG not found for correctness_image_io; compiling with -DHALIDE_NO_JPEG
-- Found OpenGL: opengl32
-- Building apps enabled
-- PNG not found for bilateral_grid_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for bilateral_grid_process; compiling with -DHALIDE_NO_JPEG
-- PNG not found for conv_layer_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for conv_layer_process; compiling with -DHALIDE_NO_JPEG
-- PNG not found for interpolate; compiling with -DHALIDE_NO_PNG
-- JPEG not found for interpolate; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lens_blur_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lens_blur_process; compiling with -DHALIDE_NO_JPEG
-- linear_algebra: No CBLAS header, skipping CBLAS tests
-- Performing Test CAN_ENABLE_FTZ_DAZ
-- Performing Test CAN_ENABLE_FTZ_DAZ - Success
-- linear_algebra: Eigen3 Missing, skipping Eigen3 benchmarks
-- linear_algebra: No CBLAS header, skipping BLAS benchmarks
-- PNG not found for run_linear_blur; compiling with -DHALIDE_NO_PNG
-- JPEG not found for run_linear_blur; compiling with -DHALIDE_NO_JPEG
-- PNG not found for local_laplacian_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for local_laplacian_process; compiling with -DHALIDE_NO_JPEG
-- PNG not found for nl_means_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for nl_means_process; compiling with -DHALIDE_NO_JPEG
-- PNG not found for stencil_chain_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for stencil_chain_process; compiling with -DHALIDE_NO_JPEG
-- Building tutorials enabled
-- Performing Test SUPPORT_NO_UNUSED_BUT_SET_VARIABLE
-- Performing Test SUPPORT_NO_UNUSED_BUT_SET_VARIABLE - Failed
-- PNG not found for lesson_02_input_image; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_02_input_image; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lesson_07_multi_stage_pipelines; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_07_multi_stage_pipelines; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lesson_08_scheduling_2; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_08_scheduling_2; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lesson_09_update_definitions; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_09_update_definitions; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lesson_12_using_the_gpu; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_12_using_the_gpu; compiling with -DHALIDE_NO_JPEG
-- Building utils enabled
-- PNG not found for HalideTraceDump; compiling with -DHALIDE_NO_PNG
-- JPEG not found for HalideTraceDump; compiling with -DHALIDE_NO_JPEG
-- Configuring incomplete, errors occurred!
See also "X:/halide-3954/CMakeFiles/CMakeOutput.log".
See also "X:/halide-3954/CMakeFiles/CMakeError.log".
```

----------

cmake **with** `CMAKE_BUILD_TYPE`

```
X:\halide-3954-with-CMAKE_BUILD_TYPE>cmake -DCMAKE_BUILD_TYPE=Release ..\Halide-21f3be8
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.21.27702.2
-- The CXX compiler identification is MSVC 19.21.27702.2
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LLVM 8.0.0
-- Using LLVMConfig.cmake in: C:/Program Files (x86)/LLVM/lib/cmake/llvm
Windows: setting CMAKE_OBJECT_PATH_MAX to 260
-- Using llvm-as at C:/Program Files (x86)/LLVM/bin/llvm-as.exe
-- Using llvm-nm at C:/Program Files (x86)/LLVM/bin/llvm-nm.exe
-- Using clang at C:/Program Files (x86)/LLVM/bin/clang.exe
-- WARNINGS_AS_ERRORS enabled
-- Found OpenMP
-- PNG not found for _halide_library_from_generator_rungen; compiling with -DHALIDE_NO_PNG
-- JPEG not found for _halide_library_from_generator_rungen; compiling with -DHALIDE_NO_JPEG
-- Performing Test SUPPORTS_SIZED_DEALLOC
-- Performing Test SUPPORTS_SIZED_DEALLOC - Success
-- Building tests enabled
-- Internal tests enabled
-- PNG not found for correctness_image_io; compiling with -DHALIDE_NO_PNG
-- JPEG not found for correctness_image_io; compiling with -DHALIDE_NO_JPEG
-- Found OpenGL: opengl32
-- Building apps enabled
-- PNG not found for bilateral_grid_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for bilateral_grid_process; compiling with -DHALIDE_NO_JPEG
-- PNG not found for conv_layer_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for conv_layer_process; compiling with -DHALIDE_NO_JPEG
-- PNG not found for interpolate; compiling with -DHALIDE_NO_PNG
-- JPEG not found for interpolate; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lens_blur_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lens_blur_process; compiling with -DHALIDE_NO_JPEG
-- linear_algebra: No CBLAS header, skipping CBLAS tests
-- Performing Test CAN_ENABLE_FTZ_DAZ
-- Performing Test CAN_ENABLE_FTZ_DAZ - Success
-- linear_algebra: Eigen3 Missing, skipping Eigen3 benchmarks
-- linear_algebra: No CBLAS header, skipping BLAS benchmarks
-- PNG not found for run_linear_blur; compiling with -DHALIDE_NO_PNG
-- JPEG not found for run_linear_blur; compiling with -DHALIDE_NO_JPEG
-- PNG not found for local_laplacian_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for local_laplacian_process; compiling with -DHALIDE_NO_JPEG
-- PNG not found for nl_means_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for nl_means_process; compiling with -DHALIDE_NO_JPEG
-- PNG not found for stencil_chain_process; compiling with -DHALIDE_NO_PNG
-- JPEG not found for stencil_chain_process; compiling with -DHALIDE_NO_JPEG
-- Building tutorials enabled
-- Performing Test SUPPORT_NO_UNUSED_BUT_SET_VARIABLE
-- Performing Test SUPPORT_NO_UNUSED_BUT_SET_VARIABLE - Failed
-- PNG not found for lesson_02_input_image; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_02_input_image; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lesson_07_multi_stage_pipelines; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_07_multi_stage_pipelines; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lesson_08_scheduling_2; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_08_scheduling_2; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lesson_09_update_definitions; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_09_update_definitions; compiling with -DHALIDE_NO_JPEG
-- PNG not found for lesson_12_using_the_gpu; compiling with -DHALIDE_NO_PNG
-- JPEG not found for lesson_12_using_the_gpu; compiling with -DHALIDE_NO_JPEG
-- Building utils enabled
-- PNG not found for HalideTraceDump; compiling with -DHALIDE_NO_PNG
-- JPEG not found for HalideTraceDump; compiling with -DHALIDE_NO_JPEG
-- Configuring done
-- Generating done
-- Build files have been written to: X:/halide-3954-with-CMAKE_BUILD_TYPE
```

**Comment by steven-johnson** [comment]
Ah, that might explain it, as I think our build systems always explicitly specify CMAKE_BUILD_TYPE. Let me clone this PR for testing.

**Comment by steven-johnson** [comment]
Thanks for the fix!

**Pull request merged**
