### PR TITLE
Fix HelloAndroidCamera2 builds

### PR DESCRIPTION
**Pull request by steven-johnson**
Fix various build problems that have crept in; also update gitignore
and move intermediate products to the bin/ directory

### CODE REVIEW

**Comment by steven-johnson** [comment]
(Addresses Issue #1632)

**Comment by abadams** [comment]
@jiawen PTAL if you have a moment. Android Studio keeps moving out from underneath us.

**Comment by steven-johnson** [comment]
Heh, this already didn't build properly if the CMake folder was named anything other than "build": I routinely name mine "cmake_build" and neither include-paths nor link-paths are correct.

Short-term, we should probably back out this change (and allow the build to assume the build/ target).

Long-term, we should probably have all apps/ rely only on the distirb/ folder target (ie, the "public" distro), but I don't think the CMake rules build one of those at present...

**Comment by jiawen** [comment]
+1

**Comment by jiawen** [comment]
Tested on device, LGTM.

**Pull request merged**
