### PR TITLE
Remove some code in prefetch that looked unnecessary

### PR DESCRIPTION
**Pull request by abadams**
Large speedup in lowering for all pipelines (3x for local laplacian!).

I don't see why we need to expand prefetch bounds based on *outer* lets
and loops -- we're not lifting code outside of them. box_touched at the
right scope should do the right thing for us.

Along the way I discovered we have no correctness tests for prefetch?! Eyeballing the IR, it looks right, but I have no confidence.

@dsharletg @psuriana PTAL

### CODE REVIEW

**Comment by steven-johnson** [comment]
Is this going to land on its own, or as part of #2530?

**Comment by abadams** [comment]
I was assuming it would land on its own

**Comment by abadams** [comment]
I got an out-of-band lgtm from @dsharletg in terms of performance and correctness.

**Comment by steven-johnson** [comment]
LGTM, but as mentioned above, some sort of testing for prefetch (other than eyeballs) would really be good.

**Comment by dpalermo** [comment]
Also, LGTM.   As for testing, both apps/camera_pipe and apps/HelloHexagon use the .prefetch directive so if those compile & run then you haven't introduced a correctness issue.  Performance is a different matter.  We can run some tests using this patch or just wait until it is committed to see if there are any changes in performance.  Given the change, I am fine with either approach.

**Pull request merged**
