### PR TITLE
Clone of Generate Python extension modules #2975

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by matthiaskramm** [comment]
Some errors, but they seem unrelated to this PR.

```
Testing lesson_12_using_the_gpu...
terminate called after throwing an instance of 'Halide::Error'
  what():  CL: clGetPlatformIDs failed: <Unknown error> -1001
Aborted (core dumped)
```

```
bash: line 1: 17939 Aborted                 (core dumped) /home/halidenightly/build_bot/worker/linux-64-gcc53-testbranch-500/halide-build/bin/correctness_bounds_inference
../halide/Makefile:1479: recipe for target 'correctness_bounds_inference' failed
```

**Comment by steven-johnson** [comment]
The Mac failures might be related, they are in the python tests:

dyld: termination function 0x108fa45b0 not in mapped image for /Users/halidenightly/build_bot_new/worker/mac-64-testbranch-500/halide-build/bin/python3_bindings/ext/bit.so

**Comment by matthiaskramm** [comment]
That error is weird. It's Mac specific, and the internet has very little to say about how this typically occurs, and nothing at all about why/how this would occur in a Python extension. The best I could find was https://osqa-ask.wireshark.org/questions/61106/compilation-with-macports-plugins-fail-to-load which seems to indicate that the issue might come in through a duplicate dynamic library, which sounds more like an issue with the platform setup than with the unit test in question.

However, there *was* a redundant (but not duplicate?) library in the Python tests, so I removed that.
It might be worth a shot re-running tests with that change, on mac-64. But if that doesn't work, I'm tempted to just disable ` test_correctness_bit_test` on Mac, to get things moving again.

**Comment by matthiaskramm** [comment]
Ended up moving the test in question to its own PR. It only tests an edge case (bit arrays) that doesn't work on Python, anyway, so it's not critical to the rest of the PR. And the latter is big enough already.

**Pull request closed without merging**
