### PR TITLE
Add support for ImageStack's .tmp format to halide_image_io.h

### PR DESCRIPTION
**Pull request by steven-johnson**

### CODE REVIEW

**Comment by steven-johnson** [comment]
There's talk elsewhere of having ImageStack add support for .mat-level-5 files (Matlab), in which case .tmp file support would be unnecessary... so we should probably hold off landing this until that's resolved.

**Comment by abadams** [comment]
.mat seems to still be a simple header followed by the raw data, so I think we'll need most of this code

**Comment by steven-johnson** [comment]
Sure, but .tmp itself is probably not useful once we add .mat to this (and ImageStack)

**Comment by abadams** [comment]
True, I guess it doesn't hurt to leave the code in a branch and go scavenge it when we do .mat

**Comment by abadams** [comment]
I got stuck on .mat support. Can't get octave to understand my mat files. I'll just merge this for now.

**Pull request merged**
