### PR TITLE
added makefile changes to build for amdgpu

### PR DESCRIPTION
**Pull request by adityaatluri**
1. Changed Makefile to enable compile flag WITH_AMDGPU
2. Changed CodeGen_LLVM file to check if intializing amdgpu works or not

Need to enable AMDGPU backend when building LLVM

### CODE REVIEW

**Comment by zvookin** [comment]
Can you add the corresponding changes to src/CMakeLists.txt? Some of our build configurations require cmake and I'd like to make sure we don't inadvertently break them.

We'll need to decide if we want to merge something like this in small pieces.  I think it should be ok, but I'd like there to be a comment in the Makefile that this support doesn't work yet.

**Comment by adityaatluri** [comment]
@zvookin Did a few comments about build status and changed cmake. Let me know if you want me to change something

**Comment by adityaatluri** [comment]
@zvookin anything I need to change? I have few more changes lined up

**Comment by zvookin** [comment]
I'm good with this. @abadams Any comments?

**Comment by abadams** [comment]
This PR doesn't look like it does anything. This is being merged in small pieces for some reason? At some point in the process we'll need to change the buildbot scripts to enable the amdgpu backend in llvm.

**Comment by adityaatluri** [comment]
I wanted to make sure build system works before adding code to it. Taking one step at a time.

**Comment by adityaatluri** [comment]
@abadams @zvookin Do you want me to work on the same branch or create a new branch and PR?

**Comment by zvookin** [comment]
Continuing on the same branch and making pull requests from it is likely the best way to go.

**Comment by adityaatluri** [comment]
Sure. Where to go from here? (I am starting from `CodeGen_AMDGPU_Dev.h` and `CodeGen_AMDGPU_Dev.cpp` by replicating `CodeGen_NVPTX_Dev.h` and `CodeGen_NVPTX_Dev.cpp`). Please let me know otherwise.

**Comment by zvookin** [comment]
Those are a good place to start. You can look at the d3d12 and vulkan branches to see all the things that are done to add a new GPU backend. These are both in progress.

**Comment by adityaatluri** [comment]
Great! Where can I ask questions about source structure and its functionality?

**Comment by shoaibkamil** [comment]
The [gitter channel](https://gitter.im/halide/Halide) is probably the best place to ask questions.

**Comment by adityaatluri** [comment]
@abadams do you have eta on when amdgpu backend gets enabled for llvm ci build?

**Pull request merged**
